package jnr.constants.platform;

import jnr.constants.Constant;

// $VF: Compiled from LastError.java
public enum LastError implements Constant {
   ERROR_INVALID_FUNCTION,
   WSASYSCALLFAILURE,
   ERROR_NOT_ENOUGH_QUOTA,
   WSAENOTCONN,
   WSAESOCKTNOSUPPORT,
   ERROR_NO_DATA,
   WSAEPFNOSUPPORT,
   ERROR_BAD_NET_NAME,
   ERROR_BROKEN_PIPE,
   WSAEBADF,
   WSAEACCES,
   ERROR_FILE_EXISTS,
   ERROR_WRONG_DISK,
   ERROR_OUT_OF_PAPER,
   WSAEINPROGRESS,
   ERROR_ALREADY_EXISTS,
   WSAEAFNOSUPPORT,
   ERROR_DISK_FULL,
   ERROR_NOT_SAME_DEVICE,
   WSANO_DATA,
   ERROR_IOPL_NOT_ENABLED,
   ERROR_RING2SEG_MUST_BE_MOVABLE,
   WSAENOTEMPTY,
   WSAESHUTDOWN,
   ERROR_INVALID_TARGET_HANDLE,
   ERROR_NO_MORE_FILES,
   ERROR_LOCK_VIOLATION,
   WSAEUSERS,
   WSAETOOMANYREFS,
   WSAENETDOWN,
   WSAECONNREFUSED,
   ERROR_NOT_READY,
   ERROR_BAD_PIPE,
   WSAECONNRESET,
   WSA_E_NO_MORE,
   ERROR_INVALID_DATA,
   ERROR_PIPE_NOT_CONNECTED,
   ERROR_CANNOT_MAKE,
   ERROR_INVALID_DRIVE,
   ERROR_SEEK,
   ERROR_LOCK_FAILED,
   ERROR_EXE_MARKED_INVALID,
   ERROR_NESTING_NOT_ALLOWED,
   __UNKNOWN_CONSTANT__,
   ERROR_PATH_NOT_FOUND,
   ERROR_CURRENT_DIRECTORY,
   ERROR_NO_PROC_SLOTS,
   WSAHOST_NOT_FOUND,
   ERROR_BAD_EXE_FORMAT,
   WSAENETUNREACH,
   ERROR_INVALID_EXE_SIGNATURE,
   WSAEHOSTDOWN,
   ERROR_NETWORK_ACCESS_DENIED,
   ERROR_INVALID_MODULETYPE,
   WSATYPE_NOT_FOUND,
   WSAEPROTOTYPE,
   WSAETIMEDOUT,
   WSAESTALE,
   WSAEREMOTE,
   WSASYSNOTREADY,
   WSAENAMETOOLONG,
   ERROR_INVALID_PARAMETER,
   ERROR_NEGATIVE_SEEK,
   ERROR_ACCESS_DENIED,
   WSAEWOULDBLOCK,
   ERROR_ITERATED_DATA_EXCEEDS_64k,
   WSAECANCELLED,
   ERROR_NOT_DOS_DISK,
   ERROR_DIR_NOT_EMPTY,
   ERROR_PIPE_BUSY,
   WSAENOBUFS,
   ERROR_GEN_FAILURE,
   WSAEPROCLIM,
   ERROR_BAD_NETPATH,
   ERROR_NOT_ENOUGH_MEMORY,
   ERROR_INFLOOP_IN_RELOC_CHAIN,
   WSAELOOP,
   ERROR_AUTODATASEG_EXCEEDS_64k,
   ERROR_INVALID_SEGDPL,
   ERROR_SECTOR_NOT_FOUND,
   ERROR_OPERATION_ABORTED,
   WSAEREFUSED,
   ERROR_FAIL_I24,
   WSAEFAULT,
   WSAEPROVIDERFAILEDINIT,
   ERROR_BAD_FORMAT,
   WSAEADDRINUSE,
   ERROR_BAD_ENVIRONMENT,
   WSA_E_CANCELLED,
   WSAEADDRNOTAVAIL,
   ERROR_SEEK_ON_DEVICE,
   WSAEINTR,
   WSAEMFILE,
   WSAEHOSTUNREACH,
   ERROR_WRITE_FAULT,
   ERROR_MOD_NOT_FOUND,
   WSAVERNOTSUPPORTED,
   ERROR_CHILD_NOT_COMPLETE,
   WSAEINVALIDPROVIDER,
   WSAECONNABORTED,
   WSAENOTSOCK,
   ERROR_NOT_LOCKED,
   ERROR_WAIT_NO_CHILDREN,
   ERROR_MAX_THRDS_REACHED,
   ERROR_INVALID_MINALLOCSIZE,
   ERROR_FILE_NOT_FOUND,
   WSANO_RECOVERY,
   ERROR_BAD_UNIT,
   ERROR_BAD_PATHNAME,
   WSAEINVAL,
   ERROR_ARENA_TRASHED,
   ERROR_PIPE_LOCAL,
   ERROR_DIRECTORY,
   ERROR_INVALID_STARTING_CODESEG,
   ERROR_WRITE_PROTECT,
   ERROR_INVALID_STACKSEG,
   ERROR_INVALID_BLOCK,
   WSAEINVALIDPROCTABLE,
   WSAEOPNOTSUPP,
   ERROR_CRC,
   ERROR_DIRECT_ACCESS_HANDLE,
   ERROR_DRIVE_LOCKED,
   ERROR_BAD_COMMAND,
   WSAENOPROTOOPT,
   ERROR_INVALID_ACCESS,
   WSAENOMORE,
   WSAENETRESET,
   ERROR_TOO_MANY_OPEN_FILES,
   WSAEPROTONOSUPPORT,
   WSAEISCONN,
   ERROR_INVALID_HANDLE,
   WSATRY_AGAIN,
   ERROR_SHARING_BUFFER_EXCEEDED,
   ERROR_READ_FAULT,
   WSAEMSGSIZE,
   ERROR_DYNLINK_FROM_INVALID_RING,
   ERROR_SHARING_VIOLATION,
   WSASERVICE_NOT_FOUND,
   ERROR_FILENAME_EXCED_RANGE,
   WSAEDISCON,
   WSAEDESTADDRREQ,
   WSAEDQUOT,
   ERROR_BAD_LENGTH,
   ERROR_RELOC_CHAIN_XEEDS_SEGLIM,
   WSANOTINITIALISED,
   WSAEALREADY;

   private static final ConstantResolver<LastError> resolver = ConstantResolver.getResolver(LastError.class, 20000, 20999);

   @Override
   public final int intValue() {
      return (int)resolver.longValue(this);
   }

   public static LastError valueOf(long value) {
      return resolver.valueOf(value);
   }

   @Override
   public final long longValue() {
      return resolver.longValue(this);
   }

   @Override
   public final boolean defined() {
      return resolver.defined(this);
   }

   @Override
   public final String toString() {
      return this.description();
   }

   public final String description() {
      return resolver.description(this);
   }

   public final int value() {
      return (int)resolver.longValue(this);
   }
}
