/*
 * Decompiled with CFR 0.152.
 */
package jnr.constants.platform;

import jnr.constants.Constant;
import jnr.constants.platform.ConstantResolver;

public final class Errno
extends Enum<Errno>
implements Constant {
    public static final /* enum */ Errno EMLINK;
    public static final /* enum */ Errno EALREADY;
    public static final /* enum */ Errno ENOLINK;
    public static final /* enum */ Errno EHWPOISON;
    public static final /* enum */ Errno EDEADLK;
    public static final /* enum */ Errno EKEYEXPIRED;
    public static final /* enum */ Errno EXFULL;
    public static final /* enum */ Errno EBFONT;
    public static final /* enum */ Errno EL3HLT;
    public static final /* enum */ Errno EWOULDBLOCK;
    public static final /* enum */ Errno ESPIPE;
    public static final /* enum */ Errno ENOLCK;
    public static final /* enum */ Errno EDESTADDRREQ;
    public static final /* enum */ Errno ENFILE;
    public static final /* enum */ Errno EFTYPE;
    public static final /* enum */ Errno EPFNOSUPPORT;
    public static final /* enum */ Errno EFBIG;
    public static final /* enum */ Errno ETIMEDOUT;
    public static final /* enum */ Errno ENOPKG;
    public static final /* enum */ Errno EIPSEC;
    public static final /* enum */ Errno ERPCMISMATCH;
    public static final /* enum */ Errno ENOTUNIQ;
    public static final /* enum */ Errno __UNKNOWN_CONSTANT__;
    public static final /* enum */ Errno EREMOTE;
    public static final /* enum */ Errno EBADMSG;
    public static final /* enum */ Errno ESTALE;
    public static final /* enum */ Errno EUNATCH;
    public static final /* enum */ Errno ESOCKTNOSUPPORT;
    public static final /* enum */ Errno ENOATTR;
    public static final /* enum */ Errno EOVERFLOW;
    public static final /* enum */ Errno EKEYREJECTED;
    public static final /* enum */ Errno ENODEV;
    public static final /* enum */ Errno ENOMEDIUM;
    public static final /* enum */ Errno EPROGMISMATCH;
    public static final /* enum */ Errno ENOSPC;
    public static final /* enum */ Errno ENOTCAPABLE;
    public static final /* enum */ Errno ENOSR;
    public static final /* enum */ Errno ENOANO;
    public static final /* enum */ Errno ENONET;
    public static final /* enum */ Errno ENOENT;
    public static final /* enum */ Errno ENOKEY;
    public static final /* enum */ Errno ENODATA;
    public static final /* enum */ Errno EDOOFUS;
    public static final /* enum */ Errno EBADR;
    public static final /* enum */ Errno ENETDOWN;
    public static final /* enum */ Errno ECAPMODE;
    public static final /* enum */ Errno EIO;
    public static final /* enum */ Errno ENOSYS;
    public static final /* enum */ Errno EL3RST;
    public static final /* enum */ Errno EISNAM;
    public static final /* enum */ Errno ENETUNREACH;
    public static final /* enum */ Errno EOWNERDEAD;
    public static final /* enum */ Errno ENOMSG;
    public static final /* enum */ Errno EBADRQC;
    public static final /* enum */ Errno ENEEDAUTH;
    public static final /* enum */ Errno ELIBSCN;
    public static final /* enum */ Errno EBADE;
    public static final /* enum */ Errno EPERM;
    public static final /* enum */ Errno ENOTDIR;
    public static final /* enum */ Errno ELIBEXEC;
    public static final /* enum */ Errno EUSERS;
    public static final /* enum */ Errno EMEDIUMTYPE;
    public static final /* enum */ Errno ENOPROTOOPT;
    public static final /* enum */ Errno ESRCH;
    public static final /* enum */ Errno EDEADLOCK;
    public static final /* enum */ Errno EPIPE;
    public static final /* enum */ Errno ECONNREFUSED;
    public static final /* enum */ Errno ENOTSOCK;
    public static final /* enum */ Errno ECONNABORTED;
    public static final /* enum */ Errno ETXTBSY;
    public static final /* enum */ Errno ESHUTDOWN;
    public static final /* enum */ Errno ENOSTR;
    public static final /* enum */ Errno ECOMM;
    public static final /* enum */ Errno ELIBACC;
    public static final /* enum */ Errno EPROGUNAVAIL;
    public static final /* enum */ Errno EILSEQ;
    public static final /* enum */ Errno ENAMETOOLONG;
    public static final /* enum */ Errno EFAULT;
    public static final /* enum */ Errno EXDEV;
    public static final /* enum */ Errno EPROCLIM;
    public static final /* enum */ Errno EINTR;
    public static final /* enum */ Errno EPROTONOSUPPORT;
    public static final /* enum */ Errno ENOCSI;
    public static final /* enum */ Errno ESRMNT;
    public static final /* enum */ Errno EISCONN;
    public static final /* enum */ Errno ERESTART;
    public static final /* enum */ Errno ENAVAIL;
    public static final /* enum */ Errno ELOOP;
    public static final /* enum */ Errno ELNRNG;
    public static final /* enum */ Errno ENOTBLK;
    public static final /* enum */ Errno EAFNOSUPPORT;
    public static final /* enum */ Errno ETOOMANYREFS;
    public static final /* enum */ Errno E2BIG;
    public static final /* enum */ Errno EHOSTDOWN;
    public static final /* enum */ Errno ENOMEM;
    public static final /* enum */ Errno EPROCUNAVAIL;
    public static final /* enum */ Errno EOPNOTSUPP;
    public static final /* enum */ Errno EADDRINUSE;
    public static final /* enum */ Errno EL2NSYNC;
    public static final /* enum */ Errno EIDRM;
    public static final /* enum */ Errno ELIBBAD;
    public static final /* enum */ Errno EREMOTEIO;
    public static final /* enum */ Errno ENOTEMPTY;
    public static final /* enum */ Errno EBADFD;
    public static final /* enum */ Errno EINPROGRESS;
    public static final /* enum */ Errno EDOTDOT;
    public static final /* enum */ Errno EREMCHG;
    public static final /* enum */ Errno ENOTRECOVERABLE;
    public static final /* enum */ Errno ENXIO;
    public static final /* enum */ Errno EKEYREVOKED;
    public static final /* enum */ Errno ENOEXEC;
    public static final /* enum */ Errno EDOM;
    public static final /* enum */ Errno EADDRNOTAVAIL;
    public static final /* enum */ Errno ENETRESET;
    public static final /* enum */ Errno ESTRPIPE;
    public static final /* enum */ Errno EADV;
    public static final /* enum */ Errno ECHILD;
    public static final /* enum */ Errno EBADRPC;
    public static final /* enum */ Errno EBADF;
    public static final /* enum */ Errno EHOSTUNREACH;
    public static final /* enum */ Errno ELIBMAX;
    public static final /* enum */ Errno EAUTH;
    public static final /* enum */ Errno EL2HLT;
    public static final /* enum */ Errno ENOTNAM;
    public static final /* enum */ Errno ECANCELED;
    public static final /* enum */ Errno EBADSLT;
    public static final /* enum */ Errno ETIME;
    public static final /* enum */ Errno ERANGE;
    public static final /* enum */ Errno EACCES;
    private static final /* synthetic */ Errno[] $VALUES;
    public static final /* enum */ Errno EROFS;
    public static final /* enum */ Errno ENOTTY;
    private static final ConstantResolver<Errno> resolver;
    public static final /* enum */ Errno ERFKILL;
    public static final /* enum */ Errno ECHRNG;
    public static final /* enum */ Errno EBUSY;
    public static final /* enum */ Errno ENOBUFS;
    public static final /* enum */ Errno EDQUOT;
    public static final /* enum */ Errno EISDIR;
    public static final /* enum */ Errno ECONNRESET;
    public static final /* enum */ Errno EMSGSIZE;
    public static final /* enum */ Errno EPROTO;
    public static final /* enum */ Errno EAGAIN;
    public static final /* enum */ Errno EMFILE;
    public static final /* enum */ Errno EUCLEAN;
    public static final /* enum */ Errno EMULTIHOP;
    public static final /* enum */ Errno EEXIST;
    public static final /* enum */ Errno EINVAL;
    public static final /* enum */ Errno ENOTSUP;
    public static final /* enum */ Errno ENOTCONN;
    public static final /* enum */ Errno EPROTOTYPE;

    @Override
    public final long longValue() {
        return resolver.longValue(this);
    }

    public static Errno valueOf(long value) {
        return resolver.valueOf(value);
    }

    public static Errno valueOf(String name) {
        return Enum.valueOf(Errno.class, name);
    }

    public final String toString() {
        return this.description();
    }

    public final int value() {
        return (int)resolver.longValue(this);
    }

    @Override
    public final int intValue() {
        return (int)resolver.longValue(this);
    }

    @Override
    public final boolean defined() {
        return resolver.defined(this);
    }

    public static Errno[] values() {
        return (Errno[])$VALUES.clone();
    }

    public final String description() {
        return resolver.description(this);
    }

    static {
        EPERM = new Errno();
        ENOENT = new Errno();
        ESRCH = new Errno();
        EINTR = new Errno();
        EIO = new Errno();
        ENXIO = new Errno();
        E2BIG = new Errno();
        ENOEXEC = new Errno();
        EBADF = new Errno();
        ECHILD = new Errno();
        EDEADLK = new Errno();
        ENOMEM = new Errno();
        EACCES = new Errno();
        EFAULT = new Errno();
        ENOTBLK = new Errno();
        EBUSY = new Errno();
        EEXIST = new Errno();
        EXDEV = new Errno();
        ENODEV = new Errno();
        ENOTDIR = new Errno();
        EISDIR = new Errno();
        EINVAL = new Errno();
        ENFILE = new Errno();
        EMFILE = new Errno();
        ENOTTY = new Errno();
        ETXTBSY = new Errno();
        EFBIG = new Errno();
        ENOSPC = new Errno();
        ESPIPE = new Errno();
        EROFS = new Errno();
        EMLINK = new Errno();
        EPIPE = new Errno();
        EDOM = new Errno();
        ERANGE = new Errno();
        EWOULDBLOCK = new Errno();
        EAGAIN = new Errno();
        EINPROGRESS = new Errno();
        EALREADY = new Errno();
        ENOTSOCK = new Errno();
        EDESTADDRREQ = new Errno();
        EMSGSIZE = new Errno();
        EPROTOTYPE = new Errno();
        ENOPROTOOPT = new Errno();
        EPROTONOSUPPORT = new Errno();
        ESOCKTNOSUPPORT = new Errno();
        EOPNOTSUPP = new Errno();
        EPFNOSUPPORT = new Errno();
        EAFNOSUPPORT = new Errno();
        EADDRINUSE = new Errno();
        EADDRNOTAVAIL = new Errno();
        ENETDOWN = new Errno();
        ENETUNREACH = new Errno();
        ENETRESET = new Errno();
        ECONNABORTED = new Errno();
        ECONNRESET = new Errno();
        ENOBUFS = new Errno();
        EISCONN = new Errno();
        ENOTCONN = new Errno();
        ESHUTDOWN = new Errno();
        ETOOMANYREFS = new Errno();
        ETIMEDOUT = new Errno();
        ECONNREFUSED = new Errno();
        ELOOP = new Errno();
        ENAMETOOLONG = new Errno();
        EHOSTDOWN = new Errno();
        EHOSTUNREACH = new Errno();
        ENOTEMPTY = new Errno();
        EUSERS = new Errno();
        EDQUOT = new Errno();
        ESTALE = new Errno();
        EREMOTE = new Errno();
        ENOLCK = new Errno();
        ENOSYS = new Errno();
        EOVERFLOW = new Errno();
        EIDRM = new Errno();
        ENOMSG = new Errno();
        EILSEQ = new Errno();
        EBADMSG = new Errno();
        EMULTIHOP = new Errno();
        ENODATA = new Errno();
        ENOLINK = new Errno();
        ENOSR = new Errno();
        ENOSTR = new Errno();
        EPROTO = new Errno();
        ETIME = new Errno();
        ECHRNG = new Errno();
        EL2NSYNC = new Errno();
        EL3HLT = new Errno();
        EL3RST = new Errno();
        ELNRNG = new Errno();
        EUNATCH = new Errno();
        ENOCSI = new Errno();
        EL2HLT = new Errno();
        EBADE = new Errno();
        EBADR = new Errno();
        EXFULL = new Errno();
        ENOANO = new Errno();
        EBADRQC = new Errno();
        EBADSLT = new Errno();
        EDEADLOCK = new Errno();
        EBFONT = new Errno();
        ENONET = new Errno();
        ENOPKG = new Errno();
        EADV = new Errno();
        ESRMNT = new Errno();
        ECOMM = new Errno();
        EDOTDOT = new Errno();
        ENOTUNIQ = new Errno();
        EBADFD = new Errno();
        EREMCHG = new Errno();
        ELIBACC = new Errno();
        ELIBBAD = new Errno();
        ELIBSCN = new Errno();
        ELIBMAX = new Errno();
        ELIBEXEC = new Errno();
        ERESTART = new Errno();
        ESTRPIPE = new Errno();
        EUCLEAN = new Errno();
        ENOTNAM = new Errno();
        ENAVAIL = new Errno();
        EISNAM = new Errno();
        EREMOTEIO = new Errno();
        ECANCELED = new Errno();
        EKEYEXPIRED = new Errno();
        EKEYREJECTED = new Errno();
        EKEYREVOKED = new Errno();
        EMEDIUMTYPE = new Errno();
        ENOKEY = new Errno();
        ENOMEDIUM = new Errno();
        ENOTRECOVERABLE = new Errno();
        EOWNERDEAD = new Errno();
        ERFKILL = new Errno();
        EAUTH = new Errno();
        EBADRPC = new Errno();
        EDOOFUS = new Errno();
        EFTYPE = new Errno();
        ENEEDAUTH = new Errno();
        ENOATTR = new Errno();
        ENOTSUP = new Errno();
        EPROCLIM = new Errno();
        EPROCUNAVAIL = new Errno();
        EPROGMISMATCH = new Errno();
        EPROGUNAVAIL = new Errno();
        ERPCMISMATCH = new Errno();
        EIPSEC = new Errno();
        EHWPOISON = new Errno();
        ECAPMODE = new Errno();
        ENOTCAPABLE = new Errno();
        __UNKNOWN_CONSTANT__ = new Errno();
        Errno[] errnoArray = new Errno[149];
        errnoArray[0] = EPERM;
        errnoArray[1] = ENOENT;
        errnoArray[2] = ESRCH;
        errnoArray[3] = EINTR;
        errnoArray[4] = EIO;
        errnoArray[5] = ENXIO;
        errnoArray[6] = E2BIG;
        errnoArray[7] = ENOEXEC;
        errnoArray[8] = EBADF;
        errnoArray[9] = ECHILD;
        errnoArray[10] = EDEADLK;
        errnoArray[11] = ENOMEM;
        errnoArray[12] = EACCES;
        errnoArray[13] = EFAULT;
        errnoArray[14] = ENOTBLK;
        errnoArray[15] = EBUSY;
        errnoArray[16] = EEXIST;
        errnoArray[17] = EXDEV;
        errnoArray[18] = ENODEV;
        errnoArray[19] = ENOTDIR;
        errnoArray[20] = EISDIR;
        errnoArray[21] = EINVAL;
        errnoArray[22] = ENFILE;
        errnoArray[23] = EMFILE;
        errnoArray[24] = ENOTTY;
        errnoArray[25] = ETXTBSY;
        errnoArray[26] = EFBIG;
        errnoArray[27] = ENOSPC;
        errnoArray[28] = ESPIPE;
        errnoArray[29] = EROFS;
        errnoArray[30] = EMLINK;
        errnoArray[31] = EPIPE;
        errnoArray[32] = EDOM;
        errnoArray[33] = ERANGE;
        errnoArray[34] = EWOULDBLOCK;
        errnoArray[35] = EAGAIN;
        errnoArray[36] = EINPROGRESS;
        errnoArray[37] = EALREADY;
        errnoArray[38] = ENOTSOCK;
        errnoArray[39] = EDESTADDRREQ;
        errnoArray[40] = EMSGSIZE;
        errnoArray[41] = EPROTOTYPE;
        errnoArray[42] = ENOPROTOOPT;
        errnoArray[43] = EPROTONOSUPPORT;
        errnoArray[44] = ESOCKTNOSUPPORT;
        errnoArray[45] = EOPNOTSUPP;
        errnoArray[46] = EPFNOSUPPORT;
        errnoArray[47] = EAFNOSUPPORT;
        errnoArray[48] = EADDRINUSE;
        errnoArray[49] = EADDRNOTAVAIL;
        errnoArray[50] = ENETDOWN;
        errnoArray[51] = ENETUNREACH;
        errnoArray[52] = ENETRESET;
        errnoArray[53] = ECONNABORTED;
        errnoArray[54] = ECONNRESET;
        errnoArray[55] = ENOBUFS;
        errnoArray[56] = EISCONN;
        errnoArray[57] = ENOTCONN;
        errnoArray[58] = ESHUTDOWN;
        errnoArray[59] = ETOOMANYREFS;
        errnoArray[60] = ETIMEDOUT;
        errnoArray[61] = ECONNREFUSED;
        errnoArray[62] = ELOOP;
        errnoArray[63] = ENAMETOOLONG;
        errnoArray[64] = EHOSTDOWN;
        errnoArray[65] = EHOSTUNREACH;
        errnoArray[66] = ENOTEMPTY;
        errnoArray[67] = EUSERS;
        errnoArray[68] = EDQUOT;
        errnoArray[69] = ESTALE;
        errnoArray[70] = EREMOTE;
        errnoArray[71] = ENOLCK;
        errnoArray[72] = ENOSYS;
        errnoArray[73] = EOVERFLOW;
        errnoArray[74] = EIDRM;
        errnoArray[75] = ENOMSG;
        errnoArray[76] = EILSEQ;
        errnoArray[77] = EBADMSG;
        errnoArray[78] = EMULTIHOP;
        errnoArray[79] = ENODATA;
        errnoArray[80] = ENOLINK;
        errnoArray[81] = ENOSR;
        errnoArray[82] = ENOSTR;
        errnoArray[83] = EPROTO;
        errnoArray[84] = ETIME;
        errnoArray[85] = ECHRNG;
        errnoArray[86] = EL2NSYNC;
        errnoArray[87] = EL3HLT;
        errnoArray[88] = EL3RST;
        errnoArray[89] = ELNRNG;
        errnoArray[90] = EUNATCH;
        errnoArray[91] = ENOCSI;
        errnoArray[92] = EL2HLT;
        errnoArray[93] = EBADE;
        errnoArray[94] = EBADR;
        errnoArray[95] = EXFULL;
        errnoArray[96] = ENOANO;
        errnoArray[97] = EBADRQC;
        errnoArray[98] = EBADSLT;
        errnoArray[99] = EDEADLOCK;
        errnoArray[100] = EBFONT;
        errnoArray[101] = ENONET;
        errnoArray[102] = ENOPKG;
        errnoArray[103] = EADV;
        errnoArray[104] = ESRMNT;
        errnoArray[105] = ECOMM;
        errnoArray[106] = EDOTDOT;
        errnoArray[107] = ENOTUNIQ;
        errnoArray[108] = EBADFD;
        errnoArray[109] = EREMCHG;
        errnoArray[110] = ELIBACC;
        errnoArray[111] = ELIBBAD;
        errnoArray[112] = ELIBSCN;
        errnoArray[113] = ELIBMAX;
        errnoArray[114] = ELIBEXEC;
        errnoArray[115] = ERESTART;
        errnoArray[116] = ESTRPIPE;
        errnoArray[117] = EUCLEAN;
        errnoArray[118] = ENOTNAM;
        errnoArray[119] = ENAVAIL;
        errnoArray[120] = EISNAM;
        errnoArray[121] = EREMOTEIO;
        errnoArray[122] = ECANCELED;
        errnoArray[123] = EKEYEXPIRED;
        errnoArray[124] = EKEYREJECTED;
        errnoArray[125] = EKEYREVOKED;
        errnoArray[126] = EMEDIUMTYPE;
        errnoArray[127] = ENOKEY;
        errnoArray[128] = ENOMEDIUM;
        errnoArray[129] = ENOTRECOVERABLE;
        errnoArray[130] = EOWNERDEAD;
        errnoArray[131] = ERFKILL;
        errnoArray[132] = EAUTH;
        errnoArray[133] = EBADRPC;
        errnoArray[134] = EDOOFUS;
        errnoArray[135] = EFTYPE;
        errnoArray[136] = ENEEDAUTH;
        errnoArray[137] = ENOATTR;
        errnoArray[138] = ENOTSUP;
        errnoArray[139] = EPROCLIM;
        errnoArray[140] = EPROCUNAVAIL;
        errnoArray[141] = EPROGMISMATCH;
        errnoArray[142] = EPROGUNAVAIL;
        errnoArray[143] = ERPCMISMATCH;
        errnoArray[144] = EIPSEC;
        errnoArray[145] = EHWPOISON;
        errnoArray[146] = ECAPMODE;
        errnoArray[147] = ENOTCAPABLE;
        errnoArray[148] = __UNKNOWN_CONSTANT__;
        $VALUES = errnoArray;
        resolver = ConstantResolver.getResolver(Errno.class, 20000, 20999);
    }
}

