/*
 * Decompiled with CFR 0.152.
 */
package jnr.constants.platform;

import jnr.constants.Constant;
import jnr.constants.platform.ConstantResolver;

public final class LastError
extends Enum<LastError>
implements Constant {
    public static final /* enum */ LastError ERROR_INVALID_FUNCTION = new LastError();
    public static final /* enum */ LastError WSASYSCALLFAILURE;
    public static final /* enum */ LastError ERROR_NOT_ENOUGH_QUOTA;
    public static final /* enum */ LastError WSAENOTCONN;
    public static final /* enum */ LastError WSAESOCKTNOSUPPORT;
    public static final /* enum */ LastError ERROR_NO_DATA;
    public static final /* enum */ LastError WSAEPFNOSUPPORT;
    public static final /* enum */ LastError ERROR_BAD_NET_NAME;
    public static final /* enum */ LastError ERROR_BROKEN_PIPE;
    public static final /* enum */ LastError WSAEBADF;
    public static final /* enum */ LastError WSAEACCES;
    public static final /* enum */ LastError ERROR_FILE_EXISTS;
    public static final /* enum */ LastError ERROR_WRONG_DISK;
    public static final /* enum */ LastError ERROR_OUT_OF_PAPER;
    public static final /* enum */ LastError WSAEINPROGRESS;
    public static final /* enum */ LastError ERROR_ALREADY_EXISTS;
    public static final /* enum */ LastError WSAEAFNOSUPPORT;
    public static final /* enum */ LastError ERROR_DISK_FULL;
    public static final /* enum */ LastError ERROR_NOT_SAME_DEVICE;
    public static final /* enum */ LastError WSANO_DATA;
    public static final /* enum */ LastError ERROR_IOPL_NOT_ENABLED;
    public static final /* enum */ LastError ERROR_RING2SEG_MUST_BE_MOVABLE;
    public static final /* enum */ LastError WSAENOTEMPTY;
    public static final /* enum */ LastError WSAESHUTDOWN;
    public static final /* enum */ LastError ERROR_INVALID_TARGET_HANDLE;
    public static final /* enum */ LastError ERROR_NO_MORE_FILES;
    public static final /* enum */ LastError ERROR_LOCK_VIOLATION;
    public static final /* enum */ LastError WSAEUSERS;
    public static final /* enum */ LastError WSAETOOMANYREFS;
    public static final /* enum */ LastError WSAENETDOWN;
    public static final /* enum */ LastError WSAECONNREFUSED;
    public static final /* enum */ LastError ERROR_NOT_READY;
    public static final /* enum */ LastError ERROR_BAD_PIPE;
    public static final /* enum */ LastError WSAECONNRESET;
    public static final /* enum */ LastError WSA_E_NO_MORE;
    public static final /* enum */ LastError ERROR_INVALID_DATA;
    public static final /* enum */ LastError ERROR_PIPE_NOT_CONNECTED;
    public static final /* enum */ LastError ERROR_CANNOT_MAKE;
    public static final /* enum */ LastError ERROR_INVALID_DRIVE;
    public static final /* enum */ LastError ERROR_SEEK;
    public static final /* enum */ LastError ERROR_LOCK_FAILED;
    public static final /* enum */ LastError ERROR_EXE_MARKED_INVALID;
    public static final /* enum */ LastError ERROR_NESTING_NOT_ALLOWED;
    public static final /* enum */ LastError __UNKNOWN_CONSTANT__;
    public static final /* enum */ LastError ERROR_PATH_NOT_FOUND;
    public static final /* enum */ LastError ERROR_CURRENT_DIRECTORY;
    private static final /* synthetic */ LastError[] $VALUES;
    public static final /* enum */ LastError ERROR_NO_PROC_SLOTS;
    public static final /* enum */ LastError WSAHOST_NOT_FOUND;
    public static final /* enum */ LastError ERROR_BAD_EXE_FORMAT;
    public static final /* enum */ LastError WSAENETUNREACH;
    public static final /* enum */ LastError ERROR_INVALID_EXE_SIGNATURE;
    public static final /* enum */ LastError WSAEHOSTDOWN;
    public static final /* enum */ LastError ERROR_NETWORK_ACCESS_DENIED;
    public static final /* enum */ LastError ERROR_INVALID_MODULETYPE;
    public static final /* enum */ LastError WSATYPE_NOT_FOUND;
    public static final /* enum */ LastError WSAEPROTOTYPE;
    public static final /* enum */ LastError WSAETIMEDOUT;
    public static final /* enum */ LastError WSAESTALE;
    public static final /* enum */ LastError WSAEREMOTE;
    public static final /* enum */ LastError WSASYSNOTREADY;
    public static final /* enum */ LastError WSAENAMETOOLONG;
    public static final /* enum */ LastError ERROR_INVALID_PARAMETER;
    public static final /* enum */ LastError ERROR_NEGATIVE_SEEK;
    public static final /* enum */ LastError ERROR_ACCESS_DENIED;
    public static final /* enum */ LastError WSAEWOULDBLOCK;
    public static final /* enum */ LastError ERROR_ITERATED_DATA_EXCEEDS_64k;
    public static final /* enum */ LastError WSAECANCELLED;
    public static final /* enum */ LastError ERROR_NOT_DOS_DISK;
    public static final /* enum */ LastError ERROR_DIR_NOT_EMPTY;
    public static final /* enum */ LastError ERROR_PIPE_BUSY;
    public static final /* enum */ LastError WSAENOBUFS;
    public static final /* enum */ LastError ERROR_GEN_FAILURE;
    public static final /* enum */ LastError WSAEPROCLIM;
    public static final /* enum */ LastError ERROR_BAD_NETPATH;
    public static final /* enum */ LastError ERROR_NOT_ENOUGH_MEMORY;
    public static final /* enum */ LastError ERROR_INFLOOP_IN_RELOC_CHAIN;
    public static final /* enum */ LastError WSAELOOP;
    public static final /* enum */ LastError ERROR_AUTODATASEG_EXCEEDS_64k;
    public static final /* enum */ LastError ERROR_INVALID_SEGDPL;
    public static final /* enum */ LastError ERROR_SECTOR_NOT_FOUND;
    public static final /* enum */ LastError ERROR_OPERATION_ABORTED;
    public static final /* enum */ LastError WSAEREFUSED;
    public static final /* enum */ LastError ERROR_FAIL_I24;
    public static final /* enum */ LastError WSAEFAULT;
    public static final /* enum */ LastError WSAEPROVIDERFAILEDINIT;
    public static final /* enum */ LastError ERROR_BAD_FORMAT;
    public static final /* enum */ LastError WSAEADDRINUSE;
    public static final /* enum */ LastError ERROR_BAD_ENVIRONMENT;
    public static final /* enum */ LastError WSA_E_CANCELLED;
    public static final /* enum */ LastError WSAEADDRNOTAVAIL;
    public static final /* enum */ LastError ERROR_SEEK_ON_DEVICE;
    public static final /* enum */ LastError WSAEINTR;
    public static final /* enum */ LastError WSAEMFILE;
    public static final /* enum */ LastError WSAEHOSTUNREACH;
    public static final /* enum */ LastError ERROR_WRITE_FAULT;
    public static final /* enum */ LastError ERROR_MOD_NOT_FOUND;
    public static final /* enum */ LastError WSAVERNOTSUPPORTED;
    public static final /* enum */ LastError ERROR_CHILD_NOT_COMPLETE;
    public static final /* enum */ LastError WSAEINVALIDPROVIDER;
    public static final /* enum */ LastError WSAECONNABORTED;
    public static final /* enum */ LastError WSAENOTSOCK;
    public static final /* enum */ LastError ERROR_NOT_LOCKED;
    public static final /* enum */ LastError ERROR_WAIT_NO_CHILDREN;
    public static final /* enum */ LastError ERROR_MAX_THRDS_REACHED;
    public static final /* enum */ LastError ERROR_INVALID_MINALLOCSIZE;
    private static final ConstantResolver<LastError> resolver;
    public static final /* enum */ LastError ERROR_FILE_NOT_FOUND;
    public static final /* enum */ LastError WSANO_RECOVERY;
    public static final /* enum */ LastError ERROR_BAD_UNIT;
    public static final /* enum */ LastError ERROR_BAD_PATHNAME;
    public static final /* enum */ LastError WSAEINVAL;
    public static final /* enum */ LastError ERROR_ARENA_TRASHED;
    public static final /* enum */ LastError ERROR_PIPE_LOCAL;
    public static final /* enum */ LastError ERROR_DIRECTORY;
    public static final /* enum */ LastError ERROR_INVALID_STARTING_CODESEG;
    public static final /* enum */ LastError ERROR_WRITE_PROTECT;
    public static final /* enum */ LastError ERROR_INVALID_STACKSEG;
    public static final /* enum */ LastError ERROR_INVALID_BLOCK;
    public static final /* enum */ LastError WSAEINVALIDPROCTABLE;
    public static final /* enum */ LastError WSAEOPNOTSUPP;
    public static final /* enum */ LastError ERROR_CRC;
    public static final /* enum */ LastError ERROR_DIRECT_ACCESS_HANDLE;
    public static final /* enum */ LastError ERROR_DRIVE_LOCKED;
    public static final /* enum */ LastError ERROR_BAD_COMMAND;
    public static final /* enum */ LastError WSAENOPROTOOPT;
    public static final /* enum */ LastError ERROR_INVALID_ACCESS;
    public static final /* enum */ LastError WSAENOMORE;
    public static final /* enum */ LastError WSAENETRESET;
    public static final /* enum */ LastError ERROR_TOO_MANY_OPEN_FILES;
    public static final /* enum */ LastError WSAEPROTONOSUPPORT;
    public static final /* enum */ LastError WSAEISCONN;
    public static final /* enum */ LastError ERROR_INVALID_HANDLE;
    public static final /* enum */ LastError WSATRY_AGAIN;
    public static final /* enum */ LastError ERROR_SHARING_BUFFER_EXCEEDED;
    public static final /* enum */ LastError ERROR_READ_FAULT;
    public static final /* enum */ LastError WSAEMSGSIZE;
    public static final /* enum */ LastError ERROR_DYNLINK_FROM_INVALID_RING;
    public static final /* enum */ LastError ERROR_SHARING_VIOLATION;
    public static final /* enum */ LastError WSASERVICE_NOT_FOUND;
    public static final /* enum */ LastError ERROR_FILENAME_EXCED_RANGE;
    public static final /* enum */ LastError WSAEDISCON;
    public static final /* enum */ LastError WSAEDESTADDRREQ;
    public static final /* enum */ LastError WSAEDQUOT;
    public static final /* enum */ LastError ERROR_BAD_LENGTH;
    public static final /* enum */ LastError ERROR_RELOC_CHAIN_XEEDS_SEGLIM;
    public static final /* enum */ LastError WSANOTINITIALISED;
    public static final /* enum */ LastError WSAEALREADY;

    @Override
    public final int intValue() {
        return (int)resolver.longValue(this);
    }

    public static LastError valueOf(long value) {
        return resolver.valueOf(value);
    }

    @Override
    public final long longValue() {
        return resolver.longValue(this);
    }

    @Override
    public final boolean defined() {
        return resolver.defined(this);
    }

    public final String toString() {
        return this.description();
    }

    public static LastError valueOf(String name) {
        return Enum.valueOf(LastError.class, name);
    }

    public final String description() {
        return resolver.description(this);
    }

    static {
        ERROR_FILE_NOT_FOUND = new LastError();
        ERROR_PATH_NOT_FOUND = new LastError();
        ERROR_TOO_MANY_OPEN_FILES = new LastError();
        ERROR_ACCESS_DENIED = new LastError();
        ERROR_INVALID_HANDLE = new LastError();
        ERROR_ARENA_TRASHED = new LastError();
        ERROR_NOT_ENOUGH_MEMORY = new LastError();
        ERROR_INVALID_BLOCK = new LastError();
        ERROR_BAD_ENVIRONMENT = new LastError();
        ERROR_BAD_FORMAT = new LastError();
        ERROR_INVALID_ACCESS = new LastError();
        ERROR_INVALID_DATA = new LastError();
        ERROR_INVALID_DRIVE = new LastError();
        ERROR_CURRENT_DIRECTORY = new LastError();
        ERROR_NOT_SAME_DEVICE = new LastError();
        ERROR_NO_MORE_FILES = new LastError();
        ERROR_WRITE_PROTECT = new LastError();
        ERROR_BAD_UNIT = new LastError();
        ERROR_NOT_READY = new LastError();
        ERROR_BAD_COMMAND = new LastError();
        ERROR_CRC = new LastError();
        ERROR_BAD_LENGTH = new LastError();
        ERROR_SEEK = new LastError();
        ERROR_NOT_DOS_DISK = new LastError();
        ERROR_SECTOR_NOT_FOUND = new LastError();
        ERROR_OUT_OF_PAPER = new LastError();
        ERROR_WRITE_FAULT = new LastError();
        ERROR_READ_FAULT = new LastError();
        ERROR_GEN_FAILURE = new LastError();
        ERROR_LOCK_VIOLATION = new LastError();
        ERROR_SHARING_VIOLATION = new LastError();
        ERROR_WRONG_DISK = new LastError();
        ERROR_SHARING_BUFFER_EXCEEDED = new LastError();
        ERROR_BAD_NETPATH = new LastError();
        ERROR_NETWORK_ACCESS_DENIED = new LastError();
        ERROR_BAD_NET_NAME = new LastError();
        ERROR_FILE_EXISTS = new LastError();
        ERROR_CANNOT_MAKE = new LastError();
        ERROR_FAIL_I24 = new LastError();
        ERROR_INVALID_PARAMETER = new LastError();
        ERROR_NO_PROC_SLOTS = new LastError();
        ERROR_DRIVE_LOCKED = new LastError();
        ERROR_BROKEN_PIPE = new LastError();
        ERROR_DISK_FULL = new LastError();
        ERROR_INVALID_TARGET_HANDLE = new LastError();
        ERROR_WAIT_NO_CHILDREN = new LastError();
        ERROR_CHILD_NOT_COMPLETE = new LastError();
        ERROR_DIRECT_ACCESS_HANDLE = new LastError();
        ERROR_NEGATIVE_SEEK = new LastError();
        ERROR_SEEK_ON_DEVICE = new LastError();
        ERROR_DIR_NOT_EMPTY = new LastError();
        ERROR_DIRECTORY = new LastError();
        ERROR_NOT_LOCKED = new LastError();
        ERROR_BAD_PATHNAME = new LastError();
        ERROR_MAX_THRDS_REACHED = new LastError();
        ERROR_LOCK_FAILED = new LastError();
        ERROR_ALREADY_EXISTS = new LastError();
        ERROR_INVALID_STARTING_CODESEG = new LastError();
        ERROR_INVALID_STACKSEG = new LastError();
        ERROR_INVALID_MODULETYPE = new LastError();
        ERROR_INVALID_EXE_SIGNATURE = new LastError();
        ERROR_EXE_MARKED_INVALID = new LastError();
        ERROR_BAD_EXE_FORMAT = new LastError();
        ERROR_ITERATED_DATA_EXCEEDS_64k = new LastError();
        ERROR_INVALID_MINALLOCSIZE = new LastError();
        ERROR_DYNLINK_FROM_INVALID_RING = new LastError();
        ERROR_IOPL_NOT_ENABLED = new LastError();
        ERROR_INVALID_SEGDPL = new LastError();
        ERROR_AUTODATASEG_EXCEEDS_64k = new LastError();
        ERROR_RING2SEG_MUST_BE_MOVABLE = new LastError();
        ERROR_RELOC_CHAIN_XEEDS_SEGLIM = new LastError();
        ERROR_INFLOOP_IN_RELOC_CHAIN = new LastError();
        ERROR_FILENAME_EXCED_RANGE = new LastError();
        ERROR_NESTING_NOT_ALLOWED = new LastError();
        ERROR_PIPE_LOCAL = new LastError();
        ERROR_BAD_PIPE = new LastError();
        ERROR_PIPE_BUSY = new LastError();
        ERROR_NO_DATA = new LastError();
        ERROR_PIPE_NOT_CONNECTED = new LastError();
        ERROR_OPERATION_ABORTED = new LastError();
        ERROR_NOT_ENOUGH_QUOTA = new LastError();
        ERROR_MOD_NOT_FOUND = new LastError();
        WSAEINTR = new LastError();
        WSAEBADF = new LastError();
        WSAEACCES = new LastError();
        WSAEFAULT = new LastError();
        WSAEINVAL = new LastError();
        WSAEMFILE = new LastError();
        WSAEWOULDBLOCK = new LastError();
        WSAEINPROGRESS = new LastError();
        WSAEALREADY = new LastError();
        WSAENOTSOCK = new LastError();
        WSAEDESTADDRREQ = new LastError();
        WSAEMSGSIZE = new LastError();
        WSAEPROTOTYPE = new LastError();
        WSAENOPROTOOPT = new LastError();
        WSAEPROTONOSUPPORT = new LastError();
        WSAESOCKTNOSUPPORT = new LastError();
        WSAEOPNOTSUPP = new LastError();
        WSAEPFNOSUPPORT = new LastError();
        WSAEAFNOSUPPORT = new LastError();
        WSAEADDRINUSE = new LastError();
        WSAEADDRNOTAVAIL = new LastError();
        WSAENETDOWN = new LastError();
        WSAENETUNREACH = new LastError();
        WSAENETRESET = new LastError();
        WSAECONNABORTED = new LastError();
        WSAECONNRESET = new LastError();
        WSAENOBUFS = new LastError();
        WSAEISCONN = new LastError();
        WSAENOTCONN = new LastError();
        WSAESHUTDOWN = new LastError();
        WSAETOOMANYREFS = new LastError();
        WSAETIMEDOUT = new LastError();
        WSAECONNREFUSED = new LastError();
        WSAELOOP = new LastError();
        WSAENAMETOOLONG = new LastError();
        WSAEHOSTDOWN = new LastError();
        WSAEHOSTUNREACH = new LastError();
        WSAENOTEMPTY = new LastError();
        WSAEPROCLIM = new LastError();
        WSAEUSERS = new LastError();
        WSAEDQUOT = new LastError();
        WSAESTALE = new LastError();
        WSAEREMOTE = new LastError();
        WSASYSNOTREADY = new LastError();
        WSAVERNOTSUPPORTED = new LastError();
        WSANOTINITIALISED = new LastError();
        WSAEDISCON = new LastError();
        WSAENOMORE = new LastError();
        WSAECANCELLED = new LastError();
        WSAEINVALIDPROCTABLE = new LastError();
        WSAEINVALIDPROVIDER = new LastError();
        WSAEPROVIDERFAILEDINIT = new LastError();
        WSASYSCALLFAILURE = new LastError();
        WSASERVICE_NOT_FOUND = new LastError();
        WSATYPE_NOT_FOUND = new LastError();
        WSA_E_NO_MORE = new LastError();
        WSA_E_CANCELLED = new LastError();
        WSAEREFUSED = new LastError();
        WSAHOST_NOT_FOUND = new LastError();
        WSATRY_AGAIN = new LastError();
        WSANO_RECOVERY = new LastError();
        WSANO_DATA = new LastError();
        __UNKNOWN_CONSTANT__ = new LastError();
        LastError[] lastErrorArray = new LastError[146];
        lastErrorArray[0] = ERROR_INVALID_FUNCTION;
        lastErrorArray[1] = ERROR_FILE_NOT_FOUND;
        lastErrorArray[2] = ERROR_PATH_NOT_FOUND;
        lastErrorArray[3] = ERROR_TOO_MANY_OPEN_FILES;
        lastErrorArray[4] = ERROR_ACCESS_DENIED;
        lastErrorArray[5] = ERROR_INVALID_HANDLE;
        lastErrorArray[6] = ERROR_ARENA_TRASHED;
        lastErrorArray[7] = ERROR_NOT_ENOUGH_MEMORY;
        lastErrorArray[8] = ERROR_INVALID_BLOCK;
        lastErrorArray[9] = ERROR_BAD_ENVIRONMENT;
        lastErrorArray[10] = ERROR_BAD_FORMAT;
        lastErrorArray[11] = ERROR_INVALID_ACCESS;
        lastErrorArray[12] = ERROR_INVALID_DATA;
        lastErrorArray[13] = ERROR_INVALID_DRIVE;
        lastErrorArray[14] = ERROR_CURRENT_DIRECTORY;
        lastErrorArray[15] = ERROR_NOT_SAME_DEVICE;
        lastErrorArray[16] = ERROR_NO_MORE_FILES;
        lastErrorArray[17] = ERROR_WRITE_PROTECT;
        lastErrorArray[18] = ERROR_BAD_UNIT;
        lastErrorArray[19] = ERROR_NOT_READY;
        lastErrorArray[20] = ERROR_BAD_COMMAND;
        lastErrorArray[21] = ERROR_CRC;
        lastErrorArray[22] = ERROR_BAD_LENGTH;
        lastErrorArray[23] = ERROR_SEEK;
        lastErrorArray[24] = ERROR_NOT_DOS_DISK;
        lastErrorArray[25] = ERROR_SECTOR_NOT_FOUND;
        lastErrorArray[26] = ERROR_OUT_OF_PAPER;
        lastErrorArray[27] = ERROR_WRITE_FAULT;
        lastErrorArray[28] = ERROR_READ_FAULT;
        lastErrorArray[29] = ERROR_GEN_FAILURE;
        lastErrorArray[30] = ERROR_LOCK_VIOLATION;
        lastErrorArray[31] = ERROR_SHARING_VIOLATION;
        lastErrorArray[32] = ERROR_WRONG_DISK;
        lastErrorArray[33] = ERROR_SHARING_BUFFER_EXCEEDED;
        lastErrorArray[34] = ERROR_BAD_NETPATH;
        lastErrorArray[35] = ERROR_NETWORK_ACCESS_DENIED;
        lastErrorArray[36] = ERROR_BAD_NET_NAME;
        lastErrorArray[37] = ERROR_FILE_EXISTS;
        lastErrorArray[38] = ERROR_CANNOT_MAKE;
        lastErrorArray[39] = ERROR_FAIL_I24;
        lastErrorArray[40] = ERROR_INVALID_PARAMETER;
        lastErrorArray[41] = ERROR_NO_PROC_SLOTS;
        lastErrorArray[42] = ERROR_DRIVE_LOCKED;
        lastErrorArray[43] = ERROR_BROKEN_PIPE;
        lastErrorArray[44] = ERROR_DISK_FULL;
        lastErrorArray[45] = ERROR_INVALID_TARGET_HANDLE;
        lastErrorArray[46] = ERROR_WAIT_NO_CHILDREN;
        lastErrorArray[47] = ERROR_CHILD_NOT_COMPLETE;
        lastErrorArray[48] = ERROR_DIRECT_ACCESS_HANDLE;
        lastErrorArray[49] = ERROR_NEGATIVE_SEEK;
        lastErrorArray[50] = ERROR_SEEK_ON_DEVICE;
        lastErrorArray[51] = ERROR_DIR_NOT_EMPTY;
        lastErrorArray[52] = ERROR_DIRECTORY;
        lastErrorArray[53] = ERROR_NOT_LOCKED;
        lastErrorArray[54] = ERROR_BAD_PATHNAME;
        lastErrorArray[55] = ERROR_MAX_THRDS_REACHED;
        lastErrorArray[56] = ERROR_LOCK_FAILED;
        lastErrorArray[57] = ERROR_ALREADY_EXISTS;
        lastErrorArray[58] = ERROR_INVALID_STARTING_CODESEG;
        lastErrorArray[59] = ERROR_INVALID_STACKSEG;
        lastErrorArray[60] = ERROR_INVALID_MODULETYPE;
        lastErrorArray[61] = ERROR_INVALID_EXE_SIGNATURE;
        lastErrorArray[62] = ERROR_EXE_MARKED_INVALID;
        lastErrorArray[63] = ERROR_BAD_EXE_FORMAT;
        lastErrorArray[64] = ERROR_ITERATED_DATA_EXCEEDS_64k;
        lastErrorArray[65] = ERROR_INVALID_MINALLOCSIZE;
        lastErrorArray[66] = ERROR_DYNLINK_FROM_INVALID_RING;
        lastErrorArray[67] = ERROR_IOPL_NOT_ENABLED;
        lastErrorArray[68] = ERROR_INVALID_SEGDPL;
        lastErrorArray[69] = ERROR_AUTODATASEG_EXCEEDS_64k;
        lastErrorArray[70] = ERROR_RING2SEG_MUST_BE_MOVABLE;
        lastErrorArray[71] = ERROR_RELOC_CHAIN_XEEDS_SEGLIM;
        lastErrorArray[72] = ERROR_INFLOOP_IN_RELOC_CHAIN;
        lastErrorArray[73] = ERROR_FILENAME_EXCED_RANGE;
        lastErrorArray[74] = ERROR_NESTING_NOT_ALLOWED;
        lastErrorArray[75] = ERROR_PIPE_LOCAL;
        lastErrorArray[76] = ERROR_BAD_PIPE;
        lastErrorArray[77] = ERROR_PIPE_BUSY;
        lastErrorArray[78] = ERROR_NO_DATA;
        lastErrorArray[79] = ERROR_PIPE_NOT_CONNECTED;
        lastErrorArray[80] = ERROR_OPERATION_ABORTED;
        lastErrorArray[81] = ERROR_NOT_ENOUGH_QUOTA;
        lastErrorArray[82] = ERROR_MOD_NOT_FOUND;
        lastErrorArray[83] = WSAEINTR;
        lastErrorArray[84] = WSAEBADF;
        lastErrorArray[85] = WSAEACCES;
        lastErrorArray[86] = WSAEFAULT;
        lastErrorArray[87] = WSAEINVAL;
        lastErrorArray[88] = WSAEMFILE;
        lastErrorArray[89] = WSAEWOULDBLOCK;
        lastErrorArray[90] = WSAEINPROGRESS;
        lastErrorArray[91] = WSAEALREADY;
        lastErrorArray[92] = WSAENOTSOCK;
        lastErrorArray[93] = WSAEDESTADDRREQ;
        lastErrorArray[94] = WSAEMSGSIZE;
        lastErrorArray[95] = WSAEPROTOTYPE;
        lastErrorArray[96] = WSAENOPROTOOPT;
        lastErrorArray[97] = WSAEPROTONOSUPPORT;
        lastErrorArray[98] = WSAESOCKTNOSUPPORT;
        lastErrorArray[99] = WSAEOPNOTSUPP;
        lastErrorArray[100] = WSAEPFNOSUPPORT;
        lastErrorArray[101] = WSAEAFNOSUPPORT;
        lastErrorArray[102] = WSAEADDRINUSE;
        lastErrorArray[103] = WSAEADDRNOTAVAIL;
        lastErrorArray[104] = WSAENETDOWN;
        lastErrorArray[105] = WSAENETUNREACH;
        lastErrorArray[106] = WSAENETRESET;
        lastErrorArray[107] = WSAECONNABORTED;
        lastErrorArray[108] = WSAECONNRESET;
        lastErrorArray[109] = WSAENOBUFS;
        lastErrorArray[110] = WSAEISCONN;
        lastErrorArray[111] = WSAENOTCONN;
        lastErrorArray[112] = WSAESHUTDOWN;
        lastErrorArray[113] = WSAETOOMANYREFS;
        lastErrorArray[114] = WSAETIMEDOUT;
        lastErrorArray[115] = WSAECONNREFUSED;
        lastErrorArray[116] = WSAELOOP;
        lastErrorArray[117] = WSAENAMETOOLONG;
        lastErrorArray[118] = WSAEHOSTDOWN;
        lastErrorArray[119] = WSAEHOSTUNREACH;
        lastErrorArray[120] = WSAENOTEMPTY;
        lastErrorArray[121] = WSAEPROCLIM;
        lastErrorArray[122] = WSAEUSERS;
        lastErrorArray[123] = WSAEDQUOT;
        lastErrorArray[124] = WSAESTALE;
        lastErrorArray[125] = WSAEREMOTE;
        lastErrorArray[126] = WSASYSNOTREADY;
        lastErrorArray[127] = WSAVERNOTSUPPORTED;
        lastErrorArray[128] = WSANOTINITIALISED;
        lastErrorArray[129] = WSAEDISCON;
        lastErrorArray[130] = WSAENOMORE;
        lastErrorArray[131] = WSAECANCELLED;
        lastErrorArray[132] = WSAEINVALIDPROCTABLE;
        lastErrorArray[133] = WSAEINVALIDPROVIDER;
        lastErrorArray[134] = WSAEPROVIDERFAILEDINIT;
        lastErrorArray[135] = WSASYSCALLFAILURE;
        lastErrorArray[136] = WSASERVICE_NOT_FOUND;
        lastErrorArray[137] = WSATYPE_NOT_FOUND;
        lastErrorArray[138] = WSA_E_NO_MORE;
        lastErrorArray[139] = WSA_E_CANCELLED;
        lastErrorArray[140] = WSAEREFUSED;
        lastErrorArray[141] = WSAHOST_NOT_FOUND;
        lastErrorArray[142] = WSATRY_AGAIN;
        lastErrorArray[143] = WSANO_RECOVERY;
        lastErrorArray[144] = WSANO_DATA;
        lastErrorArray[145] = __UNKNOWN_CONSTANT__;
        $VALUES = lastErrorArray;
        resolver = ConstantResolver.getResolver(LastError.class, 20000, 20999);
    }

    public final int value() {
        return (int)resolver.longValue(this);
    }

    public static LastError[] values() {
        return (LastError[])$VALUES.clone();
    }
}

