plugins {
    id 'fabric-loom' version '1.14.10'
    id 'maven-publish'
}

version = '1.21.8'
group = 'ru.metaculture'

base {
    archivesName = 'wild'
}

repositories {
    maven { url 'https://maven.fabricmc.net/' }
    mavenCentral()
}

loom {
    splitEnvironmentSourceSets()
}

dependencies {
    minecraft 'com.mojang:minecraft:1.21.8'
    mappings 'net.fabricmc:intermediary:1.21.8:v2'
    modImplementation 'net.fabricmc:fabric-loader:0.18.6'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.134.0+1.21.8'
    implementation fileTree(dir: 'META-INF/jars', include: ['*.jar'])
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

tasks.withType(JavaCompile).configureEach {
    enabled = false
}
tasks.named("processResources") { enabled = false }
