/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  baritone.utils.accessor.IRenderPipelines
 *  com.mojang.blaze3d.pipeline.BlendFunction
 *  com.mojang.blaze3d.pipeline.RenderPipeline
 *  com.mojang.blaze3d.pipeline.RenderPipeline$Snippet
 *  com.mojang.blaze3d.platform.DepthTestFunction
 *  com.mojang.blaze3d.platform.DestFactor
 *  com.mojang.blaze3d.platform.PolygonMode
 *  com.mojang.blaze3d.platform.SourceFactor
 *  com.mojang.blaze3d.textures.TextureFormat
 *  com.mojang.blaze3d.vertex.VertexFormat$class_5596
 *  minecraft.class01894
 *  minecraft.class07835
 */
package minecraft;

import baritone.utils.accessor.IRenderPipelines;
import com.mojang.blaze3d.pipeline.BlendFunction;
import com.mojang.blaze3d.pipeline.RenderPipeline;
import com.mojang.blaze3d.platform.DepthTestFunction;
import com.mojang.blaze3d.platform.DestFactor;
import com.mojang.blaze3d.platform.PolygonMode;
import com.mojang.blaze3d.platform.SourceFactor;
import com.mojang.blaze3d.textures.TextureFormat;
import com.mojang.blaze3d.vertex.VertexFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import minecraft.class01894;
import minecraft.class07835;
import minecraft.class08419;

public class class08394
implements IRenderPipelines {
    private static final Map<class01894, RenderPipeline> yB = new HashMap<class01894, RenderPipeline>();
    public static final RenderPipeline.Snippet N = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withUniform("DynamicTransforms", class08419.field_60031).withUniform("Projection", class08419.field_60031).buildSnippet();
    public static final RenderPipeline.Snippet y = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withUniform("Fog", class08419.field_60031).buildSnippet();
    public static final RenderPipeline.Snippet L = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withUniform("Globals", class08419.field_60031).buildSnippet();
    public static final RenderPipeline.Snippet u = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N, y}).buildSnippet();
    public static final RenderPipeline.Snippet i = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N, y}).withUniform("Lighting", class08419.field_60031).buildSnippet();
    public static final RenderPipeline.Snippet R = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{y}).withSampler("Sampler0").withSampler("Sampler2").withVertexFormat(class07835.y, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet M = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{R}).withUniform("Projection", class08419.field_60031).withUniform("ChunkSection", class08419.field_60031).withVertexShader("core/terrain").withFragmentShader("core/terrain").buildSnippet();
    public static final RenderPipeline.Snippet B = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{R, N}).withVertexShader("core/block").withFragmentShader("core/block").buildSnippet();
    public static final RenderPipeline.Snippet Z = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{i}).withVertexShader("core/entity").withFragmentShader("core/entity").withSampler("Sampler0").withSampler("Sampler2").withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet z = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{i}).withVertexShader("core/entity").withFragmentShader("core/entity").withSampler("Sampler0").withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).withShaderDefine("EMISSIVE").buildSnippet();
    public static final RenderPipeline.Snippet U = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withVertexShader("core/rendertype_beacon_beam").withFragmentShader("core/rendertype_beacon_beam").withSampler("Sampler0").withVertexFormat(class07835.y, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet E = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withBlend(BlendFunction.TRANSLUCENT).withVertexFormat(class07835.U, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet W = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N, y, L}).withVertexShader("core/rendertype_end_portal").withFragmentShader("core/rendertype_end_portal").withSampler("Sampler0").withSampler("Sampler1").withVertexFormat(class07835.i, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet m = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withVertexShader("core/rendertype_clouds").withFragmentShader("core/rendertype_clouds").withBlend(BlendFunction.TRANSLUCENT).withVertexFormat(class07835.N, VertexFormat.class_5596.field_27382).withUniform("CloudInfo", class08419.field_60031).withUniform("CloudFaces", class08419.field_60032, TextureFormat.RED8I).buildSnippet();
    public static final RenderPipeline.Snippet P = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u, L}).withVertexShader("core/rendertype_lines").withFragmentShader("core/rendertype_lines").withBlend(BlendFunction.TRANSLUCENT).withCull(false).withVertexFormat(class07835.P, VertexFormat.class_5596.field_27377).buildSnippet();
    public static final RenderPipeline.Snippet s = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withVertexShader("core/position_color").withFragmentShader("core/position_color").withBlend(BlendFunction.TRANSLUCENT).withDepthWrite(false).withVertexFormat(class07835.R, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet T = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withVertexShader("core/particle").withFragmentShader("core/particle").withSampler("Sampler0").withSampler("Sampler2").withVertexFormat(class07835.u, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet b = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{T}).withBlend(BlendFunction.TRANSLUCENT).withCull(false).buildSnippet();
    public static final RenderPipeline.Snippet j = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withVertexShader("core/gui").withFragmentShader("core/gui").withBlend(BlendFunction.TRANSLUCENT).withVertexFormat(class07835.R, VertexFormat.class_5596.field_27382).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).buildSnippet();
    public static final RenderPipeline.Snippet v = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withVertexShader("core/position_tex_color").withFragmentShader("core/position_tex_color").withSampler("Sampler0").withBlend(BlendFunction.TRANSLUCENT).withVertexFormat(class07835.z, VertexFormat.class_5596.field_27382).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).buildSnippet();
    public static final RenderPipeline.Snippet n = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E}).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).buildSnippet();
    public static final RenderPipeline.Snippet t = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withVertexShader("core/rendertype_outline").withFragmentShader("core/rendertype_outline").withSampler("Sampler0").withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).withDepthWrite(false).withVertexFormat(class07835.z, VertexFormat.class_5596.field_27382).buildSnippet();
    public static final RenderPipeline.Snippet G = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).withDepthWrite(false).withVertexFormat(class07835.N, VertexFormat.class_5596.field_27379).buildSnippet();
    public static final RenderPipeline l = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{B}).withLocation("pipeline/solid_block").build());
    public static final RenderPipeline d = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{M}).withLocation("pipeline/solid_terrain").build());
    public static final RenderPipeline w = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{M}).withLocation("pipeline/wireframe").withPolygonMode(PolygonMode.WIREFRAME).build());
    public static final RenderPipeline k = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{B}).withLocation("pipeline/cutout_block").withShaderDefine("ALPHA_CUTOUT", 0.5f).build());
    public static final RenderPipeline Y = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{M}).withLocation("pipeline/cutout_terrain").withShaderDefine("ALPHA_CUTOUT", 0.5f).build());
    public static final RenderPipeline Q = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{M}).withLocation("pipeline/translucent_terrain").withBlend(BlendFunction.TRANSLUCENT).withShaderDefine("ALPHA_CUTOUT", 0.01f).build());
    public static final RenderPipeline O = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{B}).withLocation("pipeline/tripwire_block").withShaderDefine("ALPHA_CUTOUT", 0.1f).withBlend(BlendFunction.TRANSLUCENT).build());
    public static final RenderPipeline g = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{M}).withLocation("pipeline/tripwire_terrain").withShaderDefine("ALPHA_CUTOUT", 0.1f).withBlend(BlendFunction.TRANSLUCENT).build());
    public static final RenderPipeline I = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/translucent_moving_block").withVertexShader("core/rendertype_translucent_moving_block").withFragmentShader("core/rendertype_translucent_moving_block").withSampler("Sampler0").withSampler("Sampler2").withBlend(BlendFunction.TRANSLUCENT).withVertexFormat(class07835.y, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline J = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/armor_cutout_no_cull").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("NO_OVERLAY").withShaderDefine("PER_FACE_LIGHTING").withCull(false).build());
    public static final RenderPipeline o = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/armor_decal_cutout_no_cull").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("NO_OVERLAY").withShaderDefine("PER_FACE_LIGHTING").withCull(false).withDepthTestFunction(DepthTestFunction.EQUAL_DEPTH_TEST).build());
    public static final RenderPipeline q = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/armor_translucent").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("NO_OVERLAY").withShaderDefine("PER_FACE_LIGHTING").withBlend(BlendFunction.TRANSLUCENT).withCull(false).build());
    public static final RenderPipeline K = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_solid").withSampler("Sampler1").build());
    public static final RenderPipeline V = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_solid_offset_forward").withSampler("Sampler1").build());
    public static final RenderPipeline e = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_cutout").withShaderDefine("ALPHA_CUTOUT", 0.1f).withSampler("Sampler1").build());
    public static final RenderPipeline H = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_cutout_no_cull").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("PER_FACE_LIGHTING").withSampler("Sampler1").withCull(false).build());
    public static final RenderPipeline c = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_cutout_no_cull_z_offset").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("PER_FACE_LIGHTING").withSampler("Sampler1").withCull(false).build());
    public static final RenderPipeline X = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_translucent").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("PER_FACE_LIGHTING").withSampler("Sampler1").withBlend(BlendFunction.TRANSLUCENT).withCull(false).build());
    public static final RenderPipeline a = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{z}).withLocation("pipeline/entity_translucent_emissive").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("PER_FACE_LIGHTING").withSampler("Sampler1").withBlend(BlendFunction.TRANSLUCENT).withCull(false).withDepthWrite(false).build());
    public static final RenderPipeline p = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_smooth_cutout").withShaderDefine("ALPHA_CUTOUT", 0.1f).withSampler("Sampler1").withCull(false).build());
    public static final RenderPipeline F = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/entity_no_outline").withShaderDefine("NO_OVERLAY").withShaderDefine("PER_FACE_LIGHTING").withBlend(BlendFunction.TRANSLUCENT).withCull(false).withDepthWrite(false).build());
    public static final RenderPipeline A = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{Z}).withLocation("pipeline/breeze_wind").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("APPLY_TEXTURE_MATRIX").withShaderDefine("NO_OVERLAY").withShaderDefine("NO_CARDINAL_LIGHTING").withBlend(BlendFunction.TRANSLUCENT).withCull(false).build());
    public static final RenderPipeline f = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/energy_swirl").withVertexShader("core/entity").withFragmentShader("core/entity").withShaderDefine("ALPHA_CUTOUT", 0.1f).withShaderDefine("EMISSIVE").withShaderDefine("NO_OVERLAY").withShaderDefine("NO_CARDINAL_LIGHTING").withShaderDefine("APPLY_TEXTURE_MATRIX").withSampler("Sampler0").withBlend(BlendFunction.ADDITIVE).withCull(false).withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline C = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/eyes").withVertexShader("core/entity").withFragmentShader("core/entity").withShaderDefine("EMISSIVE").withShaderDefine("NO_OVERLAY").withShaderDefine("NO_CARDINAL_LIGHTING").withSampler("Sampler0").withBlend(BlendFunction.TRANSLUCENT).withDepthWrite(false).withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline S = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{i}).withLocation("pipeline/entity_decal").withVertexShader("core/rendertype_entity_decal").withFragmentShader("core/rendertype_entity_decal").withSampler("Sampler0").withSampler("Sampler1").withSampler("Sampler2").withDepthTestFunction(DepthTestFunction.EQUAL_DEPTH_TEST).withCull(false).withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline x = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/entity_shadow").withVertexShader("core/rendertype_entity_shadow").withFragmentShader("core/rendertype_entity_shadow").withSampler("Sampler0").withBlend(BlendFunction.TRANSLUCENT).withDepthWrite(false).withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline D = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{i}).withLocation("pipeline/item_entity_translucent_cull").withVertexShader("core/rendertype_item_entity_translucent_cull").withFragmentShader("core/rendertype_item_entity_translucent_cull").withSampler("Sampler0").withSampler("Sampler2").withBlend(BlendFunction.TRANSLUCENT).withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline h = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{U}).withLocation("pipeline/beacon_beam_opaque").build());
    public static final RenderPipeline r = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{U}).withLocation("pipeline/beacon_beam_translucent").withDepthWrite(false).withBlend(BlendFunction.TRANSLUCENT).build());
    public static final RenderPipeline NN = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/dragon_explosion_alpha").withVertexShader("core/rendertype_entity_alpha").withFragmentShader("core/rendertype_entity_alpha").withSampler("Sampler0").withCull(false).withVertexFormat(class07835.L, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline Ny = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/leash").withVertexShader("core/rendertype_leash").withFragmentShader("core/rendertype_leash").withSampler("Sampler2").withCull(false).withVertexFormat(class07835.B, VertexFormat.class_5596.field_27380).build());
    public static final RenderPipeline NL = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/water_mask").withVertexShader("core/rendertype_water_mask").withFragmentShader("core/rendertype_water_mask").withColorWrite(false).withVertexFormat(class07835.i, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline Nu = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N, y, L}).withLocation("pipeline/glint").withVertexShader("core/glint").withFragmentShader("core/glint").withSampler("Sampler0").withDepthWrite(false).withCull(false).withDepthTestFunction(DepthTestFunction.EQUAL_DEPTH_TEST).withBlend(BlendFunction.GLINT).withVertexFormat(class07835.Z, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline Ni = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/crumbling").withVertexShader("core/rendertype_crumbling").withFragmentShader("core/rendertype_crumbling").withSampler("Sampler0").withBlend(new BlendFunction(SourceFactor.DST_COLOR, DestFactor.SRC_COLOR, SourceFactor.ONE, DestFactor.ZERO)).withDepthWrite(false).withVertexFormat(class07835.y, VertexFormat.class_5596.field_27382).withDepthBias(-1.0f, -10.0f).build());
    public static final RenderPipeline NR = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E, y}).withLocation("pipeline/text").withVertexShader("core/rendertype_text").withFragmentShader("core/rendertype_text").withSampler("Sampler0").withSampler("Sampler2").build());
    public static final RenderPipeline NM = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{n, y}).withLocation("pipeline/gui_text").withVertexShader("core/rendertype_text").withFragmentShader("core/rendertype_text").withSampler("Sampler0").withSampler("Sampler2").withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).build());
    public static final RenderPipeline NB = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E, y}).withLocation("pipeline/text_background").withVertexShader("core/rendertype_text_background").withFragmentShader("core/rendertype_text_background").withSampler("Sampler2").withVertexFormat(class07835.B, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline NZ = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E, y}).withLocation("pipeline/text_intensity").withVertexShader("core/rendertype_text_intensity").withFragmentShader("core/rendertype_text_intensity").withSampler("Sampler0").withSampler("Sampler2").withDepthBias(-1.0f, -10.0f).build());
    public static final RenderPipeline Nz = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{n, y}).withLocation("pipeline/gui_text_intensity").withVertexShader("core/rendertype_text_intensity").withFragmentShader("core/rendertype_text_intensity").withSampler("Sampler0").withSampler("Sampler2").build());
    public static final RenderPipeline NU = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E, y}).withLocation("pipeline/text_polygon_offset").withVertexShader("core/rendertype_text").withFragmentShader("core/rendertype_text").withSampler("Sampler0").withSampler("Sampler2").withDepthBias(-1.0f, -10.0f).build());
    public static final RenderPipeline NE = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E}).withLocation("pipeline/text_see_through").withVertexShader("core/rendertype_text_see_through").withFragmentShader("core/rendertype_text_see_through").withSampler("Sampler0").withDepthWrite(false).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).build());
    public static final RenderPipeline NW = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E}).withLocation("pipeline/text_background_see_through").withVertexShader("core/rendertype_text_background_see_through").withFragmentShader("core/rendertype_text_background_see_through").withDepthWrite(false).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).withVertexFormat(class07835.B, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline Nm = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{E}).withLocation("pipeline/text_intensity_see_through").withVertexShader("core/rendertype_text_intensity_see_through").withFragmentShader("core/rendertype_text_intensity_see_through").withSampler("Sampler0").withDepthWrite(false).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).build());
    public static final RenderPipeline NP = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/lightning").withVertexShader("core/rendertype_lightning").withFragmentShader("core/rendertype_lightning").withBlend(BlendFunction.LIGHTNING).withVertexFormat(class07835.R, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline Ns = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/dragon_rays").withVertexShader("core/rendertype_lightning").withFragmentShader("core/rendertype_lightning").withDepthWrite(false).withBlend(BlendFunction.LIGHTNING).withVertexFormat(class07835.R, VertexFormat.class_5596.field_27379).build());
    public static final RenderPipeline NT = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/dragon_rays_depth").withVertexShader("core/position").withFragmentShader("core/position").withColorWrite(false).withVertexFormat(class07835.i, VertexFormat.class_5596.field_27379).build());
    public static final RenderPipeline Nb = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{W}).withLocation("pipeline/end_portal").withShaderDefine("PORTAL_LAYERS", 15).build());
    public static final RenderPipeline Nj = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{W}).withLocation("pipeline/end_gateway").withShaderDefine("PORTAL_LAYERS", 16).build());
    public static final RenderPipeline Nv = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{m}).withLocation("pipeline/flat_clouds").withCull(false).build());
    public static final RenderPipeline Nn = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{m}).withLocation("pipeline/clouds").build());
    public static final RenderPipeline Nt = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{P}).withLocation("pipeline/lines").build());
    public static final RenderPipeline NG = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{P}).withDepthWrite(false).withLocation("pipeline/lines_translucent").build());
    public static final RenderPipeline Nl = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{P}).withLocation("pipeline/secondary_block_outline").withBlend(BlendFunction.TRANSLUCENT).withDepthWrite(false).build());
    public static final RenderPipeline Nd = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/debug_points").withVertexShader("core/debug_point").withFragmentShader("core/position_color").withCull(false).withVertexFormat(class07835.m, VertexFormat.class_5596.field_63316).build());
    public static final RenderPipeline Nw = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{s}).withLocation("pipeline/debug_filled_box").build());
    public static final RenderPipeline Nk = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{s}).withLocation("pipeline/debug_quads").withCull(false).build());
    public static final RenderPipeline NY = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{s}).withLocation("pipeline/debug_triangle_fan").withCull(false).withVertexFormat(class07835.R, VertexFormat.class_5596.field_27381).build());
    public static final RenderPipeline NQ = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/world_border").withVertexShader("core/rendertype_world_border").withFragmentShader("core/rendertype_world_border").withSampler("Sampler0").withBlend(BlendFunction.OVERLAY).withCull(false).withVertexFormat(class07835.Z, VertexFormat.class_5596.field_27382).withDepthBias(-3.0f, -3.0f).build());
    public static final RenderPipeline NO = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{T}).withLocation("pipeline/opaque_particle").build());
    public static final RenderPipeline Ng = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{T}).withLocation("pipeline/translucent_particle").withBlend(BlendFunction.TRANSLUCENT).build());
    public static final RenderPipeline NI = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{b}).withLocation("pipeline/weather_depth_write").build());
    public static final RenderPipeline NJ = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{b}).withLocation("pipeline/weather_no_depth_write").withDepthWrite(false).build());
    public static final RenderPipeline No = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{u}).withLocation("pipeline/sky").withVertexShader("core/sky").withFragmentShader("core/sky").withDepthWrite(false).withVertexFormat(class07835.i, VertexFormat.class_5596.field_27381).build());
    public static final RenderPipeline Nq = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/end_sky").withVertexShader("core/position_tex_color").withFragmentShader("core/position_tex_color").withSampler("Sampler0").withBlend(BlendFunction.TRANSLUCENT).withDepthWrite(false).withVertexFormat(class07835.z, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline NK = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/sunrise_sunset").withVertexShader("core/position_color").withFragmentShader("core/position_color").withBlend(BlendFunction.TRANSLUCENT).withDepthWrite(false).withVertexFormat(class07835.R, VertexFormat.class_5596.field_27381).build());
    public static final RenderPipeline NV = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/stars").withVertexShader("core/stars").withFragmentShader("core/stars").withBlend(BlendFunction.OVERLAY).withDepthWrite(false).withVertexFormat(class07835.i, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline Ne = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/celestial").withVertexShader("core/position_tex").withFragmentShader("core/position_tex").withSampler("Sampler0").withBlend(BlendFunction.OVERLAY).withDepthWrite(false).withVertexFormat(class07835.Z, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline NH = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{j}).withLocation("pipeline/gui").build());
    public static final RenderPipeline Nc = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{j}).withLocation("pipeline/gui_invert").withBlend(BlendFunction.INVERT).build());
    public static final RenderPipeline NX = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{j}).withLocation("pipeline/gui_text_highlight").withBlend(BlendFunction.ADDITIVE).build());
    public static final RenderPipeline Na = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/gui_textured").build());
    public static final RenderPipeline Np = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/gui_textured_premultiplied_alpha").withBlend(BlendFunction.TRANSLUCENT_PREMULTIPLIED_ALPHA).build());
    public static final RenderPipeline NF = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/block_screen_effect").withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).withDepthWrite(false).build());
    public static final RenderPipeline NA = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/fire_screen_effect").withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).withDepthWrite(false).build());
    public static final RenderPipeline Nf = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/gui_opaque_textured_background").withoutBlend().build());
    public static final RenderPipeline NC = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/gui_nausea_overlay").withBlend(BlendFunction.ADDITIVE).build());
    public static final RenderPipeline NS = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/vignette").withBlend(new BlendFunction(SourceFactor.ZERO, DestFactor.ONE_MINUS_SRC_COLOR)).build());
    public static final RenderPipeline Nx = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/crosshair").withBlend(BlendFunction.INVERT).build());
    public static final RenderPipeline ND = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{v}).withLocation("pipeline/mojang_logo").withBlend(new BlendFunction(SourceFactor.SRC_ALPHA, DestFactor.ONE)).build());
    public static final RenderPipeline Nh = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withLocation("pipeline/entity_outline_blit").withVertexShader("core/screenquad").withFragmentShader("core/blit_screen").withSampler("InSampler").withBlend(BlendFunction.ENTITY_OUTLINE_BLIT).withDepthWrite(false).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).withColorWrite(true, false).withVertexFormat(class07835.N, VertexFormat.class_5596.field_27379).build());
    public static final RenderPipeline Nr = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withLocation("pipeline/tracy_blit").withVertexShader("core/screenquad").withFragmentShader("core/blit_screen").withSampler("InSampler").withDepthWrite(false).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).withVertexFormat(class07835.N, VertexFormat.class_5596.field_27379).build());
    public static final RenderPipeline yN = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{N}).withLocation("pipeline/panorama").withVertexShader("core/panorama").withFragmentShader("core/panorama").withSampler("Sampler0").withDepthWrite(false).withColorWrite(true, false).withVertexFormat(class07835.i, VertexFormat.class_5596.field_27382).build());
    public static final RenderPipeline yy = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{t}).withLocation("pipeline/outline_cull").build());
    public static final RenderPipeline yL = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{t}).withLocation("pipeline/outline_no_cull").withCull(false).build());
    public static final RenderPipeline yu = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withLocation("pipeline/lightmap").withVertexShader("core/screenquad").withFragmentShader("core/lightmap").withUniform("LightmapInfo", class08419.field_60031).withVertexFormat(class07835.N, VertexFormat.class_5596.field_27379).withDepthWrite(false).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).build());
    public static final RenderPipeline.Snippet yi = RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[0]).withVertexShader("core/animate_sprite").withUniform("SpriteAnimationInfo", class08419.field_60031).withVertexFormat(class07835.N, VertexFormat.class_5596.field_27379).withDepthWrite(false).withDepthTestFunction(DepthTestFunction.NO_DEPTH_TEST).buildSnippet();
    public static final RenderPipeline yR = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{yi}).withFragmentShader("core/animate_sprite_blit").withLocation("pipeline/animate_sprite_blit").withSampler("Sprite").build());
    public static final RenderPipeline yM = class08394.N(RenderPipeline.builder((RenderPipeline.Snippet[])new RenderPipeline.Snippet[]{yi}).withFragmentShader("core/animate_sprite_interpolate").withLocation("pipeline/animate_sprite_interpolate").withSampler("CurrentSprite").withSampler("NextSprite").build());

    public static List<RenderPipeline> N() {
        return yB.values().stream().toList();
    }

    public static RenderPipeline N(RenderPipeline renderPipeline) {
        yB.put(renderPipeline.getLocation(), renderPipeline);
        return renderPipeline;
    }

    public RenderPipeline.Snippet getLinesSnippet() {
        return P;
    }

    public RenderPipeline baritone$registerPipeline(RenderPipeline renderPipeline) {
        return class08394.N(renderPipeline);
    }

    public RenderPipeline.Snippet getMatricesFogSnippet() {
        return u;
    }
}

