# Minecraft / Fabric
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.18.4
loom_version=1.10.5

# Fabric API
fabric_version=0.134.0+1.21.8

# Kotlin
kotlin_version=2.1.10
fabric_kotlin_version=1.13.1+kotlin.2.1.10

# Mod
mod_version=1.0.0
maven_group=kotakbaz.rain
archives_base_name=rain-visuals

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
