/*
 * Decompiled with CFR 0.152.
 */
package jnr.a64asm;

public final class SYSREG_CODE
extends Enum<SYSREG_CODE> {
    public static final /* enum */ SYSREG_CODE OSECCR_EL1;
    public static final /* enum */ SYSREG_CODE ID_AA64PFR1_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR15_EL0;
    public static final /* enum */ SYSREG_CODE FAR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER4_EL0;
    public static final /* enum */ SYSREG_CODE DBGWCR14_EL1;
    public static final /* enum */ SYSREG_CODE ID_PFR1_EL1;
    public static final /* enum */ SYSREG_CODE TTBR0_EL1;
    public static final /* enum */ SYSREG_CODE VTCR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVTYPER0_EL0;
    public static final /* enum */ SYSREG_CODE ESR_EL2;
    public static final /* enum */ SYSREG_CODE ID_AA64AFR0_EL1;
    public static final /* enum */ SYSREG_CODE MDCCINT_EL1;
    public static final /* enum */ SYSREG_CODE RMR_EL1;
    public static final /* enum */ SYSREG_CODE PMOVSSET_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR16_EL0;
    public static final /* enum */ SYSREG_CODE PMEVTYPER22_EL0;
    public static final /* enum */ SYSREG_CODE DBGBCR12_EL1;
    public static final /* enum */ SYSREG_CODE ID_DFR0_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR1_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR14_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR12_EL0;
    public static final /* enum */ SYSREG_CODE DBGWVR9_EL1;
    public static final /* enum */ SYSREG_CODE DBGWCR0_EL1;
    public static final /* enum */ SYSREG_CODE DBGBCR2_EL1;
    public static final /* enum */ SYSREG_CODE DBGBVR4_EL1;
    public static final /* enum */ SYSREG_CODE FPEXC32_EL2;
    public static final /* enum */ SYSREG_CODE DBGWCR11_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR23_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR8_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER30_EL0;
    public static final /* enum */ SYSREG_CODE PMEVTYPER14_EL0;
    public static final /* enum */ SYSREG_CODE PMEVTYPER13_EL0;
    public static final /* enum */ SYSREG_CODE RMR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVCNTR26_EL0;
    public static final /* enum */ SYSREG_CODE DBGBCR14_EL1;
    public static final /* enum */ SYSREG_CODE CURRENTEL;
    public static final /* enum */ SYSREG_CODE DBGDTRRX_EL0;
    public static final /* enum */ SYSREG_CODE AMAIR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER29_EL0;
    public static final /* enum */ SYSREG_CODE DBGBCR3_EL1;
    public static final /* enum */ SYSREG_CODE ELR_EL1;
    public static final /* enum */ SYSREG_CODE DBGWVR13_EL1;
    public static final /* enum */ SYSREG_CODE DACR32_EL2;
    public static final /* enum */ SYSREG_CODE CPTR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVTYPER1_EL0;
    public static final /* enum */ SYSREG_CODE PMINTENCLR_EL1;
    public static final /* enum */ SYSREG_CODE VBAR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR20_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR9_EL0;
    public static final /* enum */ SYSREG_CODE ELR_EL3;
    public static final /* enum */ SYSREG_CODE ISR_EL1;
    public static final /* enum */ SYSREG_CODE AIDR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR6_EL0;
    public static final /* enum */ SYSREG_CODE PMSWINC_EL0;
    public static final /* enum */ SYSREG_CODE DBGWVR12_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER26_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR17_EL0;
    public static final /* enum */ SYSREG_CODE DBGWCR5_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER25_EL0;
    public static final /* enum */ SYSREG_CODE FPSR;
    public static final /* enum */ SYSREG_CODE ID_ISAR3_EL1;
    public static final /* enum */ SYSREG_CODE SCTLR_EL3;
    public static final /* enum */ SYSREG_CODE ID_MMFR1_EL1;
    public static final /* enum */ SYSREG_CODE FAR_EL2;
    public static final /* enum */ SYSREG_CODE VTTBR_EL2;
    public static final /* enum */ SYSREG_CODE DBGWVR8_EL1;
    public static final /* enum */ SYSREG_CODE MDSCR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER3_EL0;
    public static final /* enum */ SYSREG_CODE CNTPS_TVAL_EL1;
    public static final /* enum */ SYSREG_CODE RMR_EL3;
    public static final /* enum */ SYSREG_CODE DAIF;
    public static final /* enum */ SYSREG_CODE PMEVCNTR13_EL0;
    public static final /* enum */ SYSREG_CODE CCSIDR_EL1;
    public static final /* enum */ SYSREG_CODE DBGBCR13_EL1;
    public static final /* enum */ SYSREG_CODE TTBR0_EL3;
    public static final /* enum */ SYSREG_CODE DBGWVR4_EL1;
    public static final /* enum */ SYSREG_CODE DBGVCR32_EL2;
    public static final /* enum */ SYSREG_CODE SYSREG_MAX;
    public static final /* enum */ SYSREG_CODE PMUSERENR_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR25_EL0;
    public static final /* enum */ SYSREG_CODE MAIR_EL3;
    public static final /* enum */ SYSREG_CODE DBGWCR9_EL1;
    public static final /* enum */ SYSREG_CODE DBGBCR9_EL1;
    public static final /* enum */ SYSREG_CODE MVFR1_EL1;
    public static final /* enum */ SYSREG_CODE TEEHBR32_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER20_EL0;
    public static final /* enum */ SYSREG_CODE AFSR0_EL2;
    public static final /* enum */ SYSREG_CODE DBGWVR15_EL1;
    public static final /* enum */ SYSREG_CODE TPIDR_EL1;
    public static final /* enum */ SYSREG_CODE PMCCFILTR_EL0;
    public static final /* enum */ SYSREG_CODE PMCNTENSET_EL0;
    public static final /* enum */ SYSREG_CODE VBAR_EL3;
    public static final /* enum */ SYSREG_CODE AMAIR_EL3;
    public static final /* enum */ SYSREG_CODE ID_AA64ISAR0_EL1;
    public static final /* enum */ SYSREG_CODE DBGWCR7_EL1;
    public static final /* enum */ SYSREG_CODE SPSR_SVC;
    public static final /* enum */ SYSREG_CODE DBGWCR1_EL1;
    public static final /* enum */ SYSREG_CODE CNTHCTL_EL2;
    public static final /* enum */ SYSREG_CODE DBGBCR6_EL1;
    public static final /* enum */ SYSREG_CODE MIDR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER16_EL0;
    public static final /* enum */ SYSREG_CODE ACTLR_EL1;
    public static final /* enum */ SYSREG_CODE SP_EL1;
    public static final /* enum */ SYSREG_CODE DBGAUTHSTATUS_EL1;
    public static final /* enum */ SYSREG_CODE SPSR_ABT;
    public static final /* enum */ SYSREG_CODE CPACR_EL1;
    public static final /* enum */ SYSREG_CODE DBGWCR13_EL1;
    public static final /* enum */ SYSREG_CODE MAIR_EL2;
    public static final /* enum */ SYSREG_CODE PMCEID1_EL0;
    public static final /* enum */ SYSREG_CODE DBGWVR7_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER19_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR11_EL1;
    public static final /* enum */ SYSREG_CODE FAR_EL3;
    public static final /* enum */ SYSREG_CODE DBGCLAIMCLR_EL1;
    public static final /* enum */ SYSREG_CODE DLR_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR24_EL0;
    public static final /* enum */ SYSREG_CODE PMSELR_EL0;
    public static final /* enum */ SYSREG_CODE PMCEID0_EL0;
    public static final /* enum */ SYSREG_CODE ID_ISAR5_EL1;
    public static final /* enum */ SYSREG_CODE TCR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVCNTR5_EL0;
    public static final /* enum */ SYSREG_CODE TTBR0_EL2;
    public static final /* enum */ SYSREG_CODE ID_PFR0_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER18_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR5_EL1;
    public static final /* enum */ SYSREG_CODE CNTHP_TVAL_EL2;
    public static final /* enum */ SYSREG_CODE CNTV_TVAL_EL0;
    public static final /* enum */ SYSREG_CODE SPSR_HYP;
    public static final /* enum */ SYSREG_CODE CNTHP_CTL_EL2;
    public static final /* enum */ SYSREG_CODE PMEVTYPER7_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR15_EL1;
    public static final /* enum */ SYSREG_CODE CNTPS_CVAL_EL1;
    public static final /* enum */ SYSREG_CODE SPSR_IRQ;
    public static final /* enum */ SYSREG_CODE DBGWCR15_EL1;
    public static final /* enum */ SYSREG_CODE MPIDR_EL1;
    public static final /* enum */ SYSREG_CODE TTBR1_EL1;
    public static final /* enum */ SYSREG_CODE IFSR32_EL2;
    public static final /* enum */ SYSREG_CODE ID_MMFR0_EL1;
    public static final /* enum */ SYSREG_CODE DBGWCR6_EL1;
    public static final /* enum */ SYSREG_CODE CNTKCTL_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR2_EL0;
    public static final /* enum */ SYSREG_CODE ESR_EL3;
    public static final /* enum */ SYSREG_CODE TPIDR_EL0;
    public static final /* enum */ SYSREG_CODE ID_AFR0_EL1;
    public static final /* enum */ SYSREG_CODE SDER32_EL3;
    public static final /* enum */ SYSREG_CODE DBGPRCR_EL1;
    public static final /* enum */ SYSREG_CODE HPFAR_EL2;
    public static final /* enum */ SYSREG_CODE CNTFRQ_EL0;
    public static final /* enum */ SYSREG_CODE PMEVTYPER27_EL0;
    public static final /* enum */ SYSREG_CODE DBGBCR7_EL1;
    public static final /* enum */ SYSREG_CODE DBGBVR12_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER9_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR7_EL0;
    public static final /* enum */ SYSREG_CODE AFSR0_EL1;
    public static final /* enum */ SYSREG_CODE ESR_EL1;
    public static final /* enum */ SYSREG_CODE RVBAR_EL2;
    public static final /* enum */ SYSREG_CODE OSLSR_EL1;
    public static final /* enum */ SYSREG_CODE HACR_EL2;
    public static final /* enum */ SYSREG_CODE ACTLR_EL2;
    public static final /* enum */ SYSREG_CODE PMCR_EL0;
    public static final /* enum */ SYSREG_CODE PMOVSCLR_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR13_EL1;
    public static final /* enum */ SYSREG_CODE DBGWVR11_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER21_EL0;
    public static final /* enum */ SYSREG_CODE CLIDR_EL1;
    public static final /* enum */ SYSREG_CODE CNTVOFF_EL2;
    public static final /* enum */ SYSREG_CODE TEECR32_EL1;
    public static final /* enum */ SYSREG_CODE AMAIR_EL2;
    public static final /* enum */ SYSREG_CODE ELR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVTYPER15_EL0;
    public static final /* enum */ SYSREG_CODE ID_ISAR2_EL1;
    public static final /* enum */ SYSREG_CODE RVBAR_EL1;
    public static final /* enum */ SYSREG_CODE CNTV_CTL_EL0;
    public static final /* enum */ SYSREG_CODE ID_AA64DFR0_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER24_EL0;
    public static final /* enum */ SYSREG_CODE SCTLR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVCNTR28_EL0;
    public static final /* enum */ SYSREG_CODE VBAR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVTYPER17_EL0;
    public static final /* enum */ SYSREG_CODE DBGWCR8_EL1;
    public static final /* enum */ SYSREG_CODE DBGBVR6_EL1;
    public static final /* enum */ SYSREG_CODE PMXEVTYPER_EL0;
    public static final /* enum */ SYSREG_CODE ID_AA64DFR1_EL1;
    public static final /* enum */ SYSREG_CODE DBGBCR0_EL1;
    public static final /* enum */ SYSREG_CODE ID_AA64MMFR1_EL1;
    public static final /* enum */ SYSREG_CODE MVFR0_EL1;
    public static final /* enum */ SYSREG_CODE SP_EL2;
    public static final /* enum */ SYSREG_CODE CNTVCT_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR3_EL0;
    public static final /* enum */ SYSREG_CODE DBGWVR3_EL1;
    public static final /* enum */ SYSREG_CODE SPSR_EL3;
    public static final /* enum */ SYSREG_CODE MAIR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER23_EL0;
    public static final /* enum */ SYSREG_CODE ID_AA64PFR0_EL1;
    public static final /* enum */ SYSREG_CODE SPSR_FIQ;
    public static final /* enum */ SYSREG_CODE MDCCSR_EL0;
    public static final /* enum */ SYSREG_CODE MVFR2_EL1;
    public static final /* enum */ SYSREG_CODE ID_ISAR4_EL1;
    public static final /* enum */ SYSREG_CODE FPCR;
    public static final /* enum */ SYSREG_CODE DBGDTR_EL0;
    public static final /* enum */ SYSREG_CODE ACTLR_EL3;
    public static final /* enum */ SYSREG_CODE PMEVTYPER10_EL0;
    public static final /* enum */ SYSREG_CODE CONTEXTIDR_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR10_EL0;
    public static final /* enum */ SYSREG_CODE DBGWCR3_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR11_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR22_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR10_EL1;
    public static final /* enum */ SYSREG_CODE OSDTRTX_EL1;
    public static final /* enum */ SYSREG_CODE DBGWCR2_EL1;
    public static final /* enum */ SYSREG_CODE PMINTENSET_EL1;
    public static final /* enum */ SYSREG_CODE PMCNTENCLR_EL0;
    public static final /* enum */ SYSREG_CODE ID_MMFR3_EL1;
    public static final /* enum */ SYSREG_CODE DBGWVR5_EL1;
    public static final /* enum */ SYSREG_CODE VMPIDR_EL2;
    public static final /* enum */ SYSREG_CODE TCR_EL1;
    public static final /* enum */ SYSREG_CODE VPIDR_EL2;
    public static final /* enum */ SYSREG_CODE CSSELR_EL1;
    public static final /* enum */ SYSREG_CODE ID_ISAR1_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER5_EL0;
    public static final /* enum */ SYSREG_CODE DBGBCR8_EL1;
    public static final /* enum */ SYSREG_CODE DBGWVR6_EL1;
    public static final /* enum */ SYSREG_CODE OSDTRRX_EL1;
    public static final /* enum */ SYSREG_CODE PMCCNTR_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR8_EL0;
    public static final /* enum */ SYSREG_CODE AFSR0_EL3;
    public static final /* enum */ SYSREG_CODE CNTP_TVAL_EL0;
    public static final /* enum */ SYSREG_CODE AFSR1_EL3;
    public static final /* enum */ SYSREG_CODE PAR_EL1;
    public static final /* enum */ SYSREG_CODE DBGBCR1_EL1;
    public static final /* enum */ SYSREG_CODE ID_ISAR0_EL1;
    public static final /* enum */ SYSREG_CODE REVIDR_EL1;
    public static final /* enum */ SYSREG_CODE PMXEVCNTR_EL0;
    public static final /* enum */ SYSREG_CODE CNTP_CVAL_EL0;
    public static final /* enum */ SYSREG_CODE OSDLR_EL1;
    public static final /* enum */ SYSREG_CODE AFSR1_EL2;
    public static final /* enum */ SYSREG_CODE PMEVCNTR30_EL0;
    public static final /* enum */ SYSREG_CODE DBGBCR5_EL1;
    public static final /* enum */ SYSREG_CODE DBGBVR7_EL1;
    public static final /* enum */ SYSREG_CODE NZCV;
    public static final /* enum */ SYSREG_CODE MDCR_EL2;
    public static final /* enum */ SYSREG_CODE ID_MMFR2_EL1;
    public static final /* enum */ SYSREG_CODE MDCR_EL3;
    public static final /* enum */ SYSREG_CODE DBGBCR10_EL1;
    public static final /* enum */ SYSREG_CODE MDRAR_EL1;
    public static final /* enum */ SYSREG_CODE OSLAR_EL1;
    public static final /* enum */ SYSREG_CODE CTR_EL0;
    public static final /* enum */ SYSREG_CODE TPIDRRO_EL0;
    public static final /* enum */ SYSREG_CODE PMEVTYPER12_EL0;
    public static final /* enum */ SYSREG_CODE SPSR_EL2;
    public static final /* enum */ SYSREG_CODE CPTR_EL3;
    public static final /* enum */ SYSREG_CODE CNTPCT_EL0;
    public static final /* enum */ SYSREG_CODE SPSR_EL1;
    public static final /* enum */ SYSREG_CODE HCR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVTYPER6_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR18_EL0;
    public static final /* enum */ SYSREG_CODE TPIDR_EL2;
    public static final /* enum */ SYSREG_CODE DBGBCR15_EL1;
    public static final /* enum */ SYSREG_CODE DBGWCR4_EL1;
    public static final /* enum */ SYSREG_CODE SCTLR_EL1;
    public static final /* enum */ SYSREG_CODE DBGBCR4_EL1;
    private static final /* synthetic */ SYSREG_CODE[] $VALUES;
    public static final /* enum */ SYSREG_CODE PMEVCNTR21_EL0;
    public static final /* enum */ SYSREG_CODE SPSR_UND;
    public static final /* enum */ SYSREG_CODE HSTR_EL2;
    public static final /* enum */ SYSREG_CODE PMEVCNTR29_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR0_EL0;
    public static final /* enum */ SYSREG_CODE SP_EL0;
    public static final /* enum */ SYSREG_CODE TPIDR_EL3;
    public static final /* enum */ SYSREG_CODE DBGWVR10_EL1;
    public static final /* enum */ SYSREG_CODE SCR_EL3;
    public static final /* enum */ SYSREG_CODE DBGWVR14_EL1;
    public static final /* enum */ SYSREG_CODE DBGCLAIMSET_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER2_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR14_EL1;
    public static final /* enum */ SYSREG_CODE DBGBVR0_EL1;
    public static final /* enum */ SYSREG_CODE DBGWVR2_EL1;
    public static final /* enum */ SYSREG_CODE ID_AA64AFR1_EL1;
    public static final /* enum */ SYSREG_CODE DBGWVR1_EL1;
    public static final /* enum */ SYSREG_CODE DBGBVR3_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER28_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR1_EL1;
    public static final /* enum */ SYSREG_CODE PMEVTYPER8_EL0;
    public static final /* enum */ SYSREG_CODE PMEVTYPER11_EL0;
    public static final /* enum */ SYSREG_CODE DBGBCR11_EL1;
    public static final /* enum */ SYSREG_CODE DSPSR_EL0;
    public static final /* enum */ SYSREG_CODE PMEVCNTR19_EL0;
    public static final /* enum */ SYSREG_CODE ID_AA64MMFR0_EL1;
    public static final /* enum */ SYSREG_CODE TCR_EL3;
    public static final /* enum */ SYSREG_CODE RVBAR_EL3;
    public static final /* enum */ SYSREG_CODE DBGWCR12_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR4_EL0;
    public static final /* enum */ SYSREG_CODE DBGWVR0_EL1;
    public static final /* enum */ SYSREG_CODE PMEVCNTR27_EL0;
    public static final /* enum */ SYSREG_CODE DBGWCR10_EL1;
    public static final /* enum */ SYSREG_CODE CNTP_CTL_EL0;
    public static final /* enum */ SYSREG_CODE DBGBVR9_EL1;
    public static final /* enum */ SYSREG_CODE ID_AA64ISAR1_EL1;
    public static final /* enum */ SYSREG_CODE DCZID_EL0;
    public static final /* enum */ SYSREG_CODE AFSR1_EL1;
    public static final /* enum */ SYSREG_CODE CNTPS_CTL_EL1;
    public static final /* enum */ SYSREG_CODE DBGBVR2_EL1;
    public static final /* enum */ SYSREG_CODE CNTV_CVAL_EL0;
    public static final /* enum */ SYSREG_CODE DBGDTRTX_EL0;
    public static final /* enum */ SYSREG_CODE CNTHP_CVAL_EL2;
    public static final /* enum */ SYSREG_CODE SPSEL;

    static {
        SPSR_EL1 = new SYSREG_CODE();
        ELR_EL1 = new SYSREG_CODE();
        SP_EL0 = new SYSREG_CODE();
        SPSEL = new SYSREG_CODE();
        DAIF = new SYSREG_CODE();
        CURRENTEL = new SYSREG_CODE();
        NZCV = new SYSREG_CODE();
        FPCR = new SYSREG_CODE();
        FPSR = new SYSREG_CODE();
        DSPSR_EL0 = new SYSREG_CODE();
        DLR_EL0 = new SYSREG_CODE();
        SPSR_EL2 = new SYSREG_CODE();
        ELR_EL2 = new SYSREG_CODE();
        SP_EL1 = new SYSREG_CODE();
        SPSR_IRQ = new SYSREG_CODE();
        SPSR_ABT = new SYSREG_CODE();
        SPSR_UND = new SYSREG_CODE();
        SPSR_FIQ = new SYSREG_CODE();
        SPSR_EL3 = new SYSREG_CODE();
        ELR_EL3 = new SYSREG_CODE();
        SP_EL2 = new SYSREG_CODE();
        SPSR_SVC = new SYSREG_CODE();
        SPSR_HYP = new SYSREG_CODE();
        MIDR_EL1 = new SYSREG_CODE();
        CTR_EL0 = new SYSREG_CODE();
        MPIDR_EL1 = new SYSREG_CODE();
        REVIDR_EL1 = new SYSREG_CODE();
        AIDR_EL1 = new SYSREG_CODE();
        DCZID_EL0 = new SYSREG_CODE();
        ID_DFR0_EL1 = new SYSREG_CODE();
        ID_PFR0_EL1 = new SYSREG_CODE();
        ID_PFR1_EL1 = new SYSREG_CODE();
        ID_AFR0_EL1 = new SYSREG_CODE();
        ID_MMFR0_EL1 = new SYSREG_CODE();
        ID_MMFR1_EL1 = new SYSREG_CODE();
        ID_MMFR2_EL1 = new SYSREG_CODE();
        ID_MMFR3_EL1 = new SYSREG_CODE();
        ID_ISAR0_EL1 = new SYSREG_CODE();
        ID_ISAR1_EL1 = new SYSREG_CODE();
        ID_ISAR2_EL1 = new SYSREG_CODE();
        ID_ISAR3_EL1 = new SYSREG_CODE();
        ID_ISAR4_EL1 = new SYSREG_CODE();
        ID_ISAR5_EL1 = new SYSREG_CODE();
        MVFR0_EL1 = new SYSREG_CODE();
        MVFR1_EL1 = new SYSREG_CODE();
        MVFR2_EL1 = new SYSREG_CODE();
        CCSIDR_EL1 = new SYSREG_CODE();
        ID_AA64PFR0_EL1 = new SYSREG_CODE();
        ID_AA64PFR1_EL1 = new SYSREG_CODE();
        ID_AA64DFR0_EL1 = new SYSREG_CODE();
        ID_AA64DFR1_EL1 = new SYSREG_CODE();
        ID_AA64ISAR0_EL1 = new SYSREG_CODE();
        ID_AA64ISAR1_EL1 = new SYSREG_CODE();
        ID_AA64MMFR0_EL1 = new SYSREG_CODE();
        ID_AA64MMFR1_EL1 = new SYSREG_CODE();
        ID_AA64AFR0_EL1 = new SYSREG_CODE();
        ID_AA64AFR1_EL1 = new SYSREG_CODE();
        CLIDR_EL1 = new SYSREG_CODE();
        CSSELR_EL1 = new SYSREG_CODE();
        VPIDR_EL2 = new SYSREG_CODE();
        VMPIDR_EL2 = new SYSREG_CODE();
        SCTLR_EL1 = new SYSREG_CODE();
        SCTLR_EL2 = new SYSREG_CODE();
        SCTLR_EL3 = new SYSREG_CODE();
        ACTLR_EL1 = new SYSREG_CODE();
        ACTLR_EL2 = new SYSREG_CODE();
        ACTLR_EL3 = new SYSREG_CODE();
        CPACR_EL1 = new SYSREG_CODE();
        CPTR_EL2 = new SYSREG_CODE();
        CPTR_EL3 = new SYSREG_CODE();
        SCR_EL3 = new SYSREG_CODE();
        HCR_EL2 = new SYSREG_CODE();
        MDCR_EL2 = new SYSREG_CODE();
        MDCR_EL3 = new SYSREG_CODE();
        HSTR_EL2 = new SYSREG_CODE();
        HACR_EL2 = new SYSREG_CODE();
        TTBR0_EL1 = new SYSREG_CODE();
        TTBR1_EL1 = new SYSREG_CODE();
        TTBR0_EL2 = new SYSREG_CODE();
        TTBR0_EL3 = new SYSREG_CODE();
        VTTBR_EL2 = new SYSREG_CODE();
        TCR_EL1 = new SYSREG_CODE();
        TCR_EL2 = new SYSREG_CODE();
        TCR_EL3 = new SYSREG_CODE();
        VTCR_EL2 = new SYSREG_CODE();
        AFSR0_EL1 = new SYSREG_CODE();
        AFSR1_EL1 = new SYSREG_CODE();
        AFSR0_EL2 = new SYSREG_CODE();
        AFSR1_EL2 = new SYSREG_CODE();
        AFSR0_EL3 = new SYSREG_CODE();
        AFSR1_EL3 = new SYSREG_CODE();
        ESR_EL1 = new SYSREG_CODE();
        ESR_EL2 = new SYSREG_CODE();
        ESR_EL3 = new SYSREG_CODE();
        FPEXC32_EL2 = new SYSREG_CODE();
        FAR_EL1 = new SYSREG_CODE();
        FAR_EL2 = new SYSREG_CODE();
        FAR_EL3 = new SYSREG_CODE();
        HPFAR_EL2 = new SYSREG_CODE();
        PAR_EL1 = new SYSREG_CODE();
        MAIR_EL1 = new SYSREG_CODE();
        MAIR_EL2 = new SYSREG_CODE();
        MAIR_EL3 = new SYSREG_CODE();
        AMAIR_EL1 = new SYSREG_CODE();
        AMAIR_EL2 = new SYSREG_CODE();
        AMAIR_EL3 = new SYSREG_CODE();
        VBAR_EL1 = new SYSREG_CODE();
        VBAR_EL2 = new SYSREG_CODE();
        VBAR_EL3 = new SYSREG_CODE();
        RVBAR_EL1 = new SYSREG_CODE();
        RVBAR_EL2 = new SYSREG_CODE();
        RVBAR_EL3 = new SYSREG_CODE();
        RMR_EL1 = new SYSREG_CODE();
        RMR_EL2 = new SYSREG_CODE();
        RMR_EL3 = new SYSREG_CODE();
        ISR_EL1 = new SYSREG_CODE();
        CONTEXTIDR_EL1 = new SYSREG_CODE();
        TPIDR_EL0 = new SYSREG_CODE();
        TPIDRRO_EL0 = new SYSREG_CODE();
        TPIDR_EL1 = new SYSREG_CODE();
        TPIDR_EL2 = new SYSREG_CODE();
        TPIDR_EL3 = new SYSREG_CODE();
        TEECR32_EL1 = new SYSREG_CODE();
        CNTFRQ_EL0 = new SYSREG_CODE();
        CNTPCT_EL0 = new SYSREG_CODE();
        CNTVCT_EL0 = new SYSREG_CODE();
        CNTVOFF_EL2 = new SYSREG_CODE();
        CNTKCTL_EL1 = new SYSREG_CODE();
        CNTHCTL_EL2 = new SYSREG_CODE();
        CNTP_TVAL_EL0 = new SYSREG_CODE();
        CNTP_CTL_EL0 = new SYSREG_CODE();
        CNTP_CVAL_EL0 = new SYSREG_CODE();
        CNTV_TVAL_EL0 = new SYSREG_CODE();
        CNTV_CTL_EL0 = new SYSREG_CODE();
        CNTV_CVAL_EL0 = new SYSREG_CODE();
        CNTHP_TVAL_EL2 = new SYSREG_CODE();
        CNTHP_CTL_EL2 = new SYSREG_CODE();
        CNTHP_CVAL_EL2 = new SYSREG_CODE();
        CNTPS_TVAL_EL1 = new SYSREG_CODE();
        CNTPS_CTL_EL1 = new SYSREG_CODE();
        CNTPS_CVAL_EL1 = new SYSREG_CODE();
        DACR32_EL2 = new SYSREG_CODE();
        IFSR32_EL2 = new SYSREG_CODE();
        TEEHBR32_EL1 = new SYSREG_CODE();
        SDER32_EL3 = new SYSREG_CODE();
        MDSCR_EL1 = new SYSREG_CODE();
        MDCCSR_EL0 = new SYSREG_CODE();
        MDCCINT_EL1 = new SYSREG_CODE();
        DBGDTR_EL0 = new SYSREG_CODE();
        DBGDTRRX_EL0 = new SYSREG_CODE();
        DBGDTRTX_EL0 = new SYSREG_CODE();
        OSDTRRX_EL1 = new SYSREG_CODE();
        OSDTRTX_EL1 = new SYSREG_CODE();
        OSECCR_EL1 = new SYSREG_CODE();
        DBGVCR32_EL2 = new SYSREG_CODE();
        DBGBVR0_EL1 = new SYSREG_CODE();
        DBGBVR1_EL1 = new SYSREG_CODE();
        DBGBVR2_EL1 = new SYSREG_CODE();
        DBGBVR3_EL1 = new SYSREG_CODE();
        DBGBVR4_EL1 = new SYSREG_CODE();
        DBGBVR5_EL1 = new SYSREG_CODE();
        DBGBVR6_EL1 = new SYSREG_CODE();
        DBGBVR7_EL1 = new SYSREG_CODE();
        DBGBVR8_EL1 = new SYSREG_CODE();
        DBGBVR9_EL1 = new SYSREG_CODE();
        DBGBVR10_EL1 = new SYSREG_CODE();
        DBGBVR11_EL1 = new SYSREG_CODE();
        DBGBVR12_EL1 = new SYSREG_CODE();
        DBGBVR13_EL1 = new SYSREG_CODE();
        DBGBVR14_EL1 = new SYSREG_CODE();
        DBGBVR15_EL1 = new SYSREG_CODE();
        DBGBCR0_EL1 = new SYSREG_CODE();
        DBGBCR1_EL1 = new SYSREG_CODE();
        DBGBCR2_EL1 = new SYSREG_CODE();
        DBGBCR3_EL1 = new SYSREG_CODE();
        DBGBCR4_EL1 = new SYSREG_CODE();
        DBGBCR5_EL1 = new SYSREG_CODE();
        DBGBCR6_EL1 = new SYSREG_CODE();
        DBGBCR7_EL1 = new SYSREG_CODE();
        DBGBCR8_EL1 = new SYSREG_CODE();
        DBGBCR9_EL1 = new SYSREG_CODE();
        DBGBCR10_EL1 = new SYSREG_CODE();
        DBGBCR11_EL1 = new SYSREG_CODE();
        DBGBCR12_EL1 = new SYSREG_CODE();
        DBGBCR13_EL1 = new SYSREG_CODE();
        DBGBCR14_EL1 = new SYSREG_CODE();
        DBGBCR15_EL1 = new SYSREG_CODE();
        DBGWVR0_EL1 = new SYSREG_CODE();
        DBGWVR1_EL1 = new SYSREG_CODE();
        DBGWVR2_EL1 = new SYSREG_CODE();
        DBGWVR3_EL1 = new SYSREG_CODE();
        DBGWVR4_EL1 = new SYSREG_CODE();
        DBGWVR5_EL1 = new SYSREG_CODE();
        DBGWVR6_EL1 = new SYSREG_CODE();
        DBGWVR7_EL1 = new SYSREG_CODE();
        DBGWVR8_EL1 = new SYSREG_CODE();
        DBGWVR9_EL1 = new SYSREG_CODE();
        DBGWVR10_EL1 = new SYSREG_CODE();
        DBGWVR11_EL1 = new SYSREG_CODE();
        DBGWVR12_EL1 = new SYSREG_CODE();
        DBGWVR13_EL1 = new SYSREG_CODE();
        DBGWVR14_EL1 = new SYSREG_CODE();
        DBGWVR15_EL1 = new SYSREG_CODE();
        DBGWCR0_EL1 = new SYSREG_CODE();
        DBGWCR1_EL1 = new SYSREG_CODE();
        DBGWCR2_EL1 = new SYSREG_CODE();
        DBGWCR3_EL1 = new SYSREG_CODE();
        DBGWCR4_EL1 = new SYSREG_CODE();
        DBGWCR5_EL1 = new SYSREG_CODE();
        DBGWCR6_EL1 = new SYSREG_CODE();
        DBGWCR7_EL1 = new SYSREG_CODE();
        DBGWCR8_EL1 = new SYSREG_CODE();
        DBGWCR9_EL1 = new SYSREG_CODE();
        DBGWCR10_EL1 = new SYSREG_CODE();
        DBGWCR11_EL1 = new SYSREG_CODE();
        DBGWCR12_EL1 = new SYSREG_CODE();
        DBGWCR13_EL1 = new SYSREG_CODE();
        DBGWCR14_EL1 = new SYSREG_CODE();
        DBGWCR15_EL1 = new SYSREG_CODE();
        MDRAR_EL1 = new SYSREG_CODE();
        OSLAR_EL1 = new SYSREG_CODE();
        OSLSR_EL1 = new SYSREG_CODE();
        OSDLR_EL1 = new SYSREG_CODE();
        DBGPRCR_EL1 = new SYSREG_CODE();
        DBGCLAIMSET_EL1 = new SYSREG_CODE();
        DBGCLAIMCLR_EL1 = new SYSREG_CODE();
        DBGAUTHSTATUS_EL1 = new SYSREG_CODE();
        PMCR_EL0 = new SYSREG_CODE();
        PMCNTENSET_EL0 = new SYSREG_CODE();
        PMCNTENCLR_EL0 = new SYSREG_CODE();
        PMOVSCLR_EL0 = new SYSREG_CODE();
        PMSWINC_EL0 = new SYSREG_CODE();
        PMSELR_EL0 = new SYSREG_CODE();
        PMCEID0_EL0 = new SYSREG_CODE();
        PMCEID1_EL0 = new SYSREG_CODE();
        PMCCNTR_EL0 = new SYSREG_CODE();
        PMXEVTYPER_EL0 = new SYSREG_CODE();
        PMXEVCNTR_EL0 = new SYSREG_CODE();
        PMUSERENR_EL0 = new SYSREG_CODE();
        PMINTENSET_EL1 = new SYSREG_CODE();
        PMINTENCLR_EL1 = new SYSREG_CODE();
        PMOVSSET_EL0 = new SYSREG_CODE();
        PMEVCNTR0_EL0 = new SYSREG_CODE();
        PMEVCNTR1_EL0 = new SYSREG_CODE();
        PMEVCNTR2_EL0 = new SYSREG_CODE();
        PMEVCNTR3_EL0 = new SYSREG_CODE();
        PMEVCNTR4_EL0 = new SYSREG_CODE();
        PMEVCNTR5_EL0 = new SYSREG_CODE();
        PMEVCNTR6_EL0 = new SYSREG_CODE();
        PMEVCNTR7_EL0 = new SYSREG_CODE();
        PMEVCNTR8_EL0 = new SYSREG_CODE();
        PMEVCNTR9_EL0 = new SYSREG_CODE();
        PMEVCNTR10_EL0 = new SYSREG_CODE();
        PMEVCNTR11_EL0 = new SYSREG_CODE();
        PMEVCNTR12_EL0 = new SYSREG_CODE();
        PMEVCNTR13_EL0 = new SYSREG_CODE();
        PMEVCNTR14_EL0 = new SYSREG_CODE();
        PMEVCNTR15_EL0 = new SYSREG_CODE();
        PMEVCNTR16_EL0 = new SYSREG_CODE();
        PMEVCNTR17_EL0 = new SYSREG_CODE();
        PMEVCNTR18_EL0 = new SYSREG_CODE();
        PMEVCNTR19_EL0 = new SYSREG_CODE();
        PMEVCNTR20_EL0 = new SYSREG_CODE();
        PMEVCNTR21_EL0 = new SYSREG_CODE();
        PMEVCNTR22_EL0 = new SYSREG_CODE();
        PMEVCNTR23_EL0 = new SYSREG_CODE();
        PMEVCNTR24_EL0 = new SYSREG_CODE();
        PMEVCNTR25_EL0 = new SYSREG_CODE();
        PMEVCNTR26_EL0 = new SYSREG_CODE();
        PMEVCNTR27_EL0 = new SYSREG_CODE();
        PMEVCNTR28_EL0 = new SYSREG_CODE();
        PMEVCNTR29_EL0 = new SYSREG_CODE();
        PMEVCNTR30_EL0 = new SYSREG_CODE();
        PMEVTYPER0_EL0 = new SYSREG_CODE();
        PMEVTYPER1_EL0 = new SYSREG_CODE();
        PMEVTYPER2_EL0 = new SYSREG_CODE();
        PMEVTYPER3_EL0 = new SYSREG_CODE();
        PMEVTYPER4_EL0 = new SYSREG_CODE();
        PMEVTYPER5_EL0 = new SYSREG_CODE();
        PMEVTYPER6_EL0 = new SYSREG_CODE();
        PMEVTYPER7_EL0 = new SYSREG_CODE();
        PMEVTYPER8_EL0 = new SYSREG_CODE();
        PMEVTYPER9_EL0 = new SYSREG_CODE();
        PMEVTYPER10_EL0 = new SYSREG_CODE();
        PMEVTYPER11_EL0 = new SYSREG_CODE();
        PMEVTYPER12_EL0 = new SYSREG_CODE();
        PMEVTYPER13_EL0 = new SYSREG_CODE();
        PMEVTYPER14_EL0 = new SYSREG_CODE();
        PMEVTYPER15_EL0 = new SYSREG_CODE();
        PMEVTYPER16_EL0 = new SYSREG_CODE();
        PMEVTYPER17_EL0 = new SYSREG_CODE();
        PMEVTYPER18_EL0 = new SYSREG_CODE();
        PMEVTYPER19_EL0 = new SYSREG_CODE();
        PMEVTYPER20_EL0 = new SYSREG_CODE();
        PMEVTYPER21_EL0 = new SYSREG_CODE();
        PMEVTYPER22_EL0 = new SYSREG_CODE();
        PMEVTYPER23_EL0 = new SYSREG_CODE();
        PMEVTYPER24_EL0 = new SYSREG_CODE();
        PMEVTYPER25_EL0 = new SYSREG_CODE();
        PMEVTYPER26_EL0 = new SYSREG_CODE();
        PMEVTYPER27_EL0 = new SYSREG_CODE();
        PMEVTYPER28_EL0 = new SYSREG_CODE();
        PMEVTYPER29_EL0 = new SYSREG_CODE();
        PMEVTYPER30_EL0 = new SYSREG_CODE();
        PMCCFILTR_EL0 = new SYSREG_CODE();
        SYSREG_MAX = new SYSREG_CODE();
        SYSREG_CODE[] sYSREG_CODEArray = new SYSREG_CODE[306];
        sYSREG_CODEArray[0] = SPSR_EL1;
        sYSREG_CODEArray[1] = ELR_EL1;
        sYSREG_CODEArray[2] = SP_EL0;
        sYSREG_CODEArray[3] = SPSEL;
        sYSREG_CODEArray[4] = DAIF;
        sYSREG_CODEArray[5] = CURRENTEL;
        sYSREG_CODEArray[6] = NZCV;
        sYSREG_CODEArray[7] = FPCR;
        sYSREG_CODEArray[8] = FPSR;
        sYSREG_CODEArray[9] = DSPSR_EL0;
        sYSREG_CODEArray[10] = DLR_EL0;
        sYSREG_CODEArray[11] = SPSR_EL2;
        sYSREG_CODEArray[12] = ELR_EL2;
        sYSREG_CODEArray[13] = SP_EL1;
        sYSREG_CODEArray[14] = SPSR_IRQ;
        sYSREG_CODEArray[15] = SPSR_ABT;
        sYSREG_CODEArray[16] = SPSR_UND;
        sYSREG_CODEArray[17] = SPSR_FIQ;
        sYSREG_CODEArray[18] = SPSR_EL3;
        sYSREG_CODEArray[19] = ELR_EL3;
        sYSREG_CODEArray[20] = SP_EL2;
        sYSREG_CODEArray[21] = SPSR_SVC;
        sYSREG_CODEArray[22] = SPSR_HYP;
        sYSREG_CODEArray[23] = MIDR_EL1;
        sYSREG_CODEArray[24] = CTR_EL0;
        sYSREG_CODEArray[25] = MPIDR_EL1;
        sYSREG_CODEArray[26] = REVIDR_EL1;
        sYSREG_CODEArray[27] = AIDR_EL1;
        sYSREG_CODEArray[28] = DCZID_EL0;
        sYSREG_CODEArray[29] = ID_DFR0_EL1;
        sYSREG_CODEArray[30] = ID_PFR0_EL1;
        sYSREG_CODEArray[31] = ID_PFR1_EL1;
        sYSREG_CODEArray[32] = ID_AFR0_EL1;
        sYSREG_CODEArray[33] = ID_MMFR0_EL1;
        sYSREG_CODEArray[34] = ID_MMFR1_EL1;
        sYSREG_CODEArray[35] = ID_MMFR2_EL1;
        sYSREG_CODEArray[36] = ID_MMFR3_EL1;
        sYSREG_CODEArray[37] = ID_ISAR0_EL1;
        sYSREG_CODEArray[38] = ID_ISAR1_EL1;
        sYSREG_CODEArray[39] = ID_ISAR2_EL1;
        sYSREG_CODEArray[40] = ID_ISAR3_EL1;
        sYSREG_CODEArray[41] = ID_ISAR4_EL1;
        sYSREG_CODEArray[42] = ID_ISAR5_EL1;
        sYSREG_CODEArray[43] = MVFR0_EL1;
        sYSREG_CODEArray[44] = MVFR1_EL1;
        sYSREG_CODEArray[45] = MVFR2_EL1;
        sYSREG_CODEArray[46] = CCSIDR_EL1;
        sYSREG_CODEArray[47] = ID_AA64PFR0_EL1;
        sYSREG_CODEArray[48] = ID_AA64PFR1_EL1;
        sYSREG_CODEArray[49] = ID_AA64DFR0_EL1;
        sYSREG_CODEArray[50] = ID_AA64DFR1_EL1;
        sYSREG_CODEArray[51] = ID_AA64ISAR0_EL1;
        sYSREG_CODEArray[52] = ID_AA64ISAR1_EL1;
        sYSREG_CODEArray[53] = ID_AA64MMFR0_EL1;
        sYSREG_CODEArray[54] = ID_AA64MMFR1_EL1;
        sYSREG_CODEArray[55] = ID_AA64AFR0_EL1;
        sYSREG_CODEArray[56] = ID_AA64AFR1_EL1;
        sYSREG_CODEArray[57] = CLIDR_EL1;
        sYSREG_CODEArray[58] = CSSELR_EL1;
        sYSREG_CODEArray[59] = VPIDR_EL2;
        sYSREG_CODEArray[60] = VMPIDR_EL2;
        sYSREG_CODEArray[61] = SCTLR_EL1;
        sYSREG_CODEArray[62] = SCTLR_EL2;
        sYSREG_CODEArray[63] = SCTLR_EL3;
        sYSREG_CODEArray[64] = ACTLR_EL1;
        sYSREG_CODEArray[65] = ACTLR_EL2;
        sYSREG_CODEArray[66] = ACTLR_EL3;
        sYSREG_CODEArray[67] = CPACR_EL1;
        sYSREG_CODEArray[68] = CPTR_EL2;
        sYSREG_CODEArray[69] = CPTR_EL3;
        sYSREG_CODEArray[70] = SCR_EL3;
        sYSREG_CODEArray[71] = HCR_EL2;
        sYSREG_CODEArray[72] = MDCR_EL2;
        sYSREG_CODEArray[73] = MDCR_EL3;
        sYSREG_CODEArray[74] = HSTR_EL2;
        sYSREG_CODEArray[75] = HACR_EL2;
        sYSREG_CODEArray[76] = TTBR0_EL1;
        sYSREG_CODEArray[77] = TTBR1_EL1;
        sYSREG_CODEArray[78] = TTBR0_EL2;
        sYSREG_CODEArray[79] = TTBR0_EL3;
        sYSREG_CODEArray[80] = VTTBR_EL2;
        sYSREG_CODEArray[81] = TCR_EL1;
        sYSREG_CODEArray[82] = TCR_EL2;
        sYSREG_CODEArray[83] = TCR_EL3;
        sYSREG_CODEArray[84] = VTCR_EL2;
        sYSREG_CODEArray[85] = AFSR0_EL1;
        sYSREG_CODEArray[86] = AFSR1_EL1;
        sYSREG_CODEArray[87] = AFSR0_EL2;
        sYSREG_CODEArray[88] = AFSR1_EL2;
        sYSREG_CODEArray[89] = AFSR0_EL3;
        sYSREG_CODEArray[90] = AFSR1_EL3;
        sYSREG_CODEArray[91] = ESR_EL1;
        sYSREG_CODEArray[92] = ESR_EL2;
        sYSREG_CODEArray[93] = ESR_EL3;
        sYSREG_CODEArray[94] = FPEXC32_EL2;
        sYSREG_CODEArray[95] = FAR_EL1;
        sYSREG_CODEArray[96] = FAR_EL2;
        sYSREG_CODEArray[97] = FAR_EL3;
        sYSREG_CODEArray[98] = HPFAR_EL2;
        sYSREG_CODEArray[99] = PAR_EL1;
        sYSREG_CODEArray[100] = MAIR_EL1;
        sYSREG_CODEArray[101] = MAIR_EL2;
        sYSREG_CODEArray[102] = MAIR_EL3;
        sYSREG_CODEArray[103] = AMAIR_EL1;
        sYSREG_CODEArray[104] = AMAIR_EL2;
        sYSREG_CODEArray[105] = AMAIR_EL3;
        sYSREG_CODEArray[106] = VBAR_EL1;
        sYSREG_CODEArray[107] = VBAR_EL2;
        sYSREG_CODEArray[108] = VBAR_EL3;
        sYSREG_CODEArray[109] = RVBAR_EL1;
        sYSREG_CODEArray[110] = RVBAR_EL2;
        sYSREG_CODEArray[111] = RVBAR_EL3;
        sYSREG_CODEArray[112] = RMR_EL1;
        sYSREG_CODEArray[113] = RMR_EL2;
        sYSREG_CODEArray[114] = RMR_EL3;
        sYSREG_CODEArray[115] = ISR_EL1;
        sYSREG_CODEArray[116] = CONTEXTIDR_EL1;
        sYSREG_CODEArray[117] = TPIDR_EL0;
        sYSREG_CODEArray[118] = TPIDRRO_EL0;
        sYSREG_CODEArray[119] = TPIDR_EL1;
        sYSREG_CODEArray[120] = TPIDR_EL2;
        sYSREG_CODEArray[121] = TPIDR_EL3;
        sYSREG_CODEArray[122] = TEECR32_EL1;
        sYSREG_CODEArray[123] = CNTFRQ_EL0;
        sYSREG_CODEArray[124] = CNTPCT_EL0;
        sYSREG_CODEArray[125] = CNTVCT_EL0;
        sYSREG_CODEArray[126] = CNTVOFF_EL2;
        sYSREG_CODEArray[127] = CNTKCTL_EL1;
        sYSREG_CODEArray[128] = CNTHCTL_EL2;
        sYSREG_CODEArray[129] = CNTP_TVAL_EL0;
        sYSREG_CODEArray[130] = CNTP_CTL_EL0;
        sYSREG_CODEArray[131] = CNTP_CVAL_EL0;
        sYSREG_CODEArray[132] = CNTV_TVAL_EL0;
        sYSREG_CODEArray[133] = CNTV_CTL_EL0;
        sYSREG_CODEArray[134] = CNTV_CVAL_EL0;
        sYSREG_CODEArray[135] = CNTHP_TVAL_EL2;
        sYSREG_CODEArray[136] = CNTHP_CTL_EL2;
        sYSREG_CODEArray[137] = CNTHP_CVAL_EL2;
        sYSREG_CODEArray[138] = CNTPS_TVAL_EL1;
        sYSREG_CODEArray[139] = CNTPS_CTL_EL1;
        sYSREG_CODEArray[140] = CNTPS_CVAL_EL1;
        sYSREG_CODEArray[141] = DACR32_EL2;
        sYSREG_CODEArray[142] = IFSR32_EL2;
        sYSREG_CODEArray[143] = TEEHBR32_EL1;
        sYSREG_CODEArray[144] = SDER32_EL3;
        sYSREG_CODEArray[145] = MDSCR_EL1;
        sYSREG_CODEArray[146] = MDCCSR_EL0;
        sYSREG_CODEArray[147] = MDCCINT_EL1;
        sYSREG_CODEArray[148] = DBGDTR_EL0;
        sYSREG_CODEArray[149] = DBGDTRRX_EL0;
        sYSREG_CODEArray[150] = DBGDTRTX_EL0;
        sYSREG_CODEArray[151] = OSDTRRX_EL1;
        sYSREG_CODEArray[152] = OSDTRTX_EL1;
        sYSREG_CODEArray[153] = OSECCR_EL1;
        sYSREG_CODEArray[154] = DBGVCR32_EL2;
        sYSREG_CODEArray[155] = DBGBVR0_EL1;
        sYSREG_CODEArray[156] = DBGBVR1_EL1;
        sYSREG_CODEArray[157] = DBGBVR2_EL1;
        sYSREG_CODEArray[158] = DBGBVR3_EL1;
        sYSREG_CODEArray[159] = DBGBVR4_EL1;
        sYSREG_CODEArray[160] = DBGBVR5_EL1;
        sYSREG_CODEArray[161] = DBGBVR6_EL1;
        sYSREG_CODEArray[162] = DBGBVR7_EL1;
        sYSREG_CODEArray[163] = DBGBVR8_EL1;
        sYSREG_CODEArray[164] = DBGBVR9_EL1;
        sYSREG_CODEArray[165] = DBGBVR10_EL1;
        sYSREG_CODEArray[166] = DBGBVR11_EL1;
        sYSREG_CODEArray[167] = DBGBVR12_EL1;
        sYSREG_CODEArray[168] = DBGBVR13_EL1;
        sYSREG_CODEArray[169] = DBGBVR14_EL1;
        sYSREG_CODEArray[170] = DBGBVR15_EL1;
        sYSREG_CODEArray[171] = DBGBCR0_EL1;
        sYSREG_CODEArray[172] = DBGBCR1_EL1;
        sYSREG_CODEArray[173] = DBGBCR2_EL1;
        sYSREG_CODEArray[174] = DBGBCR3_EL1;
        sYSREG_CODEArray[175] = DBGBCR4_EL1;
        sYSREG_CODEArray[176] = DBGBCR5_EL1;
        sYSREG_CODEArray[177] = DBGBCR6_EL1;
        sYSREG_CODEArray[178] = DBGBCR7_EL1;
        sYSREG_CODEArray[179] = DBGBCR8_EL1;
        sYSREG_CODEArray[180] = DBGBCR9_EL1;
        sYSREG_CODEArray[181] = DBGBCR10_EL1;
        sYSREG_CODEArray[182] = DBGBCR11_EL1;
        sYSREG_CODEArray[183] = DBGBCR12_EL1;
        sYSREG_CODEArray[184] = DBGBCR13_EL1;
        sYSREG_CODEArray[185] = DBGBCR14_EL1;
        sYSREG_CODEArray[186] = DBGBCR15_EL1;
        sYSREG_CODEArray[187] = DBGWVR0_EL1;
        sYSREG_CODEArray[188] = DBGWVR1_EL1;
        sYSREG_CODEArray[189] = DBGWVR2_EL1;
        sYSREG_CODEArray[190] = DBGWVR3_EL1;
        sYSREG_CODEArray[191] = DBGWVR4_EL1;
        sYSREG_CODEArray[192] = DBGWVR5_EL1;
        sYSREG_CODEArray[193] = DBGWVR6_EL1;
        sYSREG_CODEArray[194] = DBGWVR7_EL1;
        sYSREG_CODEArray[195] = DBGWVR8_EL1;
        sYSREG_CODEArray[196] = DBGWVR9_EL1;
        sYSREG_CODEArray[197] = DBGWVR10_EL1;
        sYSREG_CODEArray[198] = DBGWVR11_EL1;
        sYSREG_CODEArray[199] = DBGWVR12_EL1;
        sYSREG_CODEArray[200] = DBGWVR13_EL1;
        sYSREG_CODEArray[201] = DBGWVR14_EL1;
        sYSREG_CODEArray[202] = DBGWVR15_EL1;
        sYSREG_CODEArray[203] = DBGWCR0_EL1;
        sYSREG_CODEArray[204] = DBGWCR1_EL1;
        sYSREG_CODEArray[205] = DBGWCR2_EL1;
        sYSREG_CODEArray[206] = DBGWCR3_EL1;
        sYSREG_CODEArray[207] = DBGWCR4_EL1;
        sYSREG_CODEArray[208] = DBGWCR5_EL1;
        sYSREG_CODEArray[209] = DBGWCR6_EL1;
        sYSREG_CODEArray[210] = DBGWCR7_EL1;
        sYSREG_CODEArray[211] = DBGWCR8_EL1;
        sYSREG_CODEArray[212] = DBGWCR9_EL1;
        sYSREG_CODEArray[213] = DBGWCR10_EL1;
        sYSREG_CODEArray[214] = DBGWCR11_EL1;
        sYSREG_CODEArray[215] = DBGWCR12_EL1;
        sYSREG_CODEArray[216] = DBGWCR13_EL1;
        sYSREG_CODEArray[217] = DBGWCR14_EL1;
        sYSREG_CODEArray[218] = DBGWCR15_EL1;
        sYSREG_CODEArray[219] = MDRAR_EL1;
        sYSREG_CODEArray[220] = OSLAR_EL1;
        sYSREG_CODEArray[221] = OSLSR_EL1;
        sYSREG_CODEArray[222] = OSDLR_EL1;
        sYSREG_CODEArray[223] = DBGPRCR_EL1;
        sYSREG_CODEArray[224] = DBGCLAIMSET_EL1;
        sYSREG_CODEArray[225] = DBGCLAIMCLR_EL1;
        sYSREG_CODEArray[226] = DBGAUTHSTATUS_EL1;
        sYSREG_CODEArray[227] = PMCR_EL0;
        sYSREG_CODEArray[228] = PMCNTENSET_EL0;
        sYSREG_CODEArray[229] = PMCNTENCLR_EL0;
        sYSREG_CODEArray[230] = PMOVSCLR_EL0;
        sYSREG_CODEArray[231] = PMSWINC_EL0;
        sYSREG_CODEArray[232] = PMSELR_EL0;
        sYSREG_CODEArray[233] = PMCEID0_EL0;
        sYSREG_CODEArray[234] = PMCEID1_EL0;
        sYSREG_CODEArray[235] = PMCCNTR_EL0;
        sYSREG_CODEArray[236] = PMXEVTYPER_EL0;
        sYSREG_CODEArray[237] = PMXEVCNTR_EL0;
        sYSREG_CODEArray[238] = PMUSERENR_EL0;
        sYSREG_CODEArray[239] = PMINTENSET_EL1;
        sYSREG_CODEArray[240] = PMINTENCLR_EL1;
        sYSREG_CODEArray[241] = PMOVSSET_EL0;
        sYSREG_CODEArray[242] = PMEVCNTR0_EL0;
        sYSREG_CODEArray[243] = PMEVCNTR1_EL0;
        sYSREG_CODEArray[244] = PMEVCNTR2_EL0;
        sYSREG_CODEArray[245] = PMEVCNTR3_EL0;
        sYSREG_CODEArray[246] = PMEVCNTR4_EL0;
        sYSREG_CODEArray[247] = PMEVCNTR5_EL0;
        sYSREG_CODEArray[248] = PMEVCNTR6_EL0;
        sYSREG_CODEArray[249] = PMEVCNTR7_EL0;
        sYSREG_CODEArray[250] = PMEVCNTR8_EL0;
        sYSREG_CODEArray[251] = PMEVCNTR9_EL0;
        sYSREG_CODEArray[252] = PMEVCNTR10_EL0;
        sYSREG_CODEArray[253] = PMEVCNTR11_EL0;
        sYSREG_CODEArray[254] = PMEVCNTR12_EL0;
        sYSREG_CODEArray[255] = PMEVCNTR13_EL0;
        sYSREG_CODEArray[256] = PMEVCNTR14_EL0;
        sYSREG_CODEArray[257] = PMEVCNTR15_EL0;
        sYSREG_CODEArray[258] = PMEVCNTR16_EL0;
        sYSREG_CODEArray[259] = PMEVCNTR17_EL0;
        sYSREG_CODEArray[260] = PMEVCNTR18_EL0;
        sYSREG_CODEArray[261] = PMEVCNTR19_EL0;
        sYSREG_CODEArray[262] = PMEVCNTR20_EL0;
        sYSREG_CODEArray[263] = PMEVCNTR21_EL0;
        sYSREG_CODEArray[264] = PMEVCNTR22_EL0;
        sYSREG_CODEArray[265] = PMEVCNTR23_EL0;
        sYSREG_CODEArray[266] = PMEVCNTR24_EL0;
        sYSREG_CODEArray[267] = PMEVCNTR25_EL0;
        sYSREG_CODEArray[268] = PMEVCNTR26_EL0;
        sYSREG_CODEArray[269] = PMEVCNTR27_EL0;
        sYSREG_CODEArray[270] = PMEVCNTR28_EL0;
        sYSREG_CODEArray[271] = PMEVCNTR29_EL0;
        sYSREG_CODEArray[272] = PMEVCNTR30_EL0;
        sYSREG_CODEArray[273] = PMEVTYPER0_EL0;
        sYSREG_CODEArray[274] = PMEVTYPER1_EL0;
        sYSREG_CODEArray[275] = PMEVTYPER2_EL0;
        sYSREG_CODEArray[276] = PMEVTYPER3_EL0;
        sYSREG_CODEArray[277] = PMEVTYPER4_EL0;
        sYSREG_CODEArray[278] = PMEVTYPER5_EL0;
        sYSREG_CODEArray[279] = PMEVTYPER6_EL0;
        sYSREG_CODEArray[280] = PMEVTYPER7_EL0;
        sYSREG_CODEArray[281] = PMEVTYPER8_EL0;
        sYSREG_CODEArray[282] = PMEVTYPER9_EL0;
        sYSREG_CODEArray[283] = PMEVTYPER10_EL0;
        sYSREG_CODEArray[284] = PMEVTYPER11_EL0;
        sYSREG_CODEArray[285] = PMEVTYPER12_EL0;
        sYSREG_CODEArray[286] = PMEVTYPER13_EL0;
        sYSREG_CODEArray[287] = PMEVTYPER14_EL0;
        sYSREG_CODEArray[288] = PMEVTYPER15_EL0;
        sYSREG_CODEArray[289] = PMEVTYPER16_EL0;
        sYSREG_CODEArray[290] = PMEVTYPER17_EL0;
        sYSREG_CODEArray[291] = PMEVTYPER18_EL0;
        sYSREG_CODEArray[292] = PMEVTYPER19_EL0;
        sYSREG_CODEArray[293] = PMEVTYPER20_EL0;
        sYSREG_CODEArray[294] = PMEVTYPER21_EL0;
        sYSREG_CODEArray[295] = PMEVTYPER22_EL0;
        sYSREG_CODEArray[296] = PMEVTYPER23_EL0;
        sYSREG_CODEArray[297] = PMEVTYPER24_EL0;
        sYSREG_CODEArray[298] = PMEVTYPER25_EL0;
        sYSREG_CODEArray[299] = PMEVTYPER26_EL0;
        sYSREG_CODEArray[300] = PMEVTYPER27_EL0;
        sYSREG_CODEArray[301] = PMEVTYPER28_EL0;
        sYSREG_CODEArray[302] = PMEVTYPER29_EL0;
        sYSREG_CODEArray[303] = PMEVTYPER30_EL0;
        sYSREG_CODEArray[304] = PMCCFILTR_EL0;
        sYSREG_CODEArray[305] = SYSREG_MAX;
        $VALUES = sYSREG_CODEArray;
    }

    public static final SYSREG_CODE valueOf(int idx) {
        return SYSREG_CODE.values()[idx];
    }

    public static SYSREG_CODE valueOf(String name) {
        return Enum.valueOf(SYSREG_CODE.class, name);
    }

    public static SYSREG_CODE[] values() {
        return (SYSREG_CODE[])$VALUES.clone();
    }
}

