/*
 * Decompiled with CFR 0.152.
 */
package jnr.a64asm;

import java.util.EnumMap;
import java.util.Map;
import jnr.a64asm.SYSREG_CODE;

public final class SysRegDescription {
    private static final SysRegDescription[] SYSREG_tb;
    private static final Map<SYSREG_CODE, SysRegDescription> sysRegtable;
    final SYSREG_CODE code;
    final int reg_code;

    private static final SysRegDescription MAKE_SYSREGCODE(SYSREG_CODE code, int op0, int op1, int crn, int crm, int op2) {
        SysRegDescription id = new SysRegDescription(code, op0, op1, crn, crm, op2);
        sysRegtable.put(code, id);
        return id;
    }

    SysRegDescription(SYSREG_CODE code, int op0, int op1, int crn, int crm, int op2) {
        this.code = code;
        this.reg_code = (op0 << 19 | op1 << 16 | crn << 12 | crm << 8 | op2 << 5) >> 5;
    }

    /*
     * WARNING - void declaration
     */
    private static final SysRegDescription MAKE_SYSREGCODE(SYSREG_CODE code, int op1, int crm, int op2) {
        void var4_4;
        SysRegDescription id = new SysRegDescription(code, 3, op1, 4, crm, op2);
        sysRegtable.put(code, id);
        return var4_4;
    }

    static {
        sysRegtable = new EnumMap<SYSREG_CODE, SysRegDescription>(SYSREG_CODE.class);
        SysRegDescription[] sysRegDescriptionArray = new SysRegDescription[305];
        sysRegDescriptionArray[0] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_EL1, 0, 0, 0);
        sysRegDescriptionArray[1] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ELR_EL1, 0, 0, 1);
        sysRegDescriptionArray[2] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SP_EL0, 0, 1, 0);
        sysRegDescriptionArray[3] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSEL, 0, 2, 0);
        sysRegDescriptionArray[4] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DAIF, 3, 2, 1);
        sysRegDescriptionArray[5] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CURRENTEL, 0, 2, 2);
        sysRegDescriptionArray[6] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.NZCV, 3, 2, 0);
        sysRegDescriptionArray[7] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.FPCR, 3, 4, 0);
        sysRegDescriptionArray[8] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.FPSR, 3, 4, 1);
        sysRegDescriptionArray[9] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DSPSR_EL0, 3, 5, 0);
        sysRegDescriptionArray[10] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DLR_EL0, 3, 5, 1);
        sysRegDescriptionArray[11] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_EL2, 4, 0, 0);
        sysRegDescriptionArray[12] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ELR_EL2, 4, 0, 1);
        sysRegDescriptionArray[13] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SP_EL1, 4, 1, 0);
        sysRegDescriptionArray[14] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_IRQ, 4, 3, 0);
        sysRegDescriptionArray[15] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_ABT, 4, 3, 1);
        sysRegDescriptionArray[16] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_UND, 4, 3, 2);
        sysRegDescriptionArray[17] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_FIQ, 4, 3, 3);
        sysRegDescriptionArray[18] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_EL3, 6, 0, 0);
        sysRegDescriptionArray[19] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ELR_EL3, 6, 0, 1);
        sysRegDescriptionArray[20] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SP_EL2, 6, 1, 0);
        sysRegDescriptionArray[21] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_SVC, 0, 0, 0);
        sysRegDescriptionArray[22] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SPSR_HYP, 4, 0, 0);
        sysRegDescriptionArray[23] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MIDR_EL1, 3, 0, 0, 0, 0);
        sysRegDescriptionArray[24] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CTR_EL0, 3, 3, 0, 0, 1);
        sysRegDescriptionArray[25] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MPIDR_EL1, 3, 0, 0, 0, 5);
        sysRegDescriptionArray[26] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.REVIDR_EL1, 3, 0, 0, 0, 6);
        sysRegDescriptionArray[27] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AIDR_EL1, 3, 1, 0, 0, 7);
        sysRegDescriptionArray[28] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DCZID_EL0, 3, 3, 0, 0, 7);
        sysRegDescriptionArray[29] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_DFR0_EL1, 3, 0, 0, 1, 2);
        sysRegDescriptionArray[30] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_PFR0_EL1, 3, 0, 0, 1, 0);
        sysRegDescriptionArray[31] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_PFR1_EL1, 3, 0, 0, 1, 1);
        sysRegDescriptionArray[32] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AFR0_EL1, 3, 0, 0, 1, 3);
        sysRegDescriptionArray[33] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_MMFR0_EL1, 3, 0, 0, 1, 4);
        sysRegDescriptionArray[34] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_MMFR1_EL1, 3, 0, 0, 1, 5);
        sysRegDescriptionArray[35] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_MMFR2_EL1, 3, 0, 0, 1, 6);
        sysRegDescriptionArray[36] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_MMFR3_EL1, 3, 0, 0, 1, 7);
        sysRegDescriptionArray[37] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_ISAR0_EL1, 3, 0, 0, 2, 0);
        sysRegDescriptionArray[38] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_ISAR1_EL1, 3, 0, 0, 2, 1);
        sysRegDescriptionArray[39] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_ISAR2_EL1, 3, 0, 0, 2, 2);
        sysRegDescriptionArray[40] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_ISAR3_EL1, 3, 0, 0, 2, 3);
        sysRegDescriptionArray[41] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_ISAR4_EL1, 3, 0, 0, 2, 4);
        sysRegDescriptionArray[42] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_ISAR5_EL1, 3, 0, 0, 2, 5);
        sysRegDescriptionArray[43] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MVFR0_EL1, 3, 0, 0, 3, 0);
        sysRegDescriptionArray[44] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MVFR1_EL1, 3, 0, 0, 3, 1);
        sysRegDescriptionArray[45] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MVFR2_EL1, 3, 0, 0, 3, 2);
        sysRegDescriptionArray[46] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CCSIDR_EL1, 3, 1, 0, 0, 0);
        sysRegDescriptionArray[47] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64PFR0_EL1, 3, 0, 0, 4, 0);
        sysRegDescriptionArray[48] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64PFR1_EL1, 3, 0, 0, 4, 1);
        sysRegDescriptionArray[49] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64DFR0_EL1, 3, 0, 0, 5, 0);
        sysRegDescriptionArray[50] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64DFR1_EL1, 3, 0, 0, 5, 1);
        sysRegDescriptionArray[51] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64ISAR0_EL1, 3, 0, 0, 6, 0);
        sysRegDescriptionArray[52] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64ISAR1_EL1, 3, 0, 0, 6, 1);
        sysRegDescriptionArray[53] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64MMFR0_EL1, 3, 0, 0, 7, 0);
        sysRegDescriptionArray[54] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64MMFR1_EL1, 3, 0, 0, 7, 1);
        sysRegDescriptionArray[55] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64AFR0_EL1, 3, 0, 0, 5, 4);
        sysRegDescriptionArray[56] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ID_AA64AFR1_EL1, 3, 0, 0, 5, 5);
        sysRegDescriptionArray[57] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CLIDR_EL1, 3, 1, 0, 0, 1);
        sysRegDescriptionArray[58] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CSSELR_EL1, 3, 2, 0, 0, 0);
        sysRegDescriptionArray[59] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.VPIDR_EL2, 3, 4, 0, 0, 0);
        sysRegDescriptionArray[60] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.VMPIDR_EL2, 3, 4, 0, 0, 5);
        sysRegDescriptionArray[61] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SCTLR_EL1, 3, 0, 1, 0, 0);
        sysRegDescriptionArray[62] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SCTLR_EL2, 3, 4, 1, 0, 0);
        sysRegDescriptionArray[63] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SCTLR_EL3, 3, 6, 1, 0, 0);
        sysRegDescriptionArray[64] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ACTLR_EL1, 3, 0, 1, 0, 1);
        sysRegDescriptionArray[65] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ACTLR_EL2, 3, 4, 1, 0, 1);
        sysRegDescriptionArray[66] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ACTLR_EL3, 3, 6, 1, 0, 1);
        sysRegDescriptionArray[67] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CPACR_EL1, 3, 0, 1, 0, 2);
        sysRegDescriptionArray[68] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CPTR_EL2, 3, 4, 1, 1, 2);
        sysRegDescriptionArray[69] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CPTR_EL3, 3, 6, 1, 1, 2);
        sysRegDescriptionArray[70] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SCR_EL3, 3, 6, 1, 1, 0);
        sysRegDescriptionArray[71] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.HCR_EL2, 3, 4, 1, 1, 0);
        sysRegDescriptionArray[72] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MDCR_EL2, 3, 4, 1, 1, 1);
        sysRegDescriptionArray[73] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MDCR_EL3, 3, 6, 1, 3, 1);
        sysRegDescriptionArray[74] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.HSTR_EL2, 3, 4, 1, 1, 3);
        sysRegDescriptionArray[75] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.HACR_EL2, 3, 4, 1, 1, 7);
        sysRegDescriptionArray[76] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TTBR0_EL1, 3, 0, 2, 0, 0);
        sysRegDescriptionArray[77] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TTBR1_EL1, 3, 0, 2, 0, 1);
        sysRegDescriptionArray[78] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TTBR0_EL2, 3, 4, 2, 0, 0);
        sysRegDescriptionArray[79] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TTBR0_EL3, 3, 6, 2, 0, 0);
        sysRegDescriptionArray[80] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.VTTBR_EL2, 3, 4, 2, 1, 0);
        sysRegDescriptionArray[81] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TCR_EL1, 3, 0, 2, 0, 2);
        sysRegDescriptionArray[82] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TCR_EL2, 3, 4, 2, 0, 2);
        sysRegDescriptionArray[83] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TCR_EL3, 3, 6, 2, 0, 2);
        sysRegDescriptionArray[84] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.VTCR_EL2, 3, 4, 2, 1, 2);
        sysRegDescriptionArray[85] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AFSR0_EL1, 3, 0, 5, 1, 0);
        sysRegDescriptionArray[86] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AFSR1_EL1, 3, 0, 5, 1, 1);
        sysRegDescriptionArray[87] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AFSR0_EL2, 3, 4, 5, 1, 0);
        sysRegDescriptionArray[88] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AFSR1_EL2, 3, 4, 5, 1, 1);
        sysRegDescriptionArray[89] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AFSR0_EL3, 3, 6, 5, 1, 0);
        sysRegDescriptionArray[90] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AFSR1_EL3, 3, 6, 5, 1, 1);
        sysRegDescriptionArray[91] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ESR_EL1, 3, 0, 5, 2, 0);
        sysRegDescriptionArray[92] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ESR_EL2, 3, 4, 5, 2, 0);
        sysRegDescriptionArray[93] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ESR_EL3, 3, 6, 5, 2, 0);
        sysRegDescriptionArray[94] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.FPEXC32_EL2, 3, 4, 5, 3, 0);
        sysRegDescriptionArray[95] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.FAR_EL1, 3, 0, 6, 0, 0);
        sysRegDescriptionArray[96] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.FAR_EL2, 3, 4, 6, 0, 0);
        sysRegDescriptionArray[97] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.FAR_EL3, 3, 6, 6, 0, 0);
        sysRegDescriptionArray[98] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.HPFAR_EL2, 3, 4, 6, 0, 4);
        sysRegDescriptionArray[99] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PAR_EL1, 3, 0, 7, 4, 0);
        sysRegDescriptionArray[100] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MAIR_EL1, 3, 0, 10, 2, 0);
        sysRegDescriptionArray[101] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MAIR_EL2, 3, 4, 10, 2, 0);
        sysRegDescriptionArray[102] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MAIR_EL3, 3, 6, 10, 2, 0);
        sysRegDescriptionArray[103] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AMAIR_EL1, 3, 0, 10, 3, 0);
        sysRegDescriptionArray[104] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AMAIR_EL2, 3, 4, 10, 3, 0);
        sysRegDescriptionArray[105] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.AMAIR_EL3, 3, 6, 10, 3, 0);
        sysRegDescriptionArray[106] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.VBAR_EL1, 3, 0, 12, 0, 0);
        sysRegDescriptionArray[107] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.VBAR_EL2, 3, 4, 12, 0, 0);
        sysRegDescriptionArray[108] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.VBAR_EL3, 3, 6, 12, 0, 0);
        sysRegDescriptionArray[109] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.RVBAR_EL1, 3, 0, 12, 0, 1);
        sysRegDescriptionArray[110] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.RVBAR_EL2, 3, 4, 12, 0, 1);
        sysRegDescriptionArray[111] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.RVBAR_EL3, 3, 6, 12, 0, 1);
        sysRegDescriptionArray[112] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.RMR_EL1, 3, 0, 12, 0, 2);
        sysRegDescriptionArray[113] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.RMR_EL2, 3, 4, 12, 0, 2);
        sysRegDescriptionArray[114] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.RMR_EL3, 3, 6, 12, 0, 2);
        sysRegDescriptionArray[115] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.ISR_EL1, 3, 0, 12, 1, 0);
        sysRegDescriptionArray[116] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CONTEXTIDR_EL1, 3, 0, 13, 0, 1);
        sysRegDescriptionArray[117] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TPIDR_EL0, 3, 3, 13, 0, 2);
        sysRegDescriptionArray[118] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TPIDRRO_EL0, 3, 3, 13, 0, 3);
        sysRegDescriptionArray[119] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TPIDR_EL1, 3, 0, 13, 0, 4);
        sysRegDescriptionArray[120] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TPIDR_EL2, 3, 4, 13, 0, 2);
        sysRegDescriptionArray[121] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TPIDR_EL3, 3, 6, 13, 0, 2);
        sysRegDescriptionArray[122] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TEECR32_EL1, 2, 2, 0, 0, 0);
        sysRegDescriptionArray[123] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTFRQ_EL0, 3, 3, 14, 0, 0);
        sysRegDescriptionArray[124] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTPCT_EL0, 3, 3, 14, 0, 1);
        sysRegDescriptionArray[125] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTVCT_EL0, 3, 3, 14, 0, 2);
        sysRegDescriptionArray[126] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTVOFF_EL2, 3, 4, 14, 0, 3);
        sysRegDescriptionArray[127] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTKCTL_EL1, 3, 0, 14, 1, 0);
        sysRegDescriptionArray[128] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTHCTL_EL2, 3, 4, 14, 1, 0);
        sysRegDescriptionArray[129] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTP_TVAL_EL0, 3, 3, 14, 2, 0);
        sysRegDescriptionArray[130] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTP_CTL_EL0, 3, 3, 14, 2, 1);
        sysRegDescriptionArray[131] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTP_CVAL_EL0, 3, 3, 14, 2, 2);
        sysRegDescriptionArray[132] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTV_TVAL_EL0, 3, 3, 14, 3, 0);
        sysRegDescriptionArray[133] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTV_CTL_EL0, 3, 3, 14, 3, 1);
        sysRegDescriptionArray[134] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTV_CVAL_EL0, 3, 3, 14, 3, 2);
        sysRegDescriptionArray[135] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTHP_TVAL_EL2, 3, 4, 14, 2, 0);
        sysRegDescriptionArray[136] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTHP_CTL_EL2, 3, 4, 14, 2, 1);
        sysRegDescriptionArray[137] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTHP_CVAL_EL2, 3, 4, 14, 2, 2);
        sysRegDescriptionArray[138] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTPS_TVAL_EL1, 3, 7, 14, 2, 0);
        sysRegDescriptionArray[139] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTPS_CTL_EL1, 3, 7, 14, 2, 1);
        sysRegDescriptionArray[140] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.CNTPS_CVAL_EL1, 3, 7, 14, 2, 2);
        sysRegDescriptionArray[141] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DACR32_EL2, 3, 4, 3, 0, 0);
        sysRegDescriptionArray[142] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.IFSR32_EL2, 3, 4, 5, 0, 1);
        sysRegDescriptionArray[143] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.TEEHBR32_EL1, 2, 2, 1, 0, 0);
        sysRegDescriptionArray[144] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.SDER32_EL3, 3, 6, 1, 1, 1);
        sysRegDescriptionArray[145] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MDSCR_EL1, 2, 0, 0, 2, 2);
        sysRegDescriptionArray[146] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MDCCSR_EL0, 2, 3, 0, 1, 0);
        sysRegDescriptionArray[147] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MDCCINT_EL1, 2, 0, 0, 2, 0);
        sysRegDescriptionArray[148] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGDTR_EL0, 2, 3, 0, 4, 0);
        sysRegDescriptionArray[149] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGDTRRX_EL0, 2, 3, 0, 5, 0);
        sysRegDescriptionArray[150] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGDTRTX_EL0, 2, 3, 0, 5, 0);
        sysRegDescriptionArray[151] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.OSDTRRX_EL1, 2, 0, 0, 0, 2);
        sysRegDescriptionArray[152] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.OSDTRTX_EL1, 2, 0, 0, 3, 2);
        sysRegDescriptionArray[153] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.OSECCR_EL1, 2, 0, 0, 6, 2);
        sysRegDescriptionArray[154] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGVCR32_EL2, 2, 4, 0, 7, 0);
        sysRegDescriptionArray[155] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR0_EL1, 2, 0, 0, 0, 4);
        sysRegDescriptionArray[156] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR1_EL1, 2, 0, 0, 1, 4);
        sysRegDescriptionArray[157] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR2_EL1, 2, 0, 0, 2, 4);
        sysRegDescriptionArray[158] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR3_EL1, 2, 0, 0, 3, 4);
        sysRegDescriptionArray[159] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR4_EL1, 2, 0, 0, 4, 4);
        sysRegDescriptionArray[160] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR5_EL1, 2, 0, 0, 5, 4);
        sysRegDescriptionArray[161] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR6_EL1, 2, 0, 0, 6, 4);
        sysRegDescriptionArray[162] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR7_EL1, 2, 0, 0, 7, 4);
        sysRegDescriptionArray[163] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR8_EL1, 2, 0, 0, 8, 4);
        sysRegDescriptionArray[164] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR9_EL1, 2, 0, 0, 9, 4);
        sysRegDescriptionArray[165] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR10_EL1, 2, 0, 0, 10, 4);
        sysRegDescriptionArray[166] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR11_EL1, 2, 0, 0, 11, 4);
        sysRegDescriptionArray[167] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR12_EL1, 2, 0, 0, 12, 4);
        sysRegDescriptionArray[168] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR13_EL1, 2, 0, 0, 13, 4);
        sysRegDescriptionArray[169] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR14_EL1, 2, 0, 0, 14, 4);
        sysRegDescriptionArray[170] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBVR15_EL1, 2, 0, 0, 15, 4);
        sysRegDescriptionArray[171] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR0_EL1, 2, 0, 0, 0, 5);
        sysRegDescriptionArray[172] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR1_EL1, 2, 0, 0, 1, 5);
        sysRegDescriptionArray[173] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR2_EL1, 2, 0, 0, 2, 5);
        sysRegDescriptionArray[174] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR3_EL1, 2, 0, 0, 3, 5);
        sysRegDescriptionArray[175] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR4_EL1, 2, 0, 0, 4, 5);
        sysRegDescriptionArray[176] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR5_EL1, 2, 0, 0, 5, 5);
        sysRegDescriptionArray[177] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR6_EL1, 2, 0, 0, 6, 5);
        sysRegDescriptionArray[178] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR7_EL1, 2, 0, 0, 7, 5);
        sysRegDescriptionArray[179] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR8_EL1, 2, 0, 0, 8, 5);
        sysRegDescriptionArray[180] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR9_EL1, 2, 0, 0, 9, 5);
        sysRegDescriptionArray[181] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR10_EL1, 2, 0, 0, 10, 5);
        sysRegDescriptionArray[182] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR11_EL1, 2, 0, 0, 11, 5);
        sysRegDescriptionArray[183] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR12_EL1, 2, 0, 0, 12, 5);
        sysRegDescriptionArray[184] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR13_EL1, 2, 0, 0, 13, 5);
        sysRegDescriptionArray[185] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR14_EL1, 2, 0, 0, 14, 5);
        sysRegDescriptionArray[186] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGBCR15_EL1, 2, 0, 0, 15, 5);
        sysRegDescriptionArray[187] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR0_EL1, 2, 0, 0, 0, 6);
        sysRegDescriptionArray[188] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR1_EL1, 2, 0, 0, 1, 6);
        sysRegDescriptionArray[189] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR2_EL1, 2, 0, 0, 2, 6);
        sysRegDescriptionArray[190] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR3_EL1, 2, 0, 0, 3, 6);
        sysRegDescriptionArray[191] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR4_EL1, 2, 0, 0, 4, 6);
        sysRegDescriptionArray[192] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR5_EL1, 2, 0, 0, 5, 6);
        sysRegDescriptionArray[193] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR6_EL1, 2, 0, 0, 6, 6);
        sysRegDescriptionArray[194] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR7_EL1, 2, 0, 0, 7, 6);
        sysRegDescriptionArray[195] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR8_EL1, 2, 0, 0, 8, 6);
        sysRegDescriptionArray[196] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR9_EL1, 2, 0, 0, 9, 6);
        sysRegDescriptionArray[197] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR10_EL1, 2, 0, 0, 10, 6);
        sysRegDescriptionArray[198] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR11_EL1, 2, 0, 0, 11, 6);
        sysRegDescriptionArray[199] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR12_EL1, 2, 0, 0, 12, 6);
        sysRegDescriptionArray[200] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR13_EL1, 2, 0, 0, 13, 6);
        sysRegDescriptionArray[201] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR14_EL1, 2, 0, 0, 14, 6);
        sysRegDescriptionArray[202] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWVR15_EL1, 2, 0, 0, 15, 6);
        sysRegDescriptionArray[203] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR0_EL1, 2, 0, 0, 0, 7);
        sysRegDescriptionArray[204] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR1_EL1, 2, 0, 0, 1, 7);
        sysRegDescriptionArray[205] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR2_EL1, 2, 0, 0, 2, 7);
        sysRegDescriptionArray[206] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR3_EL1, 2, 0, 0, 3, 7);
        sysRegDescriptionArray[207] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR4_EL1, 2, 0, 0, 4, 7);
        sysRegDescriptionArray[208] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR5_EL1, 2, 0, 0, 5, 7);
        sysRegDescriptionArray[209] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR6_EL1, 2, 0, 0, 6, 7);
        sysRegDescriptionArray[210] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR7_EL1, 2, 0, 0, 7, 7);
        sysRegDescriptionArray[211] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR8_EL1, 2, 0, 0, 8, 7);
        sysRegDescriptionArray[212] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR9_EL1, 2, 0, 0, 9, 7);
        sysRegDescriptionArray[213] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR10_EL1, 2, 0, 0, 10, 7);
        sysRegDescriptionArray[214] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR11_EL1, 2, 0, 0, 11, 7);
        sysRegDescriptionArray[215] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR12_EL1, 2, 0, 0, 12, 7);
        sysRegDescriptionArray[216] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR13_EL1, 2, 0, 0, 13, 7);
        sysRegDescriptionArray[217] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR14_EL1, 2, 0, 0, 14, 7);
        sysRegDescriptionArray[218] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGWCR15_EL1, 2, 0, 0, 15, 7);
        sysRegDescriptionArray[219] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.MDRAR_EL1, 2, 0, 1, 0, 0);
        sysRegDescriptionArray[220] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.OSLAR_EL1, 2, 0, 1, 0, 4);
        sysRegDescriptionArray[221] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.OSLSR_EL1, 2, 0, 1, 1, 4);
        sysRegDescriptionArray[222] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.OSDLR_EL1, 2, 0, 1, 3, 4);
        sysRegDescriptionArray[223] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGPRCR_EL1, 2, 0, 1, 4, 4);
        sysRegDescriptionArray[224] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGCLAIMSET_EL1, 2, 0, 7, 8, 6);
        sysRegDescriptionArray[225] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGCLAIMCLR_EL1, 2, 0, 7, 9, 6);
        sysRegDescriptionArray[226] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.DBGAUTHSTATUS_EL1, 2, 0, 7, 14, 6);
        sysRegDescriptionArray[227] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMCR_EL0, 3, 3, 9, 12, 0);
        sysRegDescriptionArray[228] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMCNTENSET_EL0, 3, 3, 9, 12, 1);
        sysRegDescriptionArray[229] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMCNTENCLR_EL0, 3, 3, 9, 12, 2);
        sysRegDescriptionArray[230] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMOVSCLR_EL0, 3, 3, 9, 12, 3);
        sysRegDescriptionArray[231] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMSWINC_EL0, 3, 3, 9, 12, 4);
        sysRegDescriptionArray[232] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMSELR_EL0, 3, 3, 9, 12, 5);
        sysRegDescriptionArray[233] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMCEID0_EL0, 3, 3, 9, 12, 6);
        sysRegDescriptionArray[234] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMCEID1_EL0, 3, 3, 9, 12, 7);
        sysRegDescriptionArray[235] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMCCNTR_EL0, 3, 3, 9, 13, 0);
        sysRegDescriptionArray[236] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMXEVTYPER_EL0, 3, 3, 9, 13, 1);
        sysRegDescriptionArray[237] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMXEVCNTR_EL0, 3, 3, 9, 13, 2);
        sysRegDescriptionArray[238] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMUSERENR_EL0, 3, 3, 9, 14, 0);
        sysRegDescriptionArray[239] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMINTENSET_EL1, 3, 0, 9, 14, 1);
        sysRegDescriptionArray[240] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMINTENCLR_EL1, 3, 0, 9, 14, 2);
        sysRegDescriptionArray[241] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMOVSSET_EL0, 3, 3, 9, 14, 3);
        sysRegDescriptionArray[242] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR0_EL0, 3, 3, 14, 8, 0);
        sysRegDescriptionArray[243] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR1_EL0, 3, 3, 14, 8, 1);
        sysRegDescriptionArray[244] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR2_EL0, 3, 3, 14, 8, 2);
        sysRegDescriptionArray[245] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR3_EL0, 3, 3, 14, 8, 3);
        sysRegDescriptionArray[246] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR4_EL0, 3, 3, 14, 8, 4);
        sysRegDescriptionArray[247] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR5_EL0, 3, 3, 14, 8, 5);
        sysRegDescriptionArray[248] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR6_EL0, 3, 3, 14, 8, 6);
        sysRegDescriptionArray[249] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR7_EL0, 3, 3, 14, 8, 7);
        sysRegDescriptionArray[250] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR8_EL0, 3, 3, 14, 9, 0);
        sysRegDescriptionArray[251] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR9_EL0, 3, 3, 14, 9, 1);
        sysRegDescriptionArray[252] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR10_EL0, 3, 3, 14, 9, 2);
        sysRegDescriptionArray[253] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR11_EL0, 3, 3, 14, 9, 3);
        sysRegDescriptionArray[254] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR12_EL0, 3, 3, 14, 9, 4);
        sysRegDescriptionArray[255] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR13_EL0, 3, 3, 14, 9, 5);
        sysRegDescriptionArray[256] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR14_EL0, 3, 3, 14, 9, 6);
        sysRegDescriptionArray[257] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR15_EL0, 3, 3, 14, 9, 7);
        sysRegDescriptionArray[258] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR16_EL0, 3, 3, 14, 10, 0);
        sysRegDescriptionArray[259] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR17_EL0, 3, 3, 14, 10, 1);
        sysRegDescriptionArray[260] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR18_EL0, 3, 3, 14, 10, 2);
        sysRegDescriptionArray[261] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR19_EL0, 3, 3, 14, 10, 3);
        sysRegDescriptionArray[262] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR20_EL0, 3, 3, 14, 10, 4);
        sysRegDescriptionArray[263] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR21_EL0, 3, 3, 14, 10, 5);
        sysRegDescriptionArray[264] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR22_EL0, 3, 3, 14, 10, 6);
        sysRegDescriptionArray[265] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR23_EL0, 3, 3, 14, 10, 7);
        sysRegDescriptionArray[266] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR24_EL0, 3, 3, 14, 11, 0);
        sysRegDescriptionArray[267] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR25_EL0, 3, 3, 14, 11, 1);
        sysRegDescriptionArray[268] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR26_EL0, 3, 3, 14, 11, 2);
        sysRegDescriptionArray[269] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR27_EL0, 3, 3, 14, 11, 3);
        sysRegDescriptionArray[270] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR28_EL0, 3, 3, 14, 11, 4);
        sysRegDescriptionArray[271] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR29_EL0, 3, 3, 14, 11, 5);
        sysRegDescriptionArray[272] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVCNTR30_EL0, 3, 3, 14, 11, 6);
        sysRegDescriptionArray[273] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER0_EL0, 3, 3, 14, 12, 0);
        sysRegDescriptionArray[274] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER1_EL0, 3, 3, 14, 12, 1);
        sysRegDescriptionArray[275] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER2_EL0, 3, 3, 14, 12, 2);
        sysRegDescriptionArray[276] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER3_EL0, 3, 3, 14, 12, 3);
        sysRegDescriptionArray[277] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER4_EL0, 3, 3, 14, 12, 4);
        sysRegDescriptionArray[278] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER5_EL0, 3, 3, 14, 12, 5);
        sysRegDescriptionArray[279] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER6_EL0, 3, 3, 14, 12, 6);
        sysRegDescriptionArray[280] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER7_EL0, 3, 3, 14, 12, 7);
        sysRegDescriptionArray[281] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER8_EL0, 3, 3, 14, 13, 0);
        sysRegDescriptionArray[282] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER9_EL0, 3, 3, 14, 13, 1);
        sysRegDescriptionArray[283] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER10_EL0, 3, 3, 14, 13, 2);
        sysRegDescriptionArray[284] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER11_EL0, 3, 3, 14, 13, 3);
        sysRegDescriptionArray[285] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER12_EL0, 3, 3, 14, 13, 4);
        sysRegDescriptionArray[286] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER13_EL0, 3, 3, 14, 13, 5);
        sysRegDescriptionArray[287] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER14_EL0, 3, 3, 14, 13, 6);
        sysRegDescriptionArray[288] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER15_EL0, 3, 3, 14, 13, 7);
        sysRegDescriptionArray[289] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER16_EL0, 3, 3, 14, 14, 0);
        sysRegDescriptionArray[290] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER17_EL0, 3, 3, 14, 14, 1);
        sysRegDescriptionArray[291] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER18_EL0, 3, 3, 14, 14, 2);
        sysRegDescriptionArray[292] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER19_EL0, 3, 3, 14, 14, 3);
        sysRegDescriptionArray[293] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER20_EL0, 3, 3, 14, 14, 4);
        sysRegDescriptionArray[294] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER21_EL0, 3, 3, 14, 14, 5);
        sysRegDescriptionArray[295] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER22_EL0, 3, 3, 14, 14, 6);
        sysRegDescriptionArray[296] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER23_EL0, 3, 3, 14, 14, 7);
        sysRegDescriptionArray[297] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER24_EL0, 3, 3, 14, 15, 0);
        sysRegDescriptionArray[298] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER25_EL0, 3, 3, 14, 15, 1);
        sysRegDescriptionArray[299] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER26_EL0, 3, 3, 14, 15, 2);
        sysRegDescriptionArray[300] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER27_EL0, 3, 3, 14, 15, 3);
        sysRegDescriptionArray[301] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER28_EL0, 3, 3, 14, 15, 4);
        sysRegDescriptionArray[302] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER29_EL0, 3, 3, 14, 15, 5);
        sysRegDescriptionArray[303] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMEVTYPER30_EL0, 3, 3, 14, 15, 6);
        sysRegDescriptionArray[304] = SysRegDescription.MAKE_SYSREGCODE(SYSREG_CODE.PMCCFILTR_EL0, 3, 3, 14, 15, 7);
        SYSREG_tb = sysRegDescriptionArray;
    }

    public static final SysRegDescription find(SYSREG_CODE code) {
        SysRegDescription id = sysRegtable.get((Object)code);
        if (id == null) {
            throw new IllegalArgumentException("no description for " + (Object)((Object)code));
        }
        return id;
    }
}

