/*
 * Decompiled with CFR 0.152.
 */
package jnr.constants.platform.fake;

import jnr.constants.Constant;

public final class Errno
extends Enum<Errno>
implements Constant {
    public static final /* enum */ Errno EOPNOTSUPP;
    public static final /* enum */ Errno EDEADLOCK;
    private final long value;
    public static final /* enum */ Errno ENXIO;
    public static final /* enum */ Errno ENOTTY;
    public static final /* enum */ Errno ELOOP;
    public static final /* enum */ Errno ENOANO;
    public static final /* enum */ Errno ENETUNREACH;
    public static final /* enum */ Errno ENOPROTOOPT;
    public static final /* enum */ Errno ELIBMAX;
    public static final /* enum */ Errno EROFS;
    public static final /* enum */ Errno EPROGUNAVAIL;
    public static final /* enum */ Errno EBADMSG;
    public static final /* enum */ Errno EMEDIUMTYPE;
    public static final /* enum */ Errno ENOCSI;
    public static final /* enum */ Errno EBADR;
    public static final /* enum */ Errno ENOTDIR;
    public static final /* enum */ Errno ENAMETOOLONG;
    public static final /* enum */ Errno ENAVAIL;
    public static final /* enum */ Errno EINVAL;
    public static final /* enum */ Errno EMSGSIZE;
    public static final /* enum */ Errno ENODATA;
    public static final /* enum */ Errno EPROGMISMATCH;
    public static final /* enum */ Errno EREMOTE;
    public static final /* enum */ Errno EACCES;
    public static final /* enum */ Errno EPFNOSUPPORT;
    public static final /* enum */ Errno ENOSYS;
    public static final /* enum */ Errno EISNAM;
    public static final /* enum */ Errno ENOSTR;
    public static final /* enum */ Errno ESOCKTNOSUPPORT;
    public static final /* enum */ Errno ESPIPE;
    public static final /* enum */ Errno ENOLCK;
    public static final /* enum */ Errno EAGAIN;
    public static final /* enum */ Errno ELNRNG;
    public static final /* enum */ Errno EPIPE;
    public static final /* enum */ Errno EDOM;
    public static final /* enum */ Errno EBADRQC;
    public static final /* enum */ Errno EBADE;
    public static final long MAX_VALUE = 148L;
    public static final /* enum */ Errno ENOENT;
    public static final /* enum */ Errno ECANCELED;
    public static final /* enum */ Errno ELIBSCN;
    public static final /* enum */ Errno ENOLINK;
    public static final /* enum */ Errno EUNATCH;
    public static final /* enum */ Errno EDEADLK;
    public static final /* enum */ Errno EBFONT;
    public static final /* enum */ Errno EKEYREJECTED;
    public static final /* enum */ Errno EREMOTEIO;
    public static final /* enum */ Errno ENOSPC;
    public static final /* enum */ Errno ECONNREFUSED;
    public static final /* enum */ Errno EEXIST;
    public static final /* enum */ Errno EL2HLT;
    public static final /* enum */ Errno ENOTRECOVERABLE;
    public static final /* enum */ Errno ENEEDAUTH;
    public static final /* enum */ Errno EPROTOTYPE;
    public static final /* enum */ Errno EADV;
    public static final long MIN_VALUE = 1L;
    public static final /* enum */ Errno EUCLEAN;
    public static final /* enum */ Errno EBUSY;
    public static final /* enum */ Errno EHWPOISON;
    public static final /* enum */ Errno ESRCH;
    public static final /* enum */ Errno EISCONN;
    private static final /* synthetic */ Errno[] $VALUES;
    public static final /* enum */ Errno ENOTCONN;
    public static final /* enum */ Errno EMFILE;
    public static final /* enum */ Errno ENOEXEC;
    public static final /* enum */ Errno EL3RST;
    public static final /* enum */ Errno EPERM;
    public static final /* enum */ Errno EAUTH;
    public static final /* enum */ Errno ESRMNT;
    public static final /* enum */ Errno ENOMEM;
    public static final /* enum */ Errno EIO;
    public static final /* enum */ Errno ENFILE;
    public static final /* enum */ Errno ELIBBAD;
    public static final /* enum */ Errno ENETRESET;
    public static final /* enum */ Errno EOVERFLOW;
    public static final /* enum */ Errno EINTR;
    public static final /* enum */ Errno EPROCUNAVAIL;
    public static final /* enum */ Errno ENOTCAPABLE;
    public static final /* enum */ Errno ECHRNG;
    public static final /* enum */ Errno ENOATTR;
    public static final /* enum */ Errno EPROTONOSUPPORT;
    public static final /* enum */ Errno ETIME;
    public static final /* enum */ Errno EIDRM;
    public static final /* enum */ Errno ECAPMODE;
    public static final /* enum */ Errno EBADFD;
    public static final /* enum */ Errno ENOPKG;
    public static final /* enum */ Errno ERFKILL;
    public static final /* enum */ Errno EDOOFUS;
    public static final /* enum */ Errno EBADRPC;
    public static final /* enum */ Errno ENOTSOCK;
    public static final /* enum */ Errno EDQUOT;
    public static final /* enum */ Errno EINPROGRESS;
    public static final /* enum */ Errno ESTALE;
    public static final /* enum */ Errno ERANGE;
    public static final /* enum */ Errno ELIBEXEC;
    public static final /* enum */ Errno ENOKEY;
    public static final /* enum */ Errno ENOMSG;
    public static final /* enum */ Errno ENOTEMPTY;
    public static final /* enum */ Errno ENONET;
    public static final /* enum */ Errno EALREADY;
    public static final /* enum */ Errno ENOTUNIQ;
    public static final /* enum */ Errno ETIMEDOUT;
    public static final /* enum */ Errno EBADF;
    public static final /* enum */ Errno ERESTART;
    public static final /* enum */ Errno ECHILD;
    public static final /* enum */ Errno ENOSR;
    public static final /* enum */ Errno ENOTBLK;
    public static final /* enum */ Errno ESHUTDOWN;
    public static final /* enum */ Errno EDESTADDRREQ;
    public static final /* enum */ Errno EFTYPE;
    public static final /* enum */ Errno EXDEV;
    public static final /* enum */ Errno EKEYREVOKED;
    public static final /* enum */ Errno ECONNABORTED;
    public static final /* enum */ Errno ENOTNAM;
    public static final /* enum */ Errno EDOTDOT;
    public static final /* enum */ Errno EPROCLIM;
    public static final /* enum */ Errno ETXTBSY;
    public static final /* enum */ Errno ENOTSUP;
    public static final /* enum */ Errno ECOMM;
    public static final /* enum */ Errno EILSEQ;
    public static final /* enum */ Errno EIPSEC;
    public static final /* enum */ Errno ENOBUFS;
    public static final /* enum */ Errno EMLINK;
    public static final /* enum */ Errno ENETDOWN;
    public static final /* enum */ Errno EL3HLT;
    public static final /* enum */ Errno EADDRNOTAVAIL;
    public static final /* enum */ Errno ENODEV;
    public static final /* enum */ Errno E2BIG;
    public static final /* enum */ Errno EUSERS;
    public static final /* enum */ Errno ELIBACC;
    public static final /* enum */ Errno ESTRPIPE;
    public static final /* enum */ Errno EWOULDBLOCK;
    public static final /* enum */ Errno EAFNOSUPPORT;
    public static final /* enum */ Errno EISDIR;
    public static final /* enum */ Errno ECONNRESET;
    public static final /* enum */ Errno ERPCMISMATCH;
    public static final /* enum */ Errno EXFULL;
    public static final /* enum */ Errno EREMCHG;
    public static final /* enum */ Errno EL2NSYNC;
    public static final /* enum */ Errno EMULTIHOP;
    public static final /* enum */ Errno EBADSLT;
    public static final /* enum */ Errno EKEYEXPIRED;
    public static final /* enum */ Errno EHOSTDOWN;
    public static final /* enum */ Errno ENOMEDIUM;
    public static final /* enum */ Errno ETOOMANYREFS;
    public static final /* enum */ Errno EFAULT;
    public static final /* enum */ Errno EFBIG;
    public static final /* enum */ Errno EPROTO;
    public static final /* enum */ Errno EOWNERDEAD;
    public static final /* enum */ Errno EADDRINUSE;
    public static final /* enum */ Errno EHOSTUNREACH;

    static {
        EPERM = new Errno(1L);
        ENOENT = new Errno(2L);
        ESRCH = new Errno(3L);
        EINTR = new Errno(4L);
        EIO = new Errno(5L);
        ENXIO = new Errno(6L);
        E2BIG = new Errno(7L);
        ENOEXEC = new Errno(8L);
        EBADF = new Errno(9L);
        ECHILD = new Errno(10L);
        EDEADLK = new Errno(11L);
        ENOMEM = new Errno(12L);
        EACCES = new Errno(13L);
        EFAULT = new Errno(14L);
        ENOTBLK = new Errno(15L);
        EBUSY = new Errno(16L);
        EEXIST = new Errno(17L);
        EXDEV = new Errno(18L);
        ENODEV = new Errno(19L);
        ENOTDIR = new Errno(20L);
        EISDIR = new Errno(21L);
        EINVAL = new Errno(22L);
        ENFILE = new Errno(23L);
        EMFILE = new Errno(24L);
        ENOTTY = new Errno(25L);
        ETXTBSY = new Errno(26L);
        EFBIG = new Errno(27L);
        ENOSPC = new Errno(28L);
        ESPIPE = new Errno(29L);
        EROFS = new Errno(30L);
        EMLINK = new Errno(31L);
        EPIPE = new Errno(32L);
        EDOM = new Errno(33L);
        ERANGE = new Errno(34L);
        EWOULDBLOCK = new Errno(35L);
        EAGAIN = new Errno(36L);
        EINPROGRESS = new Errno(37L);
        EALREADY = new Errno(38L);
        ENOTSOCK = new Errno(39L);
        EDESTADDRREQ = new Errno(40L);
        EMSGSIZE = new Errno(41L);
        EPROTOTYPE = new Errno(42L);
        ENOPROTOOPT = new Errno(43L);
        EPROTONOSUPPORT = new Errno(44L);
        ESOCKTNOSUPPORT = new Errno(45L);
        EOPNOTSUPP = new Errno(46L);
        EPFNOSUPPORT = new Errno(47L);
        EAFNOSUPPORT = new Errno(48L);
        EADDRINUSE = new Errno(49L);
        EADDRNOTAVAIL = new Errno(50L);
        ENETDOWN = new Errno(51L);
        ENETUNREACH = new Errno(52L);
        ENETRESET = new Errno(53L);
        ECONNABORTED = new Errno(54L);
        ECONNRESET = new Errno(55L);
        ENOBUFS = new Errno(56L);
        EISCONN = new Errno(57L);
        ENOTCONN = new Errno(58L);
        ESHUTDOWN = new Errno(59L);
        ETOOMANYREFS = new Errno(60L);
        ETIMEDOUT = new Errno(61L);
        ECONNREFUSED = new Errno(62L);
        ELOOP = new Errno(63L);
        ENAMETOOLONG = new Errno(64L);
        EHOSTDOWN = new Errno(65L);
        EHOSTUNREACH = new Errno(66L);
        ENOTEMPTY = new Errno(67L);
        EUSERS = new Errno(68L);
        EDQUOT = new Errno(69L);
        ESTALE = new Errno(70L);
        EREMOTE = new Errno(71L);
        ENOLCK = new Errno(72L);
        ENOSYS = new Errno(73L);
        EOVERFLOW = new Errno(74L);
        EIDRM = new Errno(75L);
        ENOMSG = new Errno(76L);
        EILSEQ = new Errno(77L);
        EBADMSG = new Errno(78L);
        EMULTIHOP = new Errno(79L);
        ENODATA = new Errno(80L);
        ENOLINK = new Errno(81L);
        ENOSR = new Errno(82L);
        ENOSTR = new Errno(83L);
        EPROTO = new Errno(84L);
        ETIME = new Errno(85L);
        ECHRNG = new Errno(86L);
        EL2NSYNC = new Errno(87L);
        EL3HLT = new Errno(88L);
        EL3RST = new Errno(89L);
        ELNRNG = new Errno(90L);
        EUNATCH = new Errno(91L);
        ENOCSI = new Errno(92L);
        EL2HLT = new Errno(93L);
        EBADE = new Errno(94L);
        EBADR = new Errno(95L);
        EXFULL = new Errno(96L);
        ENOANO = new Errno(97L);
        EBADRQC = new Errno(98L);
        EBADSLT = new Errno(99L);
        EDEADLOCK = new Errno(100L);
        EBFONT = new Errno(101L);
        ENONET = new Errno(102L);
        ENOPKG = new Errno(103L);
        EADV = new Errno(104L);
        ESRMNT = new Errno(105L);
        ECOMM = new Errno(106L);
        EDOTDOT = new Errno(107L);
        ENOTUNIQ = new Errno(108L);
        EBADFD = new Errno(109L);
        EREMCHG = new Errno(110L);
        ELIBACC = new Errno(111L);
        ELIBBAD = new Errno(112L);
        ELIBSCN = new Errno(113L);
        ELIBMAX = new Errno(114L);
        ELIBEXEC = new Errno(115L);
        ERESTART = new Errno(116L);
        ESTRPIPE = new Errno(117L);
        EUCLEAN = new Errno(118L);
        ENOTNAM = new Errno(119L);
        ENAVAIL = new Errno(120L);
        EISNAM = new Errno(121L);
        EREMOTEIO = new Errno(122L);
        ECANCELED = new Errno(123L);
        EKEYEXPIRED = new Errno(124L);
        EKEYREJECTED = new Errno(125L);
        EKEYREVOKED = new Errno(126L);
        EMEDIUMTYPE = new Errno(127L);
        ENOKEY = new Errno(128L);
        ENOMEDIUM = new Errno(129L);
        ENOTRECOVERABLE = new Errno(130L);
        EOWNERDEAD = new Errno(131L);
        ERFKILL = new Errno(132L);
        EAUTH = new Errno(133L);
        EBADRPC = new Errno(134L);
        EDOOFUS = new Errno(135L);
        EFTYPE = new Errno(136L);
        ENEEDAUTH = new Errno(137L);
        ENOATTR = new Errno(138L);
        ENOTSUP = new Errno(139L);
        EPROCLIM = new Errno(140L);
        EPROCUNAVAIL = new Errno(141L);
        EPROGMISMATCH = new Errno(142L);
        EPROGUNAVAIL = new Errno(143L);
        ERPCMISMATCH = new Errno(144L);
        EIPSEC = new Errno(145L);
        EHWPOISON = new Errno(146L);
        ECAPMODE = new Errno(147L);
        ENOTCAPABLE = new Errno(148L);
        Errno[] errnoArray = new Errno[148];
        errnoArray[0] = EPERM;
        errnoArray[1] = ENOENT;
        errnoArray[2] = ESRCH;
        errnoArray[3] = EINTR;
        errnoArray[4] = EIO;
        errnoArray[5] = ENXIO;
        errnoArray[6] = E2BIG;
        errnoArray[7] = ENOEXEC;
        errnoArray[8] = EBADF;
        errnoArray[9] = ECHILD;
        errnoArray[10] = EDEADLK;
        errnoArray[11] = ENOMEM;
        errnoArray[12] = EACCES;
        errnoArray[13] = EFAULT;
        errnoArray[14] = ENOTBLK;
        errnoArray[15] = EBUSY;
        errnoArray[16] = EEXIST;
        errnoArray[17] = EXDEV;
        errnoArray[18] = ENODEV;
        errnoArray[19] = ENOTDIR;
        errnoArray[20] = EISDIR;
        errnoArray[21] = EINVAL;
        errnoArray[22] = ENFILE;
        errnoArray[23] = EMFILE;
        errnoArray[24] = ENOTTY;
        errnoArray[25] = ETXTBSY;
        errnoArray[26] = EFBIG;
        errnoArray[27] = ENOSPC;
        errnoArray[28] = ESPIPE;
        errnoArray[29] = EROFS;
        errnoArray[30] = EMLINK;
        errnoArray[31] = EPIPE;
        errnoArray[32] = EDOM;
        errnoArray[33] = ERANGE;
        errnoArray[34] = EWOULDBLOCK;
        errnoArray[35] = EAGAIN;
        errnoArray[36] = EINPROGRESS;
        errnoArray[37] = EALREADY;
        errnoArray[38] = ENOTSOCK;
        errnoArray[39] = EDESTADDRREQ;
        errnoArray[40] = EMSGSIZE;
        errnoArray[41] = EPROTOTYPE;
        errnoArray[42] = ENOPROTOOPT;
        errnoArray[43] = EPROTONOSUPPORT;
        errnoArray[44] = ESOCKTNOSUPPORT;
        errnoArray[45] = EOPNOTSUPP;
        errnoArray[46] = EPFNOSUPPORT;
        errnoArray[47] = EAFNOSUPPORT;
        errnoArray[48] = EADDRINUSE;
        errnoArray[49] = EADDRNOTAVAIL;
        errnoArray[50] = ENETDOWN;
        errnoArray[51] = ENETUNREACH;
        errnoArray[52] = ENETRESET;
        errnoArray[53] = ECONNABORTED;
        errnoArray[54] = ECONNRESET;
        errnoArray[55] = ENOBUFS;
        errnoArray[56] = EISCONN;
        errnoArray[57] = ENOTCONN;
        errnoArray[58] = ESHUTDOWN;
        errnoArray[59] = ETOOMANYREFS;
        errnoArray[60] = ETIMEDOUT;
        errnoArray[61] = ECONNREFUSED;
        errnoArray[62] = ELOOP;
        errnoArray[63] = ENAMETOOLONG;
        errnoArray[64] = EHOSTDOWN;
        errnoArray[65] = EHOSTUNREACH;
        errnoArray[66] = ENOTEMPTY;
        errnoArray[67] = EUSERS;
        errnoArray[68] = EDQUOT;
        errnoArray[69] = ESTALE;
        errnoArray[70] = EREMOTE;
        errnoArray[71] = ENOLCK;
        errnoArray[72] = ENOSYS;
        errnoArray[73] = EOVERFLOW;
        errnoArray[74] = EIDRM;
        errnoArray[75] = ENOMSG;
        errnoArray[76] = EILSEQ;
        errnoArray[77] = EBADMSG;
        errnoArray[78] = EMULTIHOP;
        errnoArray[79] = ENODATA;
        errnoArray[80] = ENOLINK;
        errnoArray[81] = ENOSR;
        errnoArray[82] = ENOSTR;
        errnoArray[83] = EPROTO;
        errnoArray[84] = ETIME;
        errnoArray[85] = ECHRNG;
        errnoArray[86] = EL2NSYNC;
        errnoArray[87] = EL3HLT;
        errnoArray[88] = EL3RST;
        errnoArray[89] = ELNRNG;
        errnoArray[90] = EUNATCH;
        errnoArray[91] = ENOCSI;
        errnoArray[92] = EL2HLT;
        errnoArray[93] = EBADE;
        errnoArray[94] = EBADR;
        errnoArray[95] = EXFULL;
        errnoArray[96] = ENOANO;
        errnoArray[97] = EBADRQC;
        errnoArray[98] = EBADSLT;
        errnoArray[99] = EDEADLOCK;
        errnoArray[100] = EBFONT;
        errnoArray[101] = ENONET;
        errnoArray[102] = ENOPKG;
        errnoArray[103] = EADV;
        errnoArray[104] = ESRMNT;
        errnoArray[105] = ECOMM;
        errnoArray[106] = EDOTDOT;
        errnoArray[107] = ENOTUNIQ;
        errnoArray[108] = EBADFD;
        errnoArray[109] = EREMCHG;
        errnoArray[110] = ELIBACC;
        errnoArray[111] = ELIBBAD;
        errnoArray[112] = ELIBSCN;
        errnoArray[113] = ELIBMAX;
        errnoArray[114] = ELIBEXEC;
        errnoArray[115] = ERESTART;
        errnoArray[116] = ESTRPIPE;
        errnoArray[117] = EUCLEAN;
        errnoArray[118] = ENOTNAM;
        errnoArray[119] = ENAVAIL;
        errnoArray[120] = EISNAM;
        errnoArray[121] = EREMOTEIO;
        errnoArray[122] = ECANCELED;
        errnoArray[123] = EKEYEXPIRED;
        errnoArray[124] = EKEYREJECTED;
        errnoArray[125] = EKEYREVOKED;
        errnoArray[126] = EMEDIUMTYPE;
        errnoArray[127] = ENOKEY;
        errnoArray[128] = ENOMEDIUM;
        errnoArray[129] = ENOTRECOVERABLE;
        errnoArray[130] = EOWNERDEAD;
        errnoArray[131] = ERFKILL;
        errnoArray[132] = EAUTH;
        errnoArray[133] = EBADRPC;
        errnoArray[134] = EDOOFUS;
        errnoArray[135] = EFTYPE;
        errnoArray[136] = ENEEDAUTH;
        errnoArray[137] = ENOATTR;
        errnoArray[138] = ENOTSUP;
        errnoArray[139] = EPROCLIM;
        errnoArray[140] = EPROCUNAVAIL;
        errnoArray[141] = EPROGMISMATCH;
        errnoArray[142] = EPROGUNAVAIL;
        errnoArray[143] = ERPCMISMATCH;
        errnoArray[144] = EIPSEC;
        errnoArray[145] = EHWPOISON;
        errnoArray[146] = ECAPMODE;
        errnoArray[147] = ENOTCAPABLE;
        $VALUES = errnoArray;
    }

    private Errno(long value) {
        this.value = value;
    }

    @Override
    public final int intValue() {
        return (int)this.value;
    }

    public final int value() {
        return (int)this.value;
    }

    @Override
    public final boolean defined() {
        return true;
    }

    public static Errno[] values() {
        return (Errno[])$VALUES.clone();
    }

    public static Errno valueOf(String name) {
        return Enum.valueOf(Errno.class, name);
    }

    @Override
    public final long longValue() {
        return this.value;
    }
}

