# This is the default config file for Lithium.
# This file should not be modified manually. Edit the .properties file in the config folder in the .minecraft folder instead!
#
mixin.ai=true
mixin.ai.non_poi_block_search=true
mixin.ai.pathing=true
mixin.ai.poi=true
mixin.ai.poi.fast_portals=true
mixin.ai.poi.tasks=true
mixin.ai.raid=true
mixin.ai.sensor=true
mixin.ai.sensor.replace_streams=true
mixin.ai.sensor.replace_streams.tempting=true
mixin.ai.sensor.secondary_poi=true
mixin.ai.task=true
mixin.ai.task.launch=true
mixin.ai.task.memory_change_counting=true
mixin.ai.task.replace_streams=true
mixin.ai.task.run=true
mixin.ai.task.run.long_jump_weighted_choice=true
mixin.ai.useless_behaviors=true
mixin.ai.useless_behaviors.nitwit_job_search=true
mixin.ai.useless_sensors=true
mixin.ai.useless_sensors.goat_item_sensor=true
mixin.ai.useless_sensors.parent_animal_sensor=true
mixin.alloc=true
mixin.alloc.chunk_random=true
mixin.alloc.composter=true
mixin.alloc.deep_passengers=true
mixin.alloc.entity_iteration=true
mixin.alloc.entity_tracker=true
mixin.alloc.enum_values=true
mixin.alloc.enum_values.piston_block=true
mixin.alloc.enum_values.piston_handler=true
mixin.alloc.enum_values.redstone_wire=true
mixin.alloc.explosion_behavior=true
mixin.alloc.nbt=true
mixin.block=true
mixin.block.flatten_states=true
mixin.block.fluid=true
mixin.block.fluid.flow=true
mixin.block.hopper=true
mixin.block.moving_block_shapes=true
mixin.block.redstone_wire=true
mixin.block_pattern_matching=true
mixin.cached_hashcode=true
mixin.chunk=true
mixin.chunk.entity_class_groups=true
mixin.chunk.no_locking=true
mixin.chunk.no_validation=true
mixin.chunk.palette=true
mixin.chunk.serialization=true
mixin.collections=true
mixin.collections.attributes=true
mixin.collections.block_entity_tickers=true
mixin.collections.brain=true
mixin.collections.chunk_tickets=true
mixin.collections.entity_by_type=true
mixin.collections.entity_filtering=true
mixin.collections.entity_ticking=true
mixin.collections.fluid_submersion=true
mixin.collections.mob_spawning=true
mixin.collections.poi_types=true
mixin.compat.worldedit=false
mixin.debug=false
mixin.debug.palette=true
mixin.entity=true
mixin.entity.collisions=true
mixin.entity.collisions.block_effects=true
mixin.entity.collisions.fluid=true
mixin.entity.collisions.intersection=true
mixin.entity.collisions.movement=true
mixin.entity.collisions.unpushable_cramming=true
mixin.entity.equipment_tracking=true
mixin.entity.equipment_tracking.enchantment_ticking=true
mixin.entity.equipment_tracking.equipment_changes=true
mixin.entity.fast_elytra_check=true
mixin.entity.fast_hand_swing=true
mixin.entity.fast_powder_snow_check=true
mixin.entity.fast_retrieval=true
mixin.entity.framed_maps=true
mixin.entity.inactive_navigations=true
mixin.entity.projectile_projectile_collisions=true
mixin.entity.replace_entitytype_predicates=true
mixin.entity.sprinting_particles=true
mixin.experimental=false
mixin.experimental.client_tick=true
mixin.experimental.client_tick.entity=true
mixin.experimental.client_tick.entity.base_tick=true
mixin.experimental.client_tick.entity.base_tick.unused_ambient_sound=true
mixin.experimental.client_tick.entity.base_tick.unused_water_supply=true
mixin.experimental.client_tick.entity.unused_brain=true
mixin.experimental.client_tick.particle=true
mixin.experimental.client_tick.particle.biome_particles=true
mixin.experimental.entity=true
mixin.experimental.entity.block_caching=true
mixin.experimental.entity.block_caching.block_support=true
mixin.experimental.entity.block_caching.fluid_pushing=true
mixin.experimental.entity.block_caching.suffocation=true
mixin.experimental.entity.item_entity_merging=true
mixin.gen=true
mixin.gen.cached_generator_settings=true
mixin.math=true
mixin.math.fast_blockpos=true
mixin.math.fast_util=true
mixin.math.sine_lut=true
mixin.minimal_nonvanilla=true
mixin.minimal_nonvanilla.ai=true
mixin.minimal_nonvanilla.ai.sensor=true
mixin.minimal_nonvanilla.ai.sensor.frog_attackables=true
mixin.minimal_nonvanilla.collisions=true
mixin.minimal_nonvanilla.collisions.empty_space=true
mixin.minimal_nonvanilla.spawning=true
mixin.minimal_nonvanilla.world=true
mixin.minimal_nonvanilla.world.block_entity_ticking=true
mixin.minimal_nonvanilla.world.block_entity_ticking.support_cache=true
mixin.minimal_nonvanilla.world.expiring_chunk_tickets=true
mixin.shapes=true
mixin.shapes.blockstate_cache=true
mixin.shapes.lazy_shape_context=true
mixin.shapes.optimized_matching=true
mixin.shapes.precompute_shape_arrays=true
mixin.shapes.shape_merging=true
mixin.shapes.specialized_shapes=true
mixin.util=true
mixin.util.accessors=true
mixin.util.block_entity_retrieval=true
mixin.util.block_tracking=true
mixin.util.chunk_access=true
mixin.util.chunk_status_tracking=true
mixin.util.data_storage=true
mixin.util.entity_collection_replacement=true
mixin.util.entity_movement_tracking=true
mixin.util.entity_section_position=true
mixin.util.in_world_tracking=true
mixin.util.in_world_tracking.entity=true
mixin.util.initialization=true
mixin.util.inventory_change_listening=true
mixin.util.inventory_comparator_tracking=true
mixin.util.item_component_and_count_tracking=true
mixin.util.section_data_storage=true
mixin.util.world_border_listener=true
mixin.world=true
mixin.world.block_entity_ticking=true
mixin.world.block_entity_ticking.chunk_tickable=true
mixin.world.block_entity_ticking.sleeping=true
mixin.world.block_entity_ticking.sleeping.brewing_stand=true
mixin.world.block_entity_ticking.sleeping.campfire=true
mixin.world.block_entity_ticking.sleeping.campfire.lit=true
mixin.world.block_entity_ticking.sleeping.campfire.unlit=true
mixin.world.block_entity_ticking.sleeping.chest_animation=true
mixin.world.block_entity_ticking.sleeping.crafter=true
mixin.world.block_entity_ticking.sleeping.furnace=true
mixin.world.block_entity_ticking.sleeping.hopper=true
mixin.world.block_entity_ticking.sleeping.sculk_catalyst=true
mixin.world.block_entity_ticking.sleeping.sculk_sensor_shrieker=true
mixin.world.block_entity_ticking.sleeping.shulker_box=true
mixin.world.block_entity_ticking.world_border=true
mixin.world.chunk_access=true
mixin.world.chunk_ticking=true
mixin.world.chunk_ticking.precipitation=true
mixin.world.chunk_ticking.random_block_ticking=true
mixin.world.chunk_ticking.spread_ice=true
mixin.world.combined_heightmap_update=true
mixin.world.explosions=true
mixin.world.explosions.block_raycast=true
mixin.world.explosions.entity_raycast=true
mixin.world.game_events=true
mixin.world.game_events.dispatch=true
mixin.world.inline_block_access=true
mixin.world.inline_height=true
mixin.world.raycast=true
mixin.world.temperature_cache=true
mixin.world.tick_scheduler=true
