# This is the config dependency file for Lithium.
# This file should not be modified!
#
mixin.ai.pathing=mixin.util.chunk_access:true,mixin.util.initialization:true
mixin.ai.raid=mixin.util.data_storage:true
mixin.block.hopper=mixin.util.entity_movement_tracking:true,mixin.util.block_entity_retrieval:true,mixin.util.inventory_change_listening:true,mixin.util.item_component_and_count_tracking:true
mixin.chunk.entity_class_groups=mixin.util.accessors:true
mixin.compat.worldedit=mixin.util.block_entity_retrieval:true
mixin.entity.collisions.fluid=mixin.util.block_tracking:true,mixin.experimental.entity.block_caching.fluid_pushing:false
mixin.entity.collisions.intersection=mixin.util.chunk_access:true
mixin.entity.collisions.movement=mixin.util.chunk_access:true
mixin.entity.collisions.unpushable_cramming=mixin.chunk.entity_class_groups:true
mixin.entity.equipment_tracking=mixin.util.item_component_and_count_tracking:true,mixin.util.in_world_tracking.entity:true
mixin.entity.inactive_navigations=mixin.util.data_storage:true
mixin.entity.projectile_projectile_collisions=mixin.chunk.entity_class_groups:true
mixin.experimental.entity.block_caching=mixin.util.block_tracking:true
mixin.experimental.entity.block_caching.block_support=mixin.util.block_tracking:true
mixin.experimental.entity.block_caching.fluid_pushing=mixin.util.block_tracking:true
mixin.experimental.entity.block_caching.suffocation=mixin.util.block_tracking:true
mixin.experimental.entity.item_entity_merging=mixin.util.accessors:true,mixin.util.entity_collection_replacement:true,mixin.util.item_component_and_count_tracking:true
mixin.minimal_nonvanilla.world.block_entity_ticking.support_cache=mixin.world.block_entity_ticking:true
mixin.util.block_tracking=mixin.util.data_storage:true,mixin.util.chunk_status_tracking:true,mixin.util.initialization:true,mixin.util.section_data_storage:true
mixin.util.chunk_status_tracking=mixin.util.accessors:true
mixin.util.entity_movement_tracking=mixin.util.entity_section_position:true,mixin.util.data_storage:true
mixin.util.inventory_comparator_tracking=mixin.util.block_entity_retrieval:true
mixin.world.block_entity_ticking.world_border=mixin.util.world_border_listener:true
mixin.world.chunk_ticking.random_block_ticking=mixin.util.section_data_storage:true
mixin.world.game_events.dispatch=mixin.util.data_storage:true,mixin.util.chunk_status_tracking:true
