/*
 * Decompiled with CFR 0.152.
 */
package jnr.constants.platform.solaris;

import java.util.EnumMap;
import java.util.Map;
import jnr.constants.Constant;

public final class Errno
extends Enum<Errno>
implements Constant {
    public static final /* enum */ Errno ELIBSCN;
    public static final /* enum */ Errno ENETRESET;
    public static final /* enum */ Errno ENETDOWN;
    public static final /* enum */ Errno ENOTSUP;
    public static final /* enum */ Errno EINVAL;
    public static final /* enum */ Errno ENOTCONN;
    public static final /* enum */ Errno EUSERS;
    public static final /* enum */ Errno EREMCHG;
    public static final /* enum */ Errno EBADMSG;
    public static final /* enum */ Errno EOPNOTSUPP;
    public static final /* enum */ Errno EEXIST;
    public static final /* enum */ Errno ENODATA;
    public static final /* enum */ Errno EPROTOTYPE;
    public static final /* enum */ Errno ENOMEM;
    public static final /* enum */ Errno ENOSPC;
    public static final /* enum */ Errno EL2NSYNC;
    public static final /* enum */ Errno EBFONT;
    public static final /* enum */ Errno ENOPKG;
    public static final /* enum */ Errno EADDRNOTAVAIL;
    public static final /* enum */ Errno ENOTSOCK;
    public static final /* enum */ Errno ENOTBLK;
    public static final /* enum */ Errno E2BIG;
    public static final /* enum */ Errno ETOOMANYREFS;
    public static final /* enum */ Errno ESTRPIPE;
    public static final /* enum */ Errno ESRMNT;
    public static final /* enum */ Errno EDESTADDRREQ;
    public static final /* enum */ Errno ENOENT;
    public static final /* enum */ Errno ENOEXEC;
    public static final /* enum */ Errno ECONNABORTED;
    public static final /* enum */ Errno ETIMEDOUT;
    public static final /* enum */ Errno EBUSY;
    public static final /* enum */ Errno ESOCKTNOSUPPORT;
    public static final /* enum */ Errno ENAMETOOLONG;
    public static final /* enum */ Errno EINTR;
    public static final /* enum */ Errno EL2HLT;
    public static final /* enum */ Errno EHOSTDOWN;
    public static final /* enum */ Errno EUNATCH;
    public static final /* enum */ Errno ENOSYS;
    public static final /* enum */ Errno EREMOTE;
    public static final /* enum */ Errno EXFULL;
    public static final /* enum */ Errno EBADSLT;
    private final long value;
    public static final /* enum */ Errno ESTALE;
    public static final /* enum */ Errno EFBIG;
    public static final /* enum */ Errno ENODEV;
    public static final /* enum */ Errno ENONET;
    public static final /* enum */ Errno ECONNRESET;
    public static final /* enum */ Errno EMSGSIZE;
    public static final /* enum */ Errno EMFILE;
    public static final /* enum */ Errno ENFILE;
    public static final /* enum */ Errno ERANGE;
    public static final /* enum */ Errno EDOM;
    public static final /* enum */ Errno EPROTO;
    public static final /* enum */ Errno ESRCH;
    public static final /* enum */ Errno EDEADLOCK;
    public static final long MAX_VALUE = 151L;
    public static final /* enum */ Errno EACCES;
    public static final /* enum */ Errno ENOLCK;
    public static final /* enum */ Errno ENOBUFS;
    public static final /* enum */ Errno ELIBACC;
    public static final /* enum */ Errno ENOTEMPTY;
    public static final /* enum */ Errno ESHUTDOWN;
    public static final /* enum */ Errno ELIBMAX;
    public static final /* enum */ Errno EWOULDBLOCK;
    public static final /* enum */ Errno EIO;
    public static final /* enum */ Errno ESPIPE;
    public static final /* enum */ Errno EDQUOT;
    public static final /* enum */ Errno ELOOP;
    public static final /* enum */ Errno EMLINK;
    public static final /* enum */ Errno ENOTUNIQ;
    public static final /* enum */ Errno ENOPROTOOPT;
    public static final /* enum */ Errno ENOMSG;
    public static final /* enum */ Errno EHOSTUNREACH;
    public static final /* enum */ Errno ENOCSI;
    public static final /* enum */ Errno ECHILD;
    public static final /* enum */ Errno ENOTDIR;
    public static final /* enum */ Errno EBADE;
    public static final /* enum */ Errno EADV;
    public static final /* enum */ Errno EL3HLT;
    public static final /* enum */ Errno ELNRNG;
    public static final /* enum */ Errno EIDRM;
    public static final /* enum */ Errno ECANCELED;
    public static final /* enum */ Errno EPFNOSUPPORT;
    public static final /* enum */ Errno EMULTIHOP;
    public static final /* enum */ Errno EBADRQC;
    public static final /* enum */ Errno EISDIR;
    public static final /* enum */ Errno ERESTART;
    public static final /* enum */ Errno EBADFD;
    public static final /* enum */ Errno EILSEQ;
    public static final /* enum */ Errno EAFNOSUPPORT;
    public static final /* enum */ Errno EALREADY;
    public static final /* enum */ Errno ETXTBSY;
    private static final /* synthetic */ Errno[] $VALUES;
    public static final /* enum */ Errno EFAULT;
    public static final /* enum */ Errno EDEADLK;
    public static final /* enum */ Errno ECONNREFUSED;
    public static final /* enum */ Errno EOWNERDEAD;
    public static final /* enum */ Errno ENOTTY;
    public static final long MIN_VALUE = 1L;
    public static final /* enum */ Errno EADDRINUSE;
    public static final /* enum */ Errno ETIME;
    public static final /* enum */ Errno EPROTONOSUPPORT;
    public static final /* enum */ Errno ECOMM;
    public static final /* enum */ Errno ENOANO;
    public static final /* enum */ Errno ENETUNREACH;
    public static final /* enum */ Errno ENOSR;
    public static final /* enum */ Errno EINPROGRESS;
    public static final /* enum */ Errno ENOTRECOVERABLE;
    public static final /* enum */ Errno EROFS;
    public static final /* enum */ Errno EAGAIN;
    public static final /* enum */ Errno ECHRNG;
    public static final /* enum */ Errno EBADF;
    public static final /* enum */ Errno EPERM;
    public static final /* enum */ Errno EISCONN;
    public static final /* enum */ Errno EPIPE;
    public static final /* enum */ Errno ENOSTR;
    public static final /* enum */ Errno EBADR;
    public static final /* enum */ Errno ENXIO;
    public static final /* enum */ Errno EOVERFLOW;
    public static final /* enum */ Errno ELIBEXEC;
    public static final /* enum */ Errno EXDEV;
    public static final /* enum */ Errno EL3RST;
    public static final /* enum */ Errno ELIBBAD;
    public static final /* enum */ Errno ENOLINK;

    @Override
    public final boolean defined() {
        return true;
    }

    @Override
    public final int intValue() {
        return (int)this.value;
    }

    public final int value() {
        return (int)this.value;
    }

    static {
        EPERM = new Errno(1L);
        ENOENT = new Errno(2L);
        ESRCH = new Errno(3L);
        EINTR = new Errno(4L);
        EIO = new Errno(5L);
        ENXIO = new Errno(6L);
        E2BIG = new Errno(7L);
        ENOEXEC = new Errno(8L);
        EBADF = new Errno(9L);
        ECHILD = new Errno(10L);
        EDEADLK = new Errno(45L);
        ENOMEM = new Errno(12L);
        EACCES = new Errno(13L);
        EFAULT = new Errno(14L);
        ENOTBLK = new Errno(15L);
        EBUSY = new Errno(16L);
        EEXIST = new Errno(17L);
        EXDEV = new Errno(18L);
        ENODEV = new Errno(19L);
        ENOTDIR = new Errno(20L);
        EISDIR = new Errno(21L);
        EINVAL = new Errno(22L);
        ENFILE = new Errno(23L);
        EMFILE = new Errno(24L);
        ENOTTY = new Errno(25L);
        ETXTBSY = new Errno(26L);
        EFBIG = new Errno(27L);
        ENOSPC = new Errno(28L);
        ESPIPE = new Errno(29L);
        EROFS = new Errno(30L);
        EMLINK = new Errno(31L);
        EPIPE = new Errno(32L);
        EDOM = new Errno(33L);
        ERANGE = new Errno(34L);
        EWOULDBLOCK = new Errno(11L);
        EAGAIN = new Errno(11L);
        EINPROGRESS = new Errno(150L);
        EALREADY = new Errno(149L);
        ENOTSOCK = new Errno(95L);
        EDESTADDRREQ = new Errno(96L);
        EMSGSIZE = new Errno(97L);
        EPROTOTYPE = new Errno(98L);
        ENOPROTOOPT = new Errno(99L);
        EPROTONOSUPPORT = new Errno(120L);
        ESOCKTNOSUPPORT = new Errno(121L);
        EOPNOTSUPP = new Errno(122L);
        EPFNOSUPPORT = new Errno(123L);
        EAFNOSUPPORT = new Errno(124L);
        EADDRINUSE = new Errno(125L);
        EADDRNOTAVAIL = new Errno(126L);
        ENETDOWN = new Errno(127L);
        ENETUNREACH = new Errno(128L);
        ENETRESET = new Errno(129L);
        ECONNABORTED = new Errno(130L);
        ECONNRESET = new Errno(131L);
        ENOBUFS = new Errno(132L);
        EISCONN = new Errno(133L);
        ENOTCONN = new Errno(134L);
        ESHUTDOWN = new Errno(143L);
        ETOOMANYREFS = new Errno(144L);
        ETIMEDOUT = new Errno(145L);
        ECONNREFUSED = new Errno(146L);
        ELOOP = new Errno(90L);
        ENAMETOOLONG = new Errno(78L);
        EHOSTDOWN = new Errno(147L);
        EHOSTUNREACH = new Errno(148L);
        ENOTEMPTY = new Errno(93L);
        EUSERS = new Errno(94L);
        EDQUOT = new Errno(49L);
        ESTALE = new Errno(151L);
        EREMOTE = new Errno(66L);
        ENOLCK = new Errno(46L);
        ENOSYS = new Errno(89L);
        EOVERFLOW = new Errno(79L);
        EIDRM = new Errno(36L);
        ENOMSG = new Errno(35L);
        EILSEQ = new Errno(88L);
        EBADMSG = new Errno(77L);
        EMULTIHOP = new Errno(74L);
        ENODATA = new Errno(61L);
        ENOLINK = new Errno(67L);
        ENOSR = new Errno(63L);
        ENOSTR = new Errno(60L);
        EPROTO = new Errno(71L);
        ETIME = new Errno(62L);
        ECHRNG = new Errno(37L);
        EL2NSYNC = new Errno(38L);
        EL3HLT = new Errno(39L);
        EL3RST = new Errno(40L);
        ELNRNG = new Errno(41L);
        EUNATCH = new Errno(42L);
        ENOCSI = new Errno(43L);
        EL2HLT = new Errno(44L);
        EBADE = new Errno(50L);
        EBADR = new Errno(51L);
        EXFULL = new Errno(52L);
        ENOANO = new Errno(53L);
        EBADRQC = new Errno(54L);
        EBADSLT = new Errno(55L);
        EDEADLOCK = new Errno(56L);
        EBFONT = new Errno(57L);
        ENONET = new Errno(64L);
        ENOPKG = new Errno(65L);
        EADV = new Errno(68L);
        ESRMNT = new Errno(69L);
        ECOMM = new Errno(70L);
        ENOTUNIQ = new Errno(80L);
        EBADFD = new Errno(81L);
        EREMCHG = new Errno(82L);
        ELIBACC = new Errno(83L);
        ELIBBAD = new Errno(84L);
        ELIBSCN = new Errno(85L);
        ELIBMAX = new Errno(86L);
        ELIBEXEC = new Errno(87L);
        ERESTART = new Errno(91L);
        ESTRPIPE = new Errno(92L);
        ECANCELED = new Errno(47L);
        ENOTRECOVERABLE = new Errno(59L);
        EOWNERDEAD = new Errno(58L);
        ENOTSUP = new Errno(48L);
        Errno[] errnoArray = new Errno[120];
        errnoArray[0] = EPERM;
        errnoArray[1] = ENOENT;
        errnoArray[2] = ESRCH;
        errnoArray[3] = EINTR;
        errnoArray[4] = EIO;
        errnoArray[5] = ENXIO;
        errnoArray[6] = E2BIG;
        errnoArray[7] = ENOEXEC;
        errnoArray[8] = EBADF;
        errnoArray[9] = ECHILD;
        errnoArray[10] = EDEADLK;
        errnoArray[11] = ENOMEM;
        errnoArray[12] = EACCES;
        errnoArray[13] = EFAULT;
        errnoArray[14] = ENOTBLK;
        errnoArray[15] = EBUSY;
        errnoArray[16] = EEXIST;
        errnoArray[17] = EXDEV;
        errnoArray[18] = ENODEV;
        errnoArray[19] = ENOTDIR;
        errnoArray[20] = EISDIR;
        errnoArray[21] = EINVAL;
        errnoArray[22] = ENFILE;
        errnoArray[23] = EMFILE;
        errnoArray[24] = ENOTTY;
        errnoArray[25] = ETXTBSY;
        errnoArray[26] = EFBIG;
        errnoArray[27] = ENOSPC;
        errnoArray[28] = ESPIPE;
        errnoArray[29] = EROFS;
        errnoArray[30] = EMLINK;
        errnoArray[31] = EPIPE;
        errnoArray[32] = EDOM;
        errnoArray[33] = ERANGE;
        errnoArray[34] = EWOULDBLOCK;
        errnoArray[35] = EAGAIN;
        errnoArray[36] = EINPROGRESS;
        errnoArray[37] = EALREADY;
        errnoArray[38] = ENOTSOCK;
        errnoArray[39] = EDESTADDRREQ;
        errnoArray[40] = EMSGSIZE;
        errnoArray[41] = EPROTOTYPE;
        errnoArray[42] = ENOPROTOOPT;
        errnoArray[43] = EPROTONOSUPPORT;
        errnoArray[44] = ESOCKTNOSUPPORT;
        errnoArray[45] = EOPNOTSUPP;
        errnoArray[46] = EPFNOSUPPORT;
        errnoArray[47] = EAFNOSUPPORT;
        errnoArray[48] = EADDRINUSE;
        errnoArray[49] = EADDRNOTAVAIL;
        errnoArray[50] = ENETDOWN;
        errnoArray[51] = ENETUNREACH;
        errnoArray[52] = ENETRESET;
        errnoArray[53] = ECONNABORTED;
        errnoArray[54] = ECONNRESET;
        errnoArray[55] = ENOBUFS;
        errnoArray[56] = EISCONN;
        errnoArray[57] = ENOTCONN;
        errnoArray[58] = ESHUTDOWN;
        errnoArray[59] = ETOOMANYREFS;
        errnoArray[60] = ETIMEDOUT;
        errnoArray[61] = ECONNREFUSED;
        errnoArray[62] = ELOOP;
        errnoArray[63] = ENAMETOOLONG;
        errnoArray[64] = EHOSTDOWN;
        errnoArray[65] = EHOSTUNREACH;
        errnoArray[66] = ENOTEMPTY;
        errnoArray[67] = EUSERS;
        errnoArray[68] = EDQUOT;
        errnoArray[69] = ESTALE;
        errnoArray[70] = EREMOTE;
        errnoArray[71] = ENOLCK;
        errnoArray[72] = ENOSYS;
        errnoArray[73] = EOVERFLOW;
        errnoArray[74] = EIDRM;
        errnoArray[75] = ENOMSG;
        errnoArray[76] = EILSEQ;
        errnoArray[77] = EBADMSG;
        errnoArray[78] = EMULTIHOP;
        errnoArray[79] = ENODATA;
        errnoArray[80] = ENOLINK;
        errnoArray[81] = ENOSR;
        errnoArray[82] = ENOSTR;
        errnoArray[83] = EPROTO;
        errnoArray[84] = ETIME;
        errnoArray[85] = ECHRNG;
        errnoArray[86] = EL2NSYNC;
        errnoArray[87] = EL3HLT;
        errnoArray[88] = EL3RST;
        errnoArray[89] = ELNRNG;
        errnoArray[90] = EUNATCH;
        errnoArray[91] = ENOCSI;
        errnoArray[92] = EL2HLT;
        errnoArray[93] = EBADE;
        errnoArray[94] = EBADR;
        errnoArray[95] = EXFULL;
        errnoArray[96] = ENOANO;
        errnoArray[97] = EBADRQC;
        errnoArray[98] = EBADSLT;
        errnoArray[99] = EDEADLOCK;
        errnoArray[100] = EBFONT;
        errnoArray[101] = ENONET;
        errnoArray[102] = ENOPKG;
        errnoArray[103] = EADV;
        errnoArray[104] = ESRMNT;
        errnoArray[105] = ECOMM;
        errnoArray[106] = ENOTUNIQ;
        errnoArray[107] = EBADFD;
        errnoArray[108] = EREMCHG;
        errnoArray[109] = ELIBACC;
        errnoArray[110] = ELIBBAD;
        errnoArray[111] = ELIBSCN;
        errnoArray[112] = ELIBMAX;
        errnoArray[113] = ELIBEXEC;
        errnoArray[114] = ERESTART;
        errnoArray[115] = ESTRPIPE;
        errnoArray[116] = ECANCELED;
        errnoArray[117] = ENOTRECOVERABLE;
        errnoArray[118] = EOWNERDEAD;
        errnoArray[119] = ENOTSUP;
        $VALUES = errnoArray;
    }

    private Errno(long value) {
        this.value = value;
    }

    public final String toString() {
        return StringTable.descriptions.get(this);
    }

    public static Errno valueOf(String name) {
        return Enum.valueOf(Errno.class, name);
    }

    @Override
    public final long longValue() {
        return this.value;
    }

    public static Errno[] values() {
        return (Errno[])$VALUES.clone();
    }

    static final class StringTable {
        public static final Map<Errno, String> descriptions = StringTable.generateTable();

        StringTable() {
        }

        public static final Map<Errno, String> generateTable() {
            EnumMap<Errno, String> map = new EnumMap<Errno, String>(Errno.class);
            map.put(EPERM, "Not owner");
            map.put(ENOENT, "No such file or directory");
            map.put(ESRCH, "No such process");
            map.put(EINTR, "Interrupted system call");
            map.put(EIO, "I/O error");
            map.put(ENXIO, "No such device or address");
            map.put(E2BIG, "Arg list too long");
            map.put(ENOEXEC, "Exec format error");
            map.put(EBADF, "Bad file number");
            map.put(ECHILD, "No child processes");
            map.put(EDEADLK, "Deadlock situation detected/avoided");
            map.put(ENOMEM, "Not enough space");
            map.put(EACCES, "Permission denied");
            map.put(EFAULT, "Bad address");
            map.put(ENOTBLK, "Block device required");
            map.put(EBUSY, "Device busy");
            map.put(EEXIST, "File exists");
            map.put(EXDEV, "Cross-device link");
            map.put(ENODEV, "No such device");
            map.put(ENOTDIR, "Not a directory");
            map.put(EISDIR, "Is a directory");
            map.put(EINVAL, "Invalid argument");
            map.put(ENFILE, "File table overflow");
            map.put(EMFILE, "Too many open files");
            map.put(ENOTTY, "Inappropriate ioctl for device");
            map.put(ETXTBSY, "Text file busy");
            map.put(EFBIG, "File too large");
            map.put(ENOSPC, "No space left on device");
            map.put(ESPIPE, "Illegal seek");
            map.put(EROFS, "Read-only file system");
            map.put(EMLINK, "Too many links");
            map.put(EPIPE, "Broken pipe");
            map.put(EDOM, "Argument out of domain");
            map.put(ERANGE, "Result too large");
            map.put(EWOULDBLOCK, "Resource temporarily unavailable");
            map.put(EAGAIN, "Resource temporarily unavailable");
            map.put(EINPROGRESS, "Operation now in progress");
            map.put(EALREADY, "Operation already in progress");
            map.put(ENOTSOCK, "Socket operation on non-socket");
            map.put(EDESTADDRREQ, "Destination address required");
            map.put(EMSGSIZE, "Message too long");
            map.put(EPROTOTYPE, "Protocol wrong type for socket");
            map.put(ENOPROTOOPT, "Option not supported by protocol");
            map.put(EPROTONOSUPPORT, "Protocol not supported");
            map.put(ESOCKTNOSUPPORT, "Socket type not supported");
            map.put(EOPNOTSUPP, "Operation not supported on transport endpoint");
            map.put(EPFNOSUPPORT, "Protocol family not supported");
            map.put(EAFNOSUPPORT, "Address family not supported by protocol family");
            map.put(EADDRINUSE, "Address already in use");
            map.put(EADDRNOTAVAIL, "Cannot assign requested address");
            map.put(ENETDOWN, "Network is down");
            map.put(ENETUNREACH, "Network is unreachable");
            map.put(ENETRESET, "Network dropped connection because of reset");
            map.put(ECONNABORTED, "Software caused connection abort");
            map.put(ECONNRESET, "Connection reset by peer");
            map.put(ENOBUFS, "No buffer space available");
            map.put(EISCONN, "Transport endpoint is already connected");
            map.put(ENOTCONN, "Transport endpoint is not connected");
            map.put(ESHUTDOWN, "Cannot send after socket shutdown");
            map.put(ETOOMANYREFS, "Too many references: cannot splice");
            map.put(ETIMEDOUT, "Connection timed out");
            map.put(ECONNREFUSED, "Connection refused");
            map.put(ELOOP, "Number of symbolic links encountered during path name traversal exceeds MAXSYMLINKS");
            map.put(ENAMETOOLONG, "File name too long");
            map.put(EHOSTDOWN, "Host is down");
            map.put(EHOSTUNREACH, "No route to host");
            map.put(ENOTEMPTY, "Directory not empty");
            map.put(EUSERS, "Too many users");
            map.put(EDQUOT, "Disc quota exceeded");
            map.put(ESTALE, "Stale NFS file handle");
            map.put(EREMOTE, "Object is remote");
            map.put(ENOLCK, "No record locks available");
            map.put(ENOSYS, "Operation not applicable");
            map.put(EOVERFLOW, "Value too large for defined data type");
            map.put(EIDRM, "Identifier removed");
            map.put(ENOMSG, "No message of desired type");
            map.put(EILSEQ, "Illegal byte sequence");
            map.put(EBADMSG, "Not a data message");
            map.put(EMULTIHOP, "Multihop attempted");
            map.put(ENODATA, "No data available");
            map.put(ENOLINK, "Link has been severed");
            map.put(ENOSR, "Out of stream resources");
            map.put(ENOSTR, "Not a stream device");
            map.put(EPROTO, "Protocol error");
            map.put(ETIME, "Timer expired");
            map.put(ECHRNG, "Channel number out of range");
            map.put(EL2NSYNC, "Level 2 not synchronized");
            map.put(EL3HLT, "Level 3 halted");
            map.put(EL3RST, "Level 3 reset");
            map.put(ELNRNG, "Link number out of range");
            map.put(EUNATCH, "Protocol driver not attached");
            map.put(ENOCSI, "No CSI structure available");
            map.put(EL2HLT, "Level 2 halted");
            map.put(EBADE, "Checksum failure");
            map.put(EBADR, "Too fragmented");
            map.put(EXFULL, "Message tables full");
            map.put(ENOANO, "Cryptographic key not available");
            map.put(EBADRQC, "Bad request code");
            map.put(EBADSLT, "Invalid slot");
            map.put(EDEADLOCK, "File locking deadlock");
            map.put(EBFONT, "Bad font file format");
            map.put(ENONET, "Machine is not on the network");
            map.put(ENOPKG, "Package not installed");
            map.put(EADV, "Advertise error");
            map.put(ESRMNT, "Srmount error");
            map.put(ECOMM, "Communication error on send");
            map.put(ENOTUNIQ, "Name not unique on network");
            map.put(EBADFD, "File descriptor in bad state");
            map.put(EREMCHG, "Remote address changed");
            map.put(ELIBACC, "Can not access a needed shared library");
            map.put(ELIBBAD, "Accessing a corrupted shared library");
            map.put(ELIBSCN, ".lib section in a.out corrupted");
            map.put(ELIBMAX, "Attempting to link in more shared libraries than system limit");
            map.put(ELIBEXEC, "Can not exec a shared library directly");
            map.put(ERESTART, "Error 91");
            map.put(ESTRPIPE, "Error 92");
            map.put(ECANCELED, "Operation canceled");
            map.put(ENOTRECOVERABLE, "Lock is not recoverable");
            map.put(EOWNERDEAD, "Owner of the lock died");
            map.put(ENOTSUP, "Operation not supported");
            return map;
        }
    }
}

