/*
 * Decompiled with CFR 0.152.
 */
package jnr.constants.platform.solaris;

import java.util.EnumMap;
import java.util.Map;
import jnr.constants.Constant;

public final class Sysconf
extends Enum<Sysconf>
implements Constant {
    public static final /* enum */ Sysconf _SC_2_PBS_MESSAGE;
    public static final /* enum */ Sysconf _SC_TRACE_USER_EVENT_MAX;
    public static final /* enum */ Sysconf _SC_2_PBS_ACCOUNTING;
    public static final /* enum */ Sysconf _SC_2_CHAR_TERM;
    public static final /* enum */ Sysconf _SC_MQ_PRIO_MAX;
    public static final /* enum */ Sysconf _SC_XOPEN_REALTIME_THREADS;
    public static final /* enum */ Sysconf _SC_THREAD_PRIO_INHERIT;
    public static final /* enum */ Sysconf _SC_XBS5_LP64_OFF64;
    public static final /* enum */ Sysconf _SC_LOGIN_NAME_MAX;
    public static final /* enum */ Sysconf _SC_ATEXIT_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_STACK_MIN;
    public static final /* enum */ Sysconf _SC_2_UPE;
    public static final /* enum */ Sysconf _SC_CLK_TCK;
    public static final /* enum */ Sysconf _SC_GETPW_R_SIZE_MAX;
    public static final /* enum */ Sysconf _SC_XOPEN_CRYPT;
    public static final /* enum */ Sysconf _SC_2_PBS_TRACK;
    public static final long MIN_VALUE = 1L;
    public static final /* enum */ Sysconf _SC_XBS5_LPBIG_OFFBIG;
    public static final /* enum */ Sysconf _SC_XOPEN_XCU_VERSION;
    public static final /* enum */ Sysconf _SC_ADVISORY_INFO;
    public static final /* enum */ Sysconf _SC_SYNCHRONIZED_IO;
    public static final /* enum */ Sysconf _SC_XBS5_ILP32_OFFBIG;
    public static final long MAX_VALUE = 763L;
    public static final /* enum */ Sysconf _SC_TRACE_NAME_MAX;
    public static final /* enum */ Sysconf _SC_2_FORT_RUN;
    public static final /* enum */ Sysconf _SC_THREAD_ATTR_STACKADDR;
    public static final /* enum */ Sysconf _SC_2_SW_DEV;
    public static final /* enum */ Sysconf _SC_AIO_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_SPORADIC_SERVER;
    public static final /* enum */ Sysconf _SC_2_PBS_CHECKPOINT;
    public static final /* enum */ Sysconf _SC_THREADS;
    public static final /* enum */ Sysconf _SC_FSYNC;
    public static final /* enum */ Sysconf _SC_PASS_MAX;
    public static final /* enum */ Sysconf _SC_MEMORY_PROTECTION;
    public static final /* enum */ Sysconf _SC_RTSIG_MAX;
    public static final /* enum */ Sysconf _SC_MAPPED_FILES;
    public static final /* enum */ Sysconf _SC_OPEN_MAX;
    public static final /* enum */ Sysconf _SC_RAW_SOCKETS;
    public static final /* enum */ Sysconf _SC_MONOTONIC_CLOCK;
    public static final /* enum */ Sysconf _SC_TIMER_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_PRIO_PROTECT;
    public static final /* enum */ Sysconf _SC_V6_LPBIG_OFFBIG;
    public static final /* enum */ Sysconf _SC_TTY_NAME_MAX;
    public static final /* enum */ Sysconf _SC_SEM_NSEMS_MAX;
    public static final /* enum */ Sysconf _SC_2_VERSION;
    public static final /* enum */ Sysconf _SC_XOPEN_REALTIME;
    public static final /* enum */ Sysconf _SC_EXPR_NEST_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_CPUTIME;
    public static final /* enum */ Sysconf _SC_2_C_DEV;
    public static final /* enum */ Sysconf _SC_BARRIERS;
    public static final /* enum */ Sysconf _SC_NPROCESSORS_ONLN;
    public static final /* enum */ Sysconf _SC_SEMAPHORES;
    public static final /* enum */ Sysconf _SC_THREAD_DESTRUCTOR_ITERATIONS;
    public static final /* enum */ Sysconf _SC_BC_SCALE_MAX;
    public static final /* enum */ Sysconf _SC_XOPEN_VERSION;
    private static final /* synthetic */ Sysconf[] $VALUES;
    public static final /* enum */ Sysconf _SC_REGEXP;
    public static final /* enum */ Sysconf _SC_2_LOCALEDEF;
    public static final /* enum */ Sysconf _SC_SPAWN;
    public static final /* enum */ Sysconf _SC_PRIORITY_SCHEDULING;
    public static final /* enum */ Sysconf _SC_BC_BASE_MAX;
    public static final /* enum */ Sysconf _SC_LINE_MAX;
    public static final /* enum */ Sysconf _SC_2_PBS;
    public static final /* enum */ Sysconf _SC_ASYNCHRONOUS_IO;
    public static final /* enum */ Sysconf _SC_SPIN_LOCKS;
    public static final /* enum */ Sysconf _SC_V6_ILP32_OFFBIG;
    public static final /* enum */ Sysconf _SC_SIGQUEUE_MAX;
    public static final /* enum */ Sysconf _SC_SYMLOOP_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_THREADS_MAX;
    public static final /* enum */ Sysconf _SC_VERSION;
    public static final /* enum */ Sysconf _SC_SHELL;
    public static final /* enum */ Sysconf _SC_2_PBS_LOCATE;
    public static final /* enum */ Sysconf _SC_DELAYTIMER_MAX;
    private final long value;
    public static final /* enum */ Sysconf _SC_AIO_PRIO_DELTA_MAX;
    public static final /* enum */ Sysconf _SC_PAGE_SIZE;
    public static final /* enum */ Sysconf _SC_AIO_LISTIO_MAX;
    public static final /* enum */ Sysconf _SC_XOPEN_SHM;
    public static final /* enum */ Sysconf _SC_XBS5_ILP32_OFF32;
    public static final /* enum */ Sysconf _SC_MQ_OPEN_MAX;
    public static final /* enum */ Sysconf _SC_READER_WRITER_LOCKS;
    public static final /* enum */ Sysconf _SC_TYPED_MEMORY_OBJECTS;
    public static final /* enum */ Sysconf _SC_MEMLOCK_RANGE;
    public static final /* enum */ Sysconf _SC_MEMLOCK;
    public static final /* enum */ Sysconf _SC_BC_STRING_MAX;
    public static final /* enum */ Sysconf _SC_V6_ILP32_OFF32;
    public static final /* enum */ Sysconf _SC_TRACE_INHERIT;
    public static final /* enum */ Sysconf _SC_IOV_MAX;
    public static final /* enum */ Sysconf _SC_TRACE_EVENT_NAME_MAX;
    public static final /* enum */ Sysconf _SC_NGROUPS_MAX;
    public static final /* enum */ Sysconf _SC_HOST_NAME_MAX;
    public static final /* enum */ Sysconf _SC_IPV6;
    public static final /* enum */ Sysconf _SC_CPUTIME;
    public static final /* enum */ Sysconf _SC_XOPEN_LEGACY;
    public static final /* enum */ Sysconf _SC_PAGESIZE;
    public static final /* enum */ Sysconf _SC_2_FORT_DEV;
    public static final /* enum */ Sysconf _SC_SHARED_MEMORY_OBJECTS;
    public static final /* enum */ Sysconf _SC_TIMERS;
    public static final /* enum */ Sysconf _SC_GETGR_R_SIZE_MAX;
    public static final /* enum */ Sysconf _SC_XOPEN_STREAMS;
    public static final /* enum */ Sysconf _SC_THREAD_PROCESS_SHARED;
    public static final /* enum */ Sysconf _SC_ARG_MAX;
    public static final /* enum */ Sysconf _SC_SPORADIC_SERVER;
    public static final /* enum */ Sysconf _SC_JOB_CONTROL;
    public static final /* enum */ Sysconf _SC_TRACE_EVENT_FILTER;
    public static final /* enum */ Sysconf _SC_XOPEN_ENH_I18N;
    public static final /* enum */ Sysconf _SC_COLL_WEIGHTS_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_PRIORITY_SCHEDULING;
    public static final /* enum */ Sysconf _SC_REALTIME_SIGNALS;
    public static final /* enum */ Sysconf _SC_TIMEOUTS;
    public static final /* enum */ Sysconf _SC_SEM_VALUE_MAX;
    public static final /* enum */ Sysconf _SC_STREAM_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_ATTR_STACKSIZE;
    public static final /* enum */ Sysconf _SC_NPROCESSORS_CONF;
    public static final /* enum */ Sysconf _SC_CLOCK_SELECTION;
    public static final /* enum */ Sysconf _SC_RE_DUP_MAX;
    public static final /* enum */ Sysconf _SC_PRIORITIZED_IO;
    public static final /* enum */ Sysconf _SC_XOPEN_UNIX;
    public static final /* enum */ Sysconf _SC_TRACE_SYS_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_KEYS_MAX;
    public static final /* enum */ Sysconf _SC_THREAD_SAFE_FUNCTIONS;
    public static final /* enum */ Sysconf _SC_TRACE;
    public static final /* enum */ Sysconf _SC_TZNAME_MAX;
    public static final /* enum */ Sysconf _SC_2_C_BIND;
    public static final /* enum */ Sysconf _SC_TRACE_LOG;
    public static final /* enum */ Sysconf _SC_CHILD_MAX;
    public static final /* enum */ Sysconf _SC_SAVED_IDS;
    public static final /* enum */ Sysconf _SC_BC_DIM_MAX;
    public static final /* enum */ Sysconf _SC_MESSAGE_PASSING;
    public static final /* enum */ Sysconf _SC_V6_LP64_OFF64;
    public static final /* enum */ Sysconf _SC_SS_REPL_MAX;

    static {
        _SC_ARG_MAX = new Sysconf(1L);
        _SC_CHILD_MAX = new Sysconf(2L);
        _SC_CLK_TCK = new Sysconf(3L);
        _SC_NGROUPS_MAX = new Sysconf(4L);
        _SC_OPEN_MAX = new Sysconf(5L);
        _SC_JOB_CONTROL = new Sysconf(6L);
        _SC_SAVED_IDS = new Sysconf(7L);
        _SC_VERSION = new Sysconf(8L);
        _SC_BC_BASE_MAX = new Sysconf(54L);
        _SC_BC_DIM_MAX = new Sysconf(55L);
        _SC_BC_SCALE_MAX = new Sysconf(56L);
        _SC_BC_STRING_MAX = new Sysconf(57L);
        _SC_COLL_WEIGHTS_MAX = new Sysconf(58L);
        _SC_EXPR_NEST_MAX = new Sysconf(59L);
        _SC_LINE_MAX = new Sysconf(60L);
        _SC_RE_DUP_MAX = new Sysconf(61L);
        _SC_2_VERSION = new Sysconf(53L);
        _SC_2_C_BIND = new Sysconf(45L);
        _SC_2_C_DEV = new Sysconf(46L);
        _SC_2_CHAR_TERM = new Sysconf(66L);
        _SC_2_FORT_DEV = new Sysconf(48L);
        _SC_2_FORT_RUN = new Sysconf(49L);
        _SC_2_LOCALEDEF = new Sysconf(50L);
        _SC_2_SW_DEV = new Sysconf(51L);
        _SC_2_UPE = new Sysconf(52L);
        _SC_STREAM_MAX = new Sysconf(16L);
        _SC_TZNAME_MAX = new Sysconf(17L);
        _SC_ASYNCHRONOUS_IO = new Sysconf(21L);
        _SC_PAGESIZE = new Sysconf(11L);
        _SC_MEMLOCK = new Sysconf(25L);
        _SC_MEMLOCK_RANGE = new Sysconf(26L);
        _SC_MEMORY_PROTECTION = new Sysconf(27L);
        _SC_MESSAGE_PASSING = new Sysconf(28L);
        _SC_PRIORITIZED_IO = new Sysconf(31L);
        _SC_PRIORITY_SCHEDULING = new Sysconf(32L);
        _SC_REALTIME_SIGNALS = new Sysconf(33L);
        _SC_SEMAPHORES = new Sysconf(35L);
        _SC_FSYNC = new Sysconf(23L);
        _SC_SHARED_MEMORY_OBJECTS = new Sysconf(38L);
        _SC_SYNCHRONIZED_IO = new Sysconf(42L);
        _SC_TIMERS = new Sysconf(43L);
        _SC_AIO_LISTIO_MAX = new Sysconf(18L);
        _SC_AIO_MAX = new Sysconf(19L);
        _SC_AIO_PRIO_DELTA_MAX = new Sysconf(20L);
        _SC_DELAYTIMER_MAX = new Sysconf(22L);
        _SC_MQ_OPEN_MAX = new Sysconf(29L);
        _SC_MAPPED_FILES = new Sysconf(24L);
        _SC_RTSIG_MAX = new Sysconf(34L);
        _SC_SEM_NSEMS_MAX = new Sysconf(36L);
        _SC_SEM_VALUE_MAX = new Sysconf(37L);
        _SC_SIGQUEUE_MAX = new Sysconf(39L);
        _SC_TIMER_MAX = new Sysconf(44L);
        _SC_NPROCESSORS_CONF = new Sysconf(14L);
        _SC_NPROCESSORS_ONLN = new Sysconf(15L);
        _SC_2_PBS = new Sysconf(724L);
        _SC_2_PBS_ACCOUNTING = new Sysconf(725L);
        _SC_2_PBS_CHECKPOINT = new Sysconf(726L);
        _SC_2_PBS_LOCATE = new Sysconf(728L);
        _SC_2_PBS_MESSAGE = new Sysconf(729L);
        _SC_2_PBS_TRACK = new Sysconf(730L);
        _SC_ADVISORY_INFO = new Sysconf(731L);
        _SC_BARRIERS = new Sysconf(732L);
        _SC_CLOCK_SELECTION = new Sysconf(733L);
        _SC_CPUTIME = new Sysconf(734L);
        _SC_GETGR_R_SIZE_MAX = new Sysconf(569L);
        _SC_GETPW_R_SIZE_MAX = new Sysconf(570L);
        _SC_HOST_NAME_MAX = new Sysconf(735L);
        _SC_LOGIN_NAME_MAX = new Sysconf(571L);
        _SC_MONOTONIC_CLOCK = new Sysconf(736L);
        _SC_MQ_PRIO_MAX = new Sysconf(30L);
        _SC_READER_WRITER_LOCKS = new Sysconf(737L);
        _SC_REGEXP = new Sysconf(738L);
        _SC_SHELL = new Sysconf(739L);
        _SC_SPAWN = new Sysconf(740L);
        _SC_SPIN_LOCKS = new Sysconf(741L);
        _SC_SPORADIC_SERVER = new Sysconf(742L);
        _SC_THREAD_ATTR_STACKADDR = new Sysconf(577L);
        _SC_THREAD_ATTR_STACKSIZE = new Sysconf(578L);
        _SC_THREAD_CPUTIME = new Sysconf(745L);
        _SC_THREAD_DESTRUCTOR_ITERATIONS = new Sysconf(568L);
        _SC_THREAD_KEYS_MAX = new Sysconf(572L);
        _SC_THREAD_PRIO_INHERIT = new Sysconf(580L);
        _SC_THREAD_PRIO_PROTECT = new Sysconf(581L);
        _SC_THREAD_PRIORITY_SCHEDULING = new Sysconf(579L);
        _SC_THREAD_PROCESS_SHARED = new Sysconf(582L);
        _SC_THREAD_SAFE_FUNCTIONS = new Sysconf(583L);
        _SC_THREAD_SPORADIC_SERVER = new Sysconf(746L);
        _SC_THREAD_STACK_MIN = new Sysconf(573L);
        _SC_THREAD_THREADS_MAX = new Sysconf(574L);
        _SC_TIMEOUTS = new Sysconf(747L);
        _SC_THREADS = new Sysconf(576L);
        _SC_TRACE = new Sysconf(748L);
        _SC_TRACE_EVENT_FILTER = new Sysconf(749L);
        _SC_TRACE_INHERIT = new Sysconf(751L);
        _SC_TRACE_LOG = new Sysconf(752L);
        _SC_TTY_NAME_MAX = new Sysconf(575L);
        _SC_TYPED_MEMORY_OBJECTS = new Sysconf(756L);
        _SC_V6_ILP32_OFF32 = new Sysconf(757L);
        _SC_V6_ILP32_OFFBIG = new Sysconf(758L);
        _SC_V6_LP64_OFF64 = new Sysconf(759L);
        _SC_V6_LPBIG_OFFBIG = new Sysconf(760L);
        _SC_IPV6 = new Sysconf(762L);
        _SC_RAW_SOCKETS = new Sysconf(763L);
        _SC_SYMLOOP_MAX = new Sysconf(744L);
        _SC_ATEXIT_MAX = new Sysconf(76L);
        _SC_IOV_MAX = new Sysconf(77L);
        _SC_PAGE_SIZE = new Sysconf(11L);
        _SC_XOPEN_CRYPT = new Sysconf(62L);
        _SC_XOPEN_ENH_I18N = new Sysconf(63L);
        _SC_XOPEN_LEGACY = new Sysconf(717L);
        _SC_XOPEN_REALTIME = new Sysconf(718L);
        _SC_XOPEN_REALTIME_THREADS = new Sysconf(719L);
        _SC_XOPEN_SHM = new Sysconf(64L);
        _SC_XOPEN_STREAMS = new Sysconf(761L);
        _SC_XOPEN_UNIX = new Sysconf(78L);
        _SC_XOPEN_VERSION = new Sysconf(12L);
        _SC_XOPEN_XCU_VERSION = new Sysconf(67L);
        _SC_XBS5_ILP32_OFF32 = new Sysconf(720L);
        _SC_XBS5_ILP32_OFFBIG = new Sysconf(721L);
        _SC_XBS5_LP64_OFF64 = new Sysconf(722L);
        _SC_XBS5_LPBIG_OFFBIG = new Sysconf(723L);
        _SC_SS_REPL_MAX = new Sysconf(743L);
        _SC_TRACE_EVENT_NAME_MAX = new Sysconf(750L);
        _SC_TRACE_NAME_MAX = new Sysconf(753L);
        _SC_TRACE_SYS_MAX = new Sysconf(754L);
        _SC_TRACE_USER_EVENT_MAX = new Sysconf(755L);
        _SC_PASS_MAX = new Sysconf(9L);
        Sysconf[] sysconfArray = new Sysconf[127];
        sysconfArray[0] = _SC_ARG_MAX;
        sysconfArray[1] = _SC_CHILD_MAX;
        sysconfArray[2] = _SC_CLK_TCK;
        sysconfArray[3] = _SC_NGROUPS_MAX;
        sysconfArray[4] = _SC_OPEN_MAX;
        sysconfArray[5] = _SC_JOB_CONTROL;
        sysconfArray[6] = _SC_SAVED_IDS;
        sysconfArray[7] = _SC_VERSION;
        sysconfArray[8] = _SC_BC_BASE_MAX;
        sysconfArray[9] = _SC_BC_DIM_MAX;
        sysconfArray[10] = _SC_BC_SCALE_MAX;
        sysconfArray[11] = _SC_BC_STRING_MAX;
        sysconfArray[12] = _SC_COLL_WEIGHTS_MAX;
        sysconfArray[13] = _SC_EXPR_NEST_MAX;
        sysconfArray[14] = _SC_LINE_MAX;
        sysconfArray[15] = _SC_RE_DUP_MAX;
        sysconfArray[16] = _SC_2_VERSION;
        sysconfArray[17] = _SC_2_C_BIND;
        sysconfArray[18] = _SC_2_C_DEV;
        sysconfArray[19] = _SC_2_CHAR_TERM;
        sysconfArray[20] = _SC_2_FORT_DEV;
        sysconfArray[21] = _SC_2_FORT_RUN;
        sysconfArray[22] = _SC_2_LOCALEDEF;
        sysconfArray[23] = _SC_2_SW_DEV;
        sysconfArray[24] = _SC_2_UPE;
        sysconfArray[25] = _SC_STREAM_MAX;
        sysconfArray[26] = _SC_TZNAME_MAX;
        sysconfArray[27] = _SC_ASYNCHRONOUS_IO;
        sysconfArray[28] = _SC_PAGESIZE;
        sysconfArray[29] = _SC_MEMLOCK;
        sysconfArray[30] = _SC_MEMLOCK_RANGE;
        sysconfArray[31] = _SC_MEMORY_PROTECTION;
        sysconfArray[32] = _SC_MESSAGE_PASSING;
        sysconfArray[33] = _SC_PRIORITIZED_IO;
        sysconfArray[34] = _SC_PRIORITY_SCHEDULING;
        sysconfArray[35] = _SC_REALTIME_SIGNALS;
        sysconfArray[36] = _SC_SEMAPHORES;
        sysconfArray[37] = _SC_FSYNC;
        sysconfArray[38] = _SC_SHARED_MEMORY_OBJECTS;
        sysconfArray[39] = _SC_SYNCHRONIZED_IO;
        sysconfArray[40] = _SC_TIMERS;
        sysconfArray[41] = _SC_AIO_LISTIO_MAX;
        sysconfArray[42] = _SC_AIO_MAX;
        sysconfArray[43] = _SC_AIO_PRIO_DELTA_MAX;
        sysconfArray[44] = _SC_DELAYTIMER_MAX;
        sysconfArray[45] = _SC_MQ_OPEN_MAX;
        sysconfArray[46] = _SC_MAPPED_FILES;
        sysconfArray[47] = _SC_RTSIG_MAX;
        sysconfArray[48] = _SC_SEM_NSEMS_MAX;
        sysconfArray[49] = _SC_SEM_VALUE_MAX;
        sysconfArray[50] = _SC_SIGQUEUE_MAX;
        sysconfArray[51] = _SC_TIMER_MAX;
        sysconfArray[52] = _SC_NPROCESSORS_CONF;
        sysconfArray[53] = _SC_NPROCESSORS_ONLN;
        sysconfArray[54] = _SC_2_PBS;
        sysconfArray[55] = _SC_2_PBS_ACCOUNTING;
        sysconfArray[56] = _SC_2_PBS_CHECKPOINT;
        sysconfArray[57] = _SC_2_PBS_LOCATE;
        sysconfArray[58] = _SC_2_PBS_MESSAGE;
        sysconfArray[59] = _SC_2_PBS_TRACK;
        sysconfArray[60] = _SC_ADVISORY_INFO;
        sysconfArray[61] = _SC_BARRIERS;
        sysconfArray[62] = _SC_CLOCK_SELECTION;
        sysconfArray[63] = _SC_CPUTIME;
        sysconfArray[64] = _SC_GETGR_R_SIZE_MAX;
        sysconfArray[65] = _SC_GETPW_R_SIZE_MAX;
        sysconfArray[66] = _SC_HOST_NAME_MAX;
        sysconfArray[67] = _SC_LOGIN_NAME_MAX;
        sysconfArray[68] = _SC_MONOTONIC_CLOCK;
        sysconfArray[69] = _SC_MQ_PRIO_MAX;
        sysconfArray[70] = _SC_READER_WRITER_LOCKS;
        sysconfArray[71] = _SC_REGEXP;
        sysconfArray[72] = _SC_SHELL;
        sysconfArray[73] = _SC_SPAWN;
        sysconfArray[74] = _SC_SPIN_LOCKS;
        sysconfArray[75] = _SC_SPORADIC_SERVER;
        sysconfArray[76] = _SC_THREAD_ATTR_STACKADDR;
        sysconfArray[77] = _SC_THREAD_ATTR_STACKSIZE;
        sysconfArray[78] = _SC_THREAD_CPUTIME;
        sysconfArray[79] = _SC_THREAD_DESTRUCTOR_ITERATIONS;
        sysconfArray[80] = _SC_THREAD_KEYS_MAX;
        sysconfArray[81] = _SC_THREAD_PRIO_INHERIT;
        sysconfArray[82] = _SC_THREAD_PRIO_PROTECT;
        sysconfArray[83] = _SC_THREAD_PRIORITY_SCHEDULING;
        sysconfArray[84] = _SC_THREAD_PROCESS_SHARED;
        sysconfArray[85] = _SC_THREAD_SAFE_FUNCTIONS;
        sysconfArray[86] = _SC_THREAD_SPORADIC_SERVER;
        sysconfArray[87] = _SC_THREAD_STACK_MIN;
        sysconfArray[88] = _SC_THREAD_THREADS_MAX;
        sysconfArray[89] = _SC_TIMEOUTS;
        sysconfArray[90] = _SC_THREADS;
        sysconfArray[91] = _SC_TRACE;
        sysconfArray[92] = _SC_TRACE_EVENT_FILTER;
        sysconfArray[93] = _SC_TRACE_INHERIT;
        sysconfArray[94] = _SC_TRACE_LOG;
        sysconfArray[95] = _SC_TTY_NAME_MAX;
        sysconfArray[96] = _SC_TYPED_MEMORY_OBJECTS;
        sysconfArray[97] = _SC_V6_ILP32_OFF32;
        sysconfArray[98] = _SC_V6_ILP32_OFFBIG;
        sysconfArray[99] = _SC_V6_LP64_OFF64;
        sysconfArray[100] = _SC_V6_LPBIG_OFFBIG;
        sysconfArray[101] = _SC_IPV6;
        sysconfArray[102] = _SC_RAW_SOCKETS;
        sysconfArray[103] = _SC_SYMLOOP_MAX;
        sysconfArray[104] = _SC_ATEXIT_MAX;
        sysconfArray[105] = _SC_IOV_MAX;
        sysconfArray[106] = _SC_PAGE_SIZE;
        sysconfArray[107] = _SC_XOPEN_CRYPT;
        sysconfArray[108] = _SC_XOPEN_ENH_I18N;
        sysconfArray[109] = _SC_XOPEN_LEGACY;
        sysconfArray[110] = _SC_XOPEN_REALTIME;
        sysconfArray[111] = _SC_XOPEN_REALTIME_THREADS;
        sysconfArray[112] = _SC_XOPEN_SHM;
        sysconfArray[113] = _SC_XOPEN_STREAMS;
        sysconfArray[114] = _SC_XOPEN_UNIX;
        sysconfArray[115] = _SC_XOPEN_VERSION;
        sysconfArray[116] = _SC_XOPEN_XCU_VERSION;
        sysconfArray[117] = _SC_XBS5_ILP32_OFF32;
        sysconfArray[118] = _SC_XBS5_ILP32_OFFBIG;
        sysconfArray[119] = _SC_XBS5_LP64_OFF64;
        sysconfArray[120] = _SC_XBS5_LPBIG_OFFBIG;
        sysconfArray[121] = _SC_SS_REPL_MAX;
        sysconfArray[122] = _SC_TRACE_EVENT_NAME_MAX;
        sysconfArray[123] = _SC_TRACE_NAME_MAX;
        sysconfArray[124] = _SC_TRACE_SYS_MAX;
        sysconfArray[125] = _SC_TRACE_USER_EVENT_MAX;
        sysconfArray[126] = _SC_PASS_MAX;
        $VALUES = sysconfArray;
    }

    @Override
    public final boolean defined() {
        return true;
    }

    @Override
    public final long longValue() {
        return this.value;
    }

    public static Sysconf[] values() {
        return (Sysconf[])$VALUES.clone();
    }

    public final String toString() {
        return StringTable.descriptions.get(this);
    }

    private Sysconf(long value) {
        this.value = value;
    }

    @Override
    public final int intValue() {
        return (int)this.value;
    }

    public static Sysconf valueOf(String name) {
        return Enum.valueOf(Sysconf.class, name);
    }

    public final int value() {
        return (int)this.value;
    }

    static final class StringTable {
        public static final Map<Sysconf, String> descriptions = StringTable.generateTable();

        public static final Map<Sysconf, String> generateTable() {
            EnumMap<Sysconf, String> map = new EnumMap<Sysconf, String>(Sysconf.class);
            map.put(_SC_ARG_MAX, "_SC_ARG_MAX");
            map.put(_SC_CHILD_MAX, "_SC_CHILD_MAX");
            map.put(_SC_CLK_TCK, "_SC_CLK_TCK");
            map.put(_SC_NGROUPS_MAX, "_SC_NGROUPS_MAX");
            map.put(_SC_OPEN_MAX, "_SC_OPEN_MAX");
            map.put(_SC_JOB_CONTROL, "_SC_JOB_CONTROL");
            map.put(_SC_SAVED_IDS, "_SC_SAVED_IDS");
            map.put(_SC_VERSION, "_SC_VERSION");
            map.put(_SC_BC_BASE_MAX, "_SC_BC_BASE_MAX");
            map.put(_SC_BC_DIM_MAX, "_SC_BC_DIM_MAX");
            map.put(_SC_BC_SCALE_MAX, "_SC_BC_SCALE_MAX");
            map.put(_SC_BC_STRING_MAX, "_SC_BC_STRING_MAX");
            map.put(_SC_COLL_WEIGHTS_MAX, "_SC_COLL_WEIGHTS_MAX");
            map.put(_SC_EXPR_NEST_MAX, "_SC_EXPR_NEST_MAX");
            map.put(_SC_LINE_MAX, "_SC_LINE_MAX");
            map.put(_SC_RE_DUP_MAX, "_SC_RE_DUP_MAX");
            map.put(_SC_2_VERSION, "_SC_2_VERSION");
            map.put(_SC_2_C_BIND, "_SC_2_C_BIND");
            map.put(_SC_2_C_DEV, "_SC_2_C_DEV");
            map.put(_SC_2_CHAR_TERM, "_SC_2_CHAR_TERM");
            map.put(_SC_2_FORT_DEV, "_SC_2_FORT_DEV");
            map.put(_SC_2_FORT_RUN, "_SC_2_FORT_RUN");
            map.put(_SC_2_LOCALEDEF, "_SC_2_LOCALEDEF");
            map.put(_SC_2_SW_DEV, "_SC_2_SW_DEV");
            map.put(_SC_2_UPE, "_SC_2_UPE");
            map.put(_SC_STREAM_MAX, "_SC_STREAM_MAX");
            map.put(_SC_TZNAME_MAX, "_SC_TZNAME_MAX");
            map.put(_SC_ASYNCHRONOUS_IO, "_SC_ASYNCHRONOUS_IO");
            map.put(_SC_PAGESIZE, "_SC_PAGESIZE");
            map.put(_SC_MEMLOCK, "_SC_MEMLOCK");
            map.put(_SC_MEMLOCK_RANGE, "_SC_MEMLOCK_RANGE");
            map.put(_SC_MEMORY_PROTECTION, "_SC_MEMORY_PROTECTION");
            map.put(_SC_MESSAGE_PASSING, "_SC_MESSAGE_PASSING");
            map.put(_SC_PRIORITIZED_IO, "_SC_PRIORITIZED_IO");
            map.put(_SC_PRIORITY_SCHEDULING, "_SC_PRIORITY_SCHEDULING");
            map.put(_SC_REALTIME_SIGNALS, "_SC_REALTIME_SIGNALS");
            map.put(_SC_SEMAPHORES, "_SC_SEMAPHORES");
            map.put(_SC_FSYNC, "_SC_FSYNC");
            map.put(_SC_SHARED_MEMORY_OBJECTS, "_SC_SHARED_MEMORY_OBJECTS");
            map.put(_SC_SYNCHRONIZED_IO, "_SC_SYNCHRONIZED_IO");
            map.put(_SC_TIMERS, "_SC_TIMERS");
            map.put(_SC_AIO_LISTIO_MAX, "_SC_AIO_LISTIO_MAX");
            map.put(_SC_AIO_MAX, "_SC_AIO_MAX");
            map.put(_SC_AIO_PRIO_DELTA_MAX, "_SC_AIO_PRIO_DELTA_MAX");
            map.put(_SC_DELAYTIMER_MAX, "_SC_DELAYTIMER_MAX");
            map.put(_SC_MQ_OPEN_MAX, "_SC_MQ_OPEN_MAX");
            map.put(_SC_MAPPED_FILES, "_SC_MAPPED_FILES");
            map.put(_SC_RTSIG_MAX, "_SC_RTSIG_MAX");
            map.put(_SC_SEM_NSEMS_MAX, "_SC_SEM_NSEMS_MAX");
            map.put(_SC_SEM_VALUE_MAX, "_SC_SEM_VALUE_MAX");
            map.put(_SC_SIGQUEUE_MAX, "_SC_SIGQUEUE_MAX");
            map.put(_SC_TIMER_MAX, "_SC_TIMER_MAX");
            map.put(_SC_NPROCESSORS_CONF, "_SC_NPROCESSORS_CONF");
            map.put(_SC_NPROCESSORS_ONLN, "_SC_NPROCESSORS_ONLN");
            map.put(_SC_2_PBS, "_SC_2_PBS");
            map.put(_SC_2_PBS_ACCOUNTING, "_SC_2_PBS_ACCOUNTING");
            map.put(_SC_2_PBS_CHECKPOINT, "_SC_2_PBS_CHECKPOINT");
            map.put(_SC_2_PBS_LOCATE, "_SC_2_PBS_LOCATE");
            map.put(_SC_2_PBS_MESSAGE, "_SC_2_PBS_MESSAGE");
            map.put(_SC_2_PBS_TRACK, "_SC_2_PBS_TRACK");
            map.put(_SC_ADVISORY_INFO, "_SC_ADVISORY_INFO");
            map.put(_SC_BARRIERS, "_SC_BARRIERS");
            map.put(_SC_CLOCK_SELECTION, "_SC_CLOCK_SELECTION");
            map.put(_SC_CPUTIME, "_SC_CPUTIME");
            map.put(_SC_GETGR_R_SIZE_MAX, "_SC_GETGR_R_SIZE_MAX");
            map.put(_SC_GETPW_R_SIZE_MAX, "_SC_GETPW_R_SIZE_MAX");
            map.put(_SC_HOST_NAME_MAX, "_SC_HOST_NAME_MAX");
            map.put(_SC_LOGIN_NAME_MAX, "_SC_LOGIN_NAME_MAX");
            map.put(_SC_MONOTONIC_CLOCK, "_SC_MONOTONIC_CLOCK");
            map.put(_SC_MQ_PRIO_MAX, "_SC_MQ_PRIO_MAX");
            map.put(_SC_READER_WRITER_LOCKS, "_SC_READER_WRITER_LOCKS");
            map.put(_SC_REGEXP, "_SC_REGEXP");
            map.put(_SC_SHELL, "_SC_SHELL");
            map.put(_SC_SPAWN, "_SC_SPAWN");
            map.put(_SC_SPIN_LOCKS, "_SC_SPIN_LOCKS");
            map.put(_SC_SPORADIC_SERVER, "_SC_SPORADIC_SERVER");
            map.put(_SC_THREAD_ATTR_STACKADDR, "_SC_THREAD_ATTR_STACKADDR");
            map.put(_SC_THREAD_ATTR_STACKSIZE, "_SC_THREAD_ATTR_STACKSIZE");
            map.put(_SC_THREAD_CPUTIME, "_SC_THREAD_CPUTIME");
            map.put(_SC_THREAD_DESTRUCTOR_ITERATIONS, "_SC_THREAD_DESTRUCTOR_ITERATIONS");
            map.put(_SC_THREAD_KEYS_MAX, "_SC_THREAD_KEYS_MAX");
            map.put(_SC_THREAD_PRIO_INHERIT, "_SC_THREAD_PRIO_INHERIT");
            map.put(_SC_THREAD_PRIO_PROTECT, "_SC_THREAD_PRIO_PROTECT");
            map.put(_SC_THREAD_PRIORITY_SCHEDULING, "_SC_THREAD_PRIORITY_SCHEDULING");
            map.put(_SC_THREAD_PROCESS_SHARED, "_SC_THREAD_PROCESS_SHARED");
            map.put(_SC_THREAD_SAFE_FUNCTIONS, "_SC_THREAD_SAFE_FUNCTIONS");
            map.put(_SC_THREAD_SPORADIC_SERVER, "_SC_THREAD_SPORADIC_SERVER");
            map.put(_SC_THREAD_STACK_MIN, "_SC_THREAD_STACK_MIN");
            map.put(_SC_THREAD_THREADS_MAX, "_SC_THREAD_THREADS_MAX");
            map.put(_SC_TIMEOUTS, "_SC_TIMEOUTS");
            map.put(_SC_THREADS, "_SC_THREADS");
            map.put(_SC_TRACE, "_SC_TRACE");
            map.put(_SC_TRACE_EVENT_FILTER, "_SC_TRACE_EVENT_FILTER");
            map.put(_SC_TRACE_INHERIT, "_SC_TRACE_INHERIT");
            map.put(_SC_TRACE_LOG, "_SC_TRACE_LOG");
            map.put(_SC_TTY_NAME_MAX, "_SC_TTY_NAME_MAX");
            map.put(_SC_TYPED_MEMORY_OBJECTS, "_SC_TYPED_MEMORY_OBJECTS");
            map.put(_SC_V6_ILP32_OFF32, "_SC_V6_ILP32_OFF32");
            map.put(_SC_V6_ILP32_OFFBIG, "_SC_V6_ILP32_OFFBIG");
            map.put(_SC_V6_LP64_OFF64, "_SC_V6_LP64_OFF64");
            map.put(_SC_V6_LPBIG_OFFBIG, "_SC_V6_LPBIG_OFFBIG");
            map.put(_SC_IPV6, "_SC_IPV6");
            map.put(_SC_RAW_SOCKETS, "_SC_RAW_SOCKETS");
            map.put(_SC_SYMLOOP_MAX, "_SC_SYMLOOP_MAX");
            map.put(_SC_ATEXIT_MAX, "_SC_ATEXIT_MAX");
            map.put(_SC_IOV_MAX, "_SC_IOV_MAX");
            map.put(_SC_PAGE_SIZE, "_SC_PAGE_SIZE");
            map.put(_SC_XOPEN_CRYPT, "_SC_XOPEN_CRYPT");
            map.put(_SC_XOPEN_ENH_I18N, "_SC_XOPEN_ENH_I18N");
            map.put(_SC_XOPEN_LEGACY, "_SC_XOPEN_LEGACY");
            map.put(_SC_XOPEN_REALTIME, "_SC_XOPEN_REALTIME");
            map.put(_SC_XOPEN_REALTIME_THREADS, "_SC_XOPEN_REALTIME_THREADS");
            map.put(_SC_XOPEN_SHM, "_SC_XOPEN_SHM");
            map.put(_SC_XOPEN_STREAMS, "_SC_XOPEN_STREAMS");
            map.put(_SC_XOPEN_UNIX, "_SC_XOPEN_UNIX");
            map.put(_SC_XOPEN_VERSION, "_SC_XOPEN_VERSION");
            map.put(_SC_XOPEN_XCU_VERSION, "_SC_XOPEN_XCU_VERSION");
            map.put(_SC_XBS5_ILP32_OFF32, "_SC_XBS5_ILP32_OFF32");
            map.put(_SC_XBS5_ILP32_OFFBIG, "_SC_XBS5_ILP32_OFFBIG");
            map.put(_SC_XBS5_LP64_OFF64, "_SC_XBS5_LP64_OFF64");
            map.put(_SC_XBS5_LPBIG_OFFBIG, "_SC_XBS5_LPBIG_OFFBIG");
            map.put(_SC_SS_REPL_MAX, "_SC_SS_REPL_MAX");
            map.put(_SC_TRACE_EVENT_NAME_MAX, "_SC_TRACE_EVENT_NAME_MAX");
            map.put(_SC_TRACE_NAME_MAX, "_SC_TRACE_NAME_MAX");
            map.put(_SC_TRACE_SYS_MAX, "_SC_TRACE_SYS_MAX");
            map.put(_SC_TRACE_USER_EVENT_MAX, "_SC_TRACE_USER_EVENT_MAX");
            map.put(_SC_PASS_MAX, "_SC_PASS_MAX");
            return map;
        }

        StringTable() {
        }
    }
}

