org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
org.gradle.parallel=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
org.gradle.java.installations.paths=/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home

minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
fabric_version=0.119.4+1.21.4
mixinextras_version=0.5.4

mod_version=1.0.0
maven_group=ru.destra
archives_base_name=destra-recovered
