/*
 * Decompiled with CFR 0.152.
 */
package jnr.x86asm;

/*
 * This class specifies class file version 49.0 but uses Java 6 signatures.  Assumed Java 6.
 */
public final class INST_CODE
extends Enum<INST_CODE> {
    public static final /* enum */ INST_CODE INST_PFMUL;
    public static final /* enum */ INST_CODE INST_FPTAN;
    public static final /* enum */ INST_CODE INST_PUSHFQ;
    public static final /* enum */ INST_CODE INST_AMD_PREFETCHW;
    public static final /* enum */ INST_CODE INST_JGE;
    public static final /* enum */ INST_CODE INST_PSHUFD;
    public static final /* enum */ INST_CODE INST_MOV_PTR;
    public static final /* enum */ INST_CODE INST_PFACC;
    public static final /* enum */ INST_CODE INST_MOVAPS;
    public static final /* enum */ INST_CODE INST_PUNPCKLBW;
    public static final /* enum */ INST_CODE INST_FICOM;
    public static final /* enum */ INST_CODE INST_POP;
    public static final /* enum */ INST_CODE INST_PSLLDQ;
    public static final /* enum */ INST_CODE INST_FRNDINT;
    public static final /* enum */ INST_CODE INST_FCLEX;
    public static final /* enum */ INST_CODE INST_PADDSW;
    public static final /* enum */ INST_CODE INST_CMOVNGE;
    public static final /* enum */ INST_CODE INST_BTR;
    public static final /* enum */ INST_CODE INST_JS;
    public static final /* enum */ INST_CODE INST_PFCMPGE;
    public static final /* enum */ INST_CODE INST_CVTSS2SI;
    public static final /* enum */ INST_CODE INST_MOVDDUP;
    public static final /* enum */ INST_CODE INST_PSUBB;
    public static final /* enum */ INST_CODE INST_HADDPS;
    public static final /* enum */ INST_CODE INST_FXCH;
    public static final /* enum */ INST_CODE INST_ROL;
    public static final /* enum */ INST_CODE INST_JC_SHORT;
    public static final /* enum */ INST_CODE INST_XADD;
    public static final /* enum */ INST_CODE INST_PF2IW;
    public static final /* enum */ INST_CODE INST_MULPD;
    public static final /* enum */ INST_CODE INST_PFCMPEQ;
    public static final /* enum */ INST_CODE INST_INT3;
    public static final /* enum */ INST_CODE INST_ANDNPS;
    public static final /* enum */ INST_CODE INST_JLE;
    public static final /* enum */ INST_CODE INST_SUBSD;
    public static final /* enum */ INST_CODE INST_CMOVNB;
    public static final /* enum */ INST_CODE INST_SETPE;
    public static final /* enum */ INST_CODE INST_FDIVR;
    public static final /* enum */ INST_CODE INST_PCMPISTRI;
    public static final /* enum */ INST_CODE INST_PEXTRB;
    public static final /* enum */ INST_CODE INST_SBB;
    public static final /* enum */ INST_CODE INST_MOVSHDUP;
    public static final /* enum */ INST_CODE INST_FSTSW;
    public static final /* enum */ INST_CODE INST_MOVUPD;
    public static final /* enum */ INST_CODE INST_CMOVLE;
    public static final /* enum */ INST_CODE INST_DEC;
    public static final /* enum */ INST_CODE INST_PFPNACC;
    public static final /* enum */ INST_CODE INST_DIV;
    public static final /* enum */ INST_CODE INST_UNPCKHPD;
    public static final /* enum */ INST_CODE INST_FISUB;
    public static final /* enum */ INST_CODE INST_PCMPEQW;
    public static final /* enum */ INST_CODE INST_XCHG;
    public static final /* enum */ INST_CODE INST_PSRLD;
    public static final /* enum */ INST_CODE INST_BT;
    public static final /* enum */ INST_CODE INST_F2XM1;
    public static final /* enum */ INST_CODE INST_FLD;
    public static final /* enum */ INST_CODE INST_PMAXSB;
    public static final /* enum */ INST_CODE INST_PANDN;
    public static final /* enum */ INST_CODE INST_FLDLN2;
    public static final /* enum */ INST_CODE INST_FCMOVNB;
    public static final /* enum */ INST_CODE INST_PUSHAD;
    public static final /* enum */ INST_CODE INST_RCR;
    public static final /* enum */ INST_CODE INST_PMINSD;
    public static final /* enum */ INST_CODE INST_ENTER;
    public static final /* enum */ INST_CODE INST_ADC;
    public static final /* enum */ INST_CODE INST_SETNB;
    public static final /* enum */ INST_CODE INST_CMPXCHG;
    public static final /* enum */ INST_CODE INST_SETZ;
    public static final /* enum */ INST_CODE INST_FXTRACT;
    public static final /* enum */ INST_CODE INST_JNL_SHORT;
    public static final /* enum */ INST_CODE INST_SETS;
    public static final /* enum */ INST_CODE INST_MOVHLPS;
    public static final /* enum */ INST_CODE INST_MINPS;
    public static final /* enum */ INST_CODE INST_PMOVSXDQ;
    public static final /* enum */ INST_CODE INST_ANDPS;
    public static final /* enum */ INST_CODE INST_PXOR;
    public static final /* enum */ INST_CODE INST_FILD;
    public static final /* enum */ INST_CODE INST_FSQRT;
    public static final /* enum */ INST_CODE INST_BLENDVPS;
    public static final /* enum */ INST_CODE INST_MOVDQU;
    public static final /* enum */ INST_CODE INST_PMULHRSW;
    public static final INST_CODE INST_J;
    public static final /* enum */ INST_CODE INST_CWDE;
    public static final /* enum */ INST_CODE INST_PSRAW;
    public static final /* enum */ INST_CODE INST_BSR;
    public static final /* enum */ INST_CODE INST_ADDPS;
    public static final /* enum */ INST_CODE INST_FCMOVBE;
    public static final /* enum */ INST_CODE INST_FFREE;
    public static final /* enum */ INST_CODE INST_FRSTOR;
    public static final /* enum */ INST_CODE INST_PMINSW;
    public static final /* enum */ INST_CODE INST_SETE;
    public static final /* enum */ INST_CODE INST_FCMOVU;
    public static final /* enum */ INST_CODE INST_PUNPCKLQDQ;
    public static final /* enum */ INST_CODE INST_PADDW;
    public static final /* enum */ INST_CODE INST_FCMOVE;
    public static final /* enum */ INST_CODE INST_MOVSLDUP;
    public static final /* enum */ INST_CODE INST_SETNBE;
    public static final /* enum */ INST_CODE INST_SQRTSS;
    public static final /* enum */ INST_CODE INST_JNL;
    public static final /* enum */ INST_CODE INST_PCMPGTQ;
    public static final /* enum */ INST_CODE INST_COMISS;
    public static final /* enum */ INST_CODE INST_BSF;
    public static final /* enum */ INST_CODE INST_MOVNTDQ;
    public static final /* enum */ INST_CODE INST_PMOVZXDQ;
    public static final /* enum */ INST_CODE INST_MOVQ2DQ;
    public static final /* enum */ INST_CODE INST_PABSB;
    public static final /* enum */ INST_CODE INST_CMOVP;
    public static final /* enum */ INST_CODE INST_ROUNDPD;
    public static final /* enum */ INST_CODE INST_SETL;
    public static final /* enum */ INST_CODE INST_JL_SHORT;
    public static final /* enum */ INST_CODE INST_XOR;
    public static final /* enum */ INST_CODE INST_JPE;
    public static final /* enum */ INST_CODE INST_CMOVBE;
    public static final /* enum */ INST_CODE INST_MOVDQA;
    public static final /* enum */ INST_CODE INST_JNZ;
    public static final /* enum */ INST_CODE INST_PUNPCKLWD;
    public static final /* enum */ INST_CODE INST_FLD1;
    public static final /* enum */ INST_CODE INST_JNAE;
    public static final /* enum */ INST_CODE INST_PFSUBR;
    public static final /* enum */ INST_CODE INST_ROR;
    public static final /* enum */ INST_CODE INST_JB_SHORT;
    public static final /* enum */ INST_CODE INST_MOV;
    public static final /* enum */ INST_CODE INST_CMOVNA;
    public static final /* enum */ INST_CODE INST_JC;
    public static final /* enum */ INST_CODE INST_CVTTPS2PI;
    public static final /* enum */ INST_CODE INST_JNGE;
    public static final /* enum */ INST_CODE INST_FCOS;
    public static final /* enum */ INST_CODE INST_PFADD;
    public static final /* enum */ INST_CODE INST_MOVNTPD;
    public static final /* enum */ INST_CODE INST_JB;
    public static final /* enum */ INST_CODE INST_FCHS;
    public static final /* enum */ INST_CODE INST_PEXTRD;
    public static final INST_CODE INST_J_SHORT;
    private static final /* synthetic */ INST_CODE[] $VALUES;
    public static final /* enum */ INST_CODE INST_ADDSUBPD;
    public static final /* enum */ INST_CODE INST_PHSUBD;
    public static final /* enum */ INST_CODE INST_FIDIVR;
    public static final /* enum */ INST_CODE INST_FCOMIP;
    public static final /* enum */ INST_CODE INST_MINSS;
    public static final /* enum */ INST_CODE INST_SETNC;
    public static final /* enum */ INST_CODE INST_JBE;
    public static final /* enum */ INST_CODE INST_FNCLEX;
    public static final /* enum */ INST_CODE INST_CVTTPD2PI;
    public static final /* enum */ INST_CODE INST_FST;
    public static final /* enum */ INST_CODE INST_PMAXSW;
    public static final /* enum */ INST_CODE INST_CLFLUSH;
    public static final /* enum */ INST_CODE INST_PAVGB;
    public static final /* enum */ INST_CODE INST_MOVNTPS;
    public static final /* enum */ INST_CODE INST_PFRCPIT1;
    public static final /* enum */ INST_CODE INST_CBW;
    public static final /* enum */ INST_CODE INST_CVTSI2SD;
    public static final /* enum */ INST_CODE INST_FLDL2E;
    public static final /* enum */ INST_CODE INST_STC;
    public static final /* enum */ INST_CODE INST_CMOVNZ;
    public static final /* enum */ INST_CODE INST_CMOVNLE;
    public static final /* enum */ INST_CODE INST_PSUBW;
    public static final /* enum */ INST_CODE INST_STMXCSR;
    public static final /* enum */ INST_CODE INST_PMAXUW;
    public static final /* enum */ INST_CODE INST_CVTPD2PS;
    public static final /* enum */ INST_CODE INST_PEXTRQ;
    public static final /* enum */ INST_CODE INST_PAND;
    public static final /* enum */ INST_CODE INST_SETA;
    public static final /* enum */ INST_CODE INST_JNG;
    public static final /* enum */ INST_CODE INST_SETO;
    public static final /* enum */ INST_CODE INST_PCMPGTD;
    public static final /* enum */ INST_CODE INST_MOVLPD;
    public static final /* enum */ INST_CODE INST_CMOVPO;
    public static final /* enum */ INST_CODE INST_DPPS;
    public static final /* enum */ INST_CODE INST_PMOVZXWQ;
    public static final /* enum */ INST_CODE INST_CVTPD2DQ;
    public static final /* enum */ INST_CODE INST_MOVMSKPS;
    public static final /* enum */ INST_CODE INST_PADDQ;
    public static final /* enum */ INST_CODE INST_FDIVP;
    public static final /* enum */ INST_CODE INST_FISTP;
    public static final /* enum */ INST_CODE INST_JNBE_SHORT;
    public static final /* enum */ INST_CODE INST_JO_SHORT;
    public static final /* enum */ INST_CODE INST_FCOMP;
    public static final /* enum */ INST_CODE INST_BLENDVPD;
    public static final /* enum */ INST_CODE INST_ORPS;
    public static final /* enum */ INST_CODE INST_FPATAN;
    public static final /* enum */ INST_CODE INST_JNO;
    public static final /* enum */ INST_CODE INST_FIMUL;
    public static final /* enum */ INST_CODE INST_PMOVSXWD;
    public static final /* enum */ INST_CODE INST_STD;
    public static final /* enum */ INST_CODE INST_FDIV;
    public static final /* enum */ INST_CODE INST_CMOVB;
    public static final /* enum */ INST_CODE INST_LOCK;
    public static final /* enum */ INST_CODE INST_ROUNDSS;
    public static final /* enum */ INST_CODE INST_SAR;
    public static final /* enum */ INST_CODE INST_FIST;
    public static final /* enum */ INST_CODE INST_CMC;
    public static final /* enum */ INST_CODE INST_ORPD;
    public static final /* enum */ INST_CODE INST_PACKUSWB;
    public static final /* enum */ INST_CODE INST_SHUFPS;
    public static final /* enum */ INST_CODE INST_PCMPEQQ;
    public static final /* enum */ INST_CODE INST_PUNPCKHQDQ;
    public static final /* enum */ INST_CODE INST_JNA_SHORT;
    public static final /* enum */ INST_CODE INST_PMULHUW;
    public static final /* enum */ INST_CODE INST_PSUBUSB;
    public static final /* enum */ INST_CODE INST_CDQE;
    public static final /* enum */ INST_CODE INST_CVTPS2PI;
    public static final /* enum */ INST_CODE INST_JE_SHORT;
    public static final /* enum */ INST_CODE INST_PHADDW;
    public static final /* enum */ INST_CODE INST_JNB;
    public static final /* enum */ INST_CODE INST_SUBPD;
    public static final /* enum */ INST_CODE INST_PSUBD;
    public static final /* enum */ INST_CODE INST_FEMMS;
    public static final /* enum */ INST_CODE INST_CMOVNBE;
    public static final /* enum */ INST_CODE INST_PACKSSDW;
    public static final /* enum */ INST_CODE INST_MOVHPS;
    public static final /* enum */ INST_CODE INST_FMULP;
    public static final /* enum */ INST_CODE INST_PSRLQ;
    public static final /* enum */ INST_CODE INST_JNC;
    public static final /* enum */ INST_CODE INST_JNP_SHORT;
    public static final /* enum */ INST_CODE INST_EMMS;
    public static final /* enum */ INST_CODE INST_LEA;
    public static final /* enum */ INST_CODE INST_HSUBPS;
    public static final /* enum */ INST_CODE INST_DAA;
    public static final /* enum */ INST_CODE INST_ANDNPD;
    public static final /* enum */ INST_CODE INST_PUNPCKHDQ;
    public static final /* enum */ INST_CODE INST_FNOP;
    public static final /* enum */ INST_CODE INST_JPO_SHORT;
    public static final /* enum */ INST_CODE INST_PSHUFLW;
    public static final /* enum */ INST_CODE INST_RDTSCP;
    public static final /* enum */ INST_CODE INST_MOVSX;
    public static final /* enum */ INST_CODE INST_PSUBSW;
    public static final /* enum */ INST_CODE INST_FLDPI;
    public static final /* enum */ INST_CODE INST_SFENCE;
    public static final /* enum */ INST_CODE INST_PSRLDQ;
    public static final /* enum */ INST_CODE INST_SETNO;
    public static final /* enum */ INST_CODE INST_PTEST;
    public static final /* enum */ INST_CODE INST_UCOMISS;
    public static final /* enum */ INST_CODE INST_PMULLW;
    public static final /* enum */ INST_CODE INST_JMP;
    public static final /* enum */ INST_CODE INST_MULSD;
    public static final /* enum */ INST_CODE INST_PMOVZXWD;
    public static final /* enum */ INST_CODE INST_UNPCKLPS;
    public static final /* enum */ INST_CODE INST_JNGE_SHORT;
    public static final /* enum */ INST_CODE INST_FXSAVE;
    public static final /* enum */ INST_CODE INST_RCPPS;
    public static final /* enum */ INST_CODE INST_MOVLHPS;
    public static final /* enum */ INST_CODE INST_FWAIT;
    public static final /* enum */ INST_CODE INST_PMADDUBSW;
    public static final /* enum */ INST_CODE INST_FCMOVNBE;
    public static final /* enum */ INST_CODE INST_JPE_SHORT;
    public static final /* enum */ INST_CODE INST_RDTSC;
    public static final /* enum */ INST_CODE INST_SETP;
    public static final /* enum */ INST_CODE INST_PMAXUB;
    public static final /* enum */ INST_CODE INST_SETNLE;
    public static final /* enum */ INST_CODE INST_PMAXUD;
    public static final /* enum */ INST_CODE INST_PMULHW;
    public static final /* enum */ INST_CODE INST_SETNS;
    public static final /* enum */ INST_CODE INST_PCMPGTW;
    public static final /* enum */ INST_CODE INST_PSUBSB;
    public static final /* enum */ INST_CODE INST_CVTPS2PD;
    public static final /* enum */ INST_CODE INST_DIVSS;
    public static final /* enum */ INST_CODE INST_SQRTPD;
    public static final /* enum */ INST_CODE INST_MUL;
    public static final /* enum */ INST_CODE INST_FPREM1;
    public static final /* enum */ INST_CODE INST_MFENCE;
    public static final /* enum */ INST_CODE INST_FXAM;
    public static final /* enum */ INST_CODE INST_CVTTSS2SI;
    public static final /* enum */ INST_CODE INST_UNPCKHPS;
    public static final /* enum */ INST_CODE INST_CMOVNP;
    public static final /* enum */ INST_CODE INST_BSWAP;
    public static final /* enum */ INST_CODE INST_PMOVZXBW;
    public static final /* enum */ INST_CODE INST_AND;
    public static final /* enum */ INST_CODE INST_PFMAX;
    public static final /* enum */ INST_CODE INST_PSHUFHW;
    public static final /* enum */ INST_CODE INST_JMP_SHORT;
    public static final /* enum */ INST_CODE INST_PFRCP;
    public static final /* enum */ INST_CODE INST_PINSRW;
    public static final /* enum */ INST_CODE INST_SQRTSD;
    public static final /* enum */ INST_CODE INST_PADDUSW;
    public static final /* enum */ INST_CODE INST_FSAVE;
    public static final /* enum */ INST_CODE INST_PFRCPIT2;
    public static final /* enum */ INST_CODE INST_PCMPESTRM;
    public static final /* enum */ INST_CODE INST_RSQRTPS;
    public static final /* enum */ INST_CODE INST_LDDQU;
    public static final /* enum */ INST_CODE INST_FSINCOS;
    public static final /* enum */ INST_CODE INST_CVTPI2PD;
    public static final /* enum */ INST_CODE INST_JBE_SHORT;
    public static final /* enum */ INST_CODE INST_LFENCE;
    public static final /* enum */ INST_CODE INST_PADDSB;
    public static final /* enum */ INST_CODE INST_FSUB;
    public static final /* enum */ INST_CODE INST_POPFD;
    public static final /* enum */ INST_CODE INST_PMAXSD;
    public static final /* enum */ INST_CODE INST_FBLD;
    public static final /* enum */ INST_CODE INST_HADDPD;
    public static final /* enum */ INST_CODE INST_AMD_PREFETCH;
    public static final /* enum */ INST_CODE INST_LEAVE;
    public static final /* enum */ INST_CODE INST_JNLE;
    public static final /* enum */ INST_CODE INST_PHADDSW;
    public static final /* enum */ INST_CODE INST_MINPD;
    public static final /* enum */ INST_CODE INST_PCMPEQD;
    public static final /* enum */ INST_CODE INST_BTC;
    public static final /* enum */ INST_CODE INST_SETNG;
    public static final /* enum */ INST_CODE INST_RSQRTSS;
    public static final /* enum */ INST_CODE INST_CMP;
    public static final /* enum */ INST_CODE INST_NOT;
    public static final /* enum */ INST_CODE INST_CMOVNL;
    public static final /* enum */ INST_CODE INST_FNSTSW;
    public static final /* enum */ INST_CODE INST_ADD;
    public static final /* enum */ INST_CODE INST_JL;
    public static final /* enum */ INST_CODE INST_SHR;
    public static final /* enum */ INST_CODE INST_MAXPS;
    public static final /* enum */ INST_CODE INST_PINSRQ;
    public static final /* enum */ INST_CODE INST_SQRTPS;
    public static final /* enum */ INST_CODE INST_PSHUFW;
    public static final /* enum */ INST_CODE INST_PADDUSB;
    public static final /* enum */ INST_CODE INST_NEG;
    public static final /* enum */ INST_CODE INST_XORPS;
    public static final /* enum */ INST_CODE INST_PMINUW;
    public static final /* enum */ INST_CODE INST_JLE_SHORT;
    public static final /* enum */ INST_CODE INST_JG_SHORT;
    public static final /* enum */ INST_CODE INST_PSUBUSW;
    public static final /* enum */ INST_CODE INST_POPCNT;
    public static final /* enum */ INST_CODE INST_FNSTCW;
    public static final /* enum */ INST_CODE INST_CMOVO;
    public static final /* enum */ INST_CODE INST_JNG_SHORT;
    public static final /* enum */ INST_CODE INST_ADDSD;
    public static final /* enum */ INST_CODE INST_MOVAPD;
    public static final /* enum */ INST_CODE INST_MULPS;
    public static final /* enum */ INST_CODE INST_FLDLG2;
    public static final /* enum */ INST_CODE INST_FUCOMPP;
    public static final /* enum */ INST_CODE INST_JAE;
    public static final /* enum */ INST_CODE INST_JNS_SHORT;
    public static final /* enum */ INST_CODE INST_PUNPCKHWD;
    public static final /* enum */ INST_CODE INST_JE;
    public static final /* enum */ INST_CODE INST_FINIT;
    public static final /* enum */ INST_CODE INST_PUSH;
    public static final /* enum */ INST_CODE INST_PMOVSXWQ;
    public static final /* enum */ INST_CODE INST_FNSAVE;
    public static final /* enum */ INST_CODE INST_FSUBP;
    public static final /* enum */ INST_CODE INST_PCMPEQB;
    public static final /* enum */ INST_CODE INST_PSLLD;
    public static final /* enum */ INST_CODE INST_CMPSD;
    public static final /* enum */ INST_CODE INST_RET;
    public static final /* enum */ INST_CODE INST_PADDD;
    public static final /* enum */ INST_CODE INST_CVTDQ2PS;
    public static final /* enum */ INST_CODE INST_PSLLW;
    public static final /* enum */ INST_CODE INST_CMPXCHG16B;
    public static final /* enum */ INST_CODE INST_PSHUFB;
    public static final /* enum */ INST_CODE INST_MAXSS;
    public static final /* enum */ INST_CODE INST_MOVNTDQA;
    public static final /* enum */ INST_CODE INST_SETC;
    public static final /* enum */ INST_CODE INST_PINSRD;
    public static final /* enum */ INST_CODE INST_CPUID;
    public static final /* enum */ INST_CODE INST_SETNE;
    public static final /* enum */ INST_CODE INST_MOVNTI;
    public static final /* enum */ INST_CODE INST_JAE_SHORT;
    public static final /* enum */ INST_CODE INST_FCMOVNU;
    public static final /* enum */ INST_CODE INST_JNE_SHORT;
    public static final /* enum */ INST_CODE INST_PMULDQ;
    public static final /* enum */ INST_CODE INST_SHL;
    public static final /* enum */ INST_CODE INST_PHMINPOSUW;
    public static final /* enum */ INST_CODE INST_JGE_SHORT;
    public static final /* enum */ INST_CODE INST_FNSTENV;
    public static final /* enum */ INST_CODE INST_PMULLD;
    public static final /* enum */ INST_CODE INST_MINSD;
    public static final /* enum */ INST_CODE INST_PBLENDVB;
    public static final /* enum */ INST_CODE INST_SETAE;
    public static final /* enum */ INST_CODE INST_JNB_SHORT;
    public static final /* enum */ INST_CODE INST_BLENDPS;
    public static final /* enum */ INST_CODE INST_CMOVE;
    public static final /* enum */ INST_CODE INST_PMOVMSKB;
    public static final /* enum */ INST_CODE INST_UCOMISD;
    public static final /* enum */ INST_CODE INST_SETNP;
    public static final /* enum */ INST_CODE INST_PMOVSXBW;
    public static final /* enum */ INST_CODE INST_JZ;
    public static final /* enum */ INST_CODE INST_CVTPI2PS;
    public static final /* enum */ INST_CODE INST_MOVD;
    public static final /* enum */ INST_CODE INST_DIVPS;
    public static final /* enum */ INST_CODE INST_CLC;
    public static final /* enum */ INST_CODE INST_CMPSS;
    public static final /* enum */ INST_CODE INST_PFMIN;
    public static final /* enum */ INST_CODE INST_MOVSXD;
    public static final /* enum */ INST_CODE INST_FCOMI;
    public static final /* enum */ INST_CODE INST_CMOVNO;
    public static final /* enum */ INST_CODE INST_RCL;
    public static final /* enum */ INST_CODE INST_PMINSB;
    public static final /* enum */ INST_CODE INST_PSRAD;
    public static final /* enum */ INST_CODE INST_DPPD;
    public static final /* enum */ INST_CODE INST_UNPCKLPD;
    public static final /* enum */ INST_CODE INST_JS_SHORT;
    public static final /* enum */ INST_CODE INST_SETNGE;
    public static final /* enum */ INST_CODE INST_FCOM;
    public static final /* enum */ INST_CODE INST_PMINUD;
    public static final /* enum */ INST_CODE INST_SHRD;
    public static final /* enum */ INST_CODE INST_FIADD;
    public static final /* enum */ INST_CODE INST_MOVNTQ;
    public static final /* enum */ INST_CODE INST_CMPXCHG8B;
    public static final /* enum */ INST_CODE INST_TEST;
    public static final /* enum */ INST_CODE INST_PCMPGTB;
    public static final /* enum */ INST_CODE INST_JNA;
    public static final /* enum */ INST_CODE INST_IMUL;
    public static final /* enum */ INST_CODE INST_MPSADBW;
    public static final /* enum */ INST_CODE INST_PSIGNW;
    public static final /* enum */ INST_CODE INST_OR;
    public static final /* enum */ INST_CODE INST_DIVSD;
    public static final /* enum */ INST_CODE INST_FNINIT;
    public static final /* enum */ INST_CODE INST_MASKMOVQ;
    public static final /* enum */ INST_CODE INST_ADDSUBPS;
    public static final /* enum */ INST_CODE INST_SETNL;
    public static final /* enum */ INST_CODE INST_FSUBR;
    public static final /* enum */ INST_CODE INST_FPREM;
    public static final /* enum */ INST_CODE INST_FMUL;
    public static final /* enum */ INST_CODE INST_FSCALE;
    public static final /* enum */ INST_CODE INST_MOVMSKPD;
    public static final /* enum */ INST_CODE INST_ANDPD;
    public static final /* enum */ INST_CODE INST_CVTTPD2DQ;
    public static final /* enum */ INST_CODE INST_FISTTP;
    public static final /* enum */ INST_CODE INST_CVTDQ2PD;
    public static final /* enum */ INST_CODE INST_PUNPCKLDQ;
    public static final /* enum */ INST_CODE INST_PSLLQ;
    public static final /* enum */ INST_CODE INST_SAL;
    public static final /* enum */ INST_CODE INST_FISUBR;
    public static final /* enum */ INST_CODE INST_POPAD;
    public static final /* enum */ INST_CODE INST_JG;
    public static final /* enum */ INST_CODE INST_FSTP;
    public static final /* enum */ INST_CODE INST_LDMXCSR;
    public static final /* enum */ INST_CODE INST_FYL2X;
    public static final /* enum */ INST_CODE INST_COMISD;
    public static final /* enum */ INST_CODE INST_FUCOM;
    public static final /* enum */ INST_CODE INST_MOVDQ2Q;
    public static final /* enum */ INST_CODE INST_CVTSD2SS;
    public static final /* enum */ INST_CODE INST_FYL2XP1;
    public static final /* enum */ INST_CODE INST_FSTENV;
    public static final /* enum */ INST_CODE INST_MOVHPD;
    public static final /* enum */ INST_CODE INST_FIDIV;
    public static final /* enum */ INST_CODE INST_PI2FD;
    public static final /* enum */ INST_CODE INST_PACKUSDW;
    public static final /* enum */ INST_CODE INST_FUCOMP;
    public static final /* enum */ INST_CODE INST_FADDP;
    public static final /* enum */ INST_CODE INST_PAUSE;
    public static final /* enum */ INST_CODE INST_JNAE_SHORT;
    public static final /* enum */ INST_CODE INST_CMOVAE;
    public static final /* enum */ INST_CODE INST_PBLENDW;
    public static final /* enum */ INST_CODE INST_PSWAPD;
    public static final /* enum */ INST_CODE INST_SAHF;
    public static final /* enum */ INST_CODE INST_PALIGNR;
    public static final /* enum */ INST_CODE INST_CVTPD2PI;
    public static final /* enum */ INST_CODE INST_FUCOMI;
    public static final /* enum */ INST_CODE INST_SETLE;
    public static final /* enum */ INST_CODE INST_FCOMPP;
    public static final /* enum */ INST_CODE INST_SUBPS;
    public static final /* enum */ INST_CODE INST_FTST;
    public static final /* enum */ INST_CODE INST_PMINUB;
    public static final /* enum */ INST_CODE INST_CMOVGE;
    public static final /* enum */ INST_CODE INST_PSUBQ;
    public static final /* enum */ INST_CODE INST_FADD;
    public static final /* enum */ INST_CODE INST_SETGE;
    public static final /* enum */ INST_CODE INST_ROUNDSD;
    public static final /* enum */ INST_CODE INST_PMOVSXBQ;
    public static final /* enum */ INST_CODE INST_MOVQ;
    public static final /* enum */ INST_CODE INST_PSADBW;
    public static final /* enum */ INST_CODE INST_INC;
    public static final /* enum */ INST_CODE INST_SETBE;
    public static final /* enum */ INST_CODE INST_JPO;
    public static final /* enum */ INST_CODE INST_PREFETCH;
    public static final /* enum */ INST_CODE INST_CMOVPE;
    public static final /* enum */ INST_CODE INST_ADDPD;
    public static final /* enum */ INST_CODE INST_PEXTRW;
    public static final /* enum */ INST_CODE INST_PHADDD;
    public static final /* enum */ INST_CODE INST_SUB;
    public static final /* enum */ INST_CODE INST_PMULUDQ;
    public static final /* enum */ INST_CODE INST_FLDL2T;
    public static final /* enum */ INST_CODE INST_MOVSS;
    public static final /* enum */ INST_CODE INST_CMOVL;
    public static final /* enum */ INST_CODE INST_SETB;
    public static final /* enum */ INST_CODE INST_JNS;
    public static final /* enum */ INST_CODE INST_SETNAE;
    public static final /* enum */ INST_CODE INST_FCMOVNE;
    public static final /* enum */ INST_CODE INST_PF2ID;
    public static final /* enum */ INST_CODE INST_MOVZX;
    public static final /* enum */ INST_CODE INST_PSRLW;
    public static final /* enum */ INST_CODE INST_CMOVZ;
    public static final /* enum */ INST_CODE INST_POR;
    public static final /* enum */ INST_CODE INST_CMOVG;
    public static final /* enum */ INST_CODE INST_CMPPD;
    public static final /* enum */ INST_CODE INST_JNZ_SHORT;
    public static final /* enum */ INST_CODE INST_PI2FW;
    public static final /* enum */ INST_CODE INST_SETNA;
    public static final /* enum */ INST_CODE INST_CMOVC;
    public static final /* enum */ INST_CODE INST_MULSS;
    public static final /* enum */ INST_CODE INST_PMOVZXBD;
    public static final /* enum */ INST_CODE INST_FSTCW;
    public static final /* enum */ INST_CODE INST_PFRSQIT1;
    public static final /* enum */ INST_CODE INST_JP_SHORT;
    public static final /* enum */ INST_CODE INST_JNO_SHORT;
    public static final /* enum */ INST_CODE INST_ADDSS;
    public static final /* enum */ INST_CODE INST_MWAIT;
    public static final /* enum */ INST_CODE INST_SETPO;
    public static final /* enum */ INST_CODE INST_FICOMP;
    public static final /* enum */ INST_CODE INST_PFSUB;
    public static final /* enum */ INST_CODE INST_MASKMOVDQU;
    public static final /* enum */ INST_CODE INST_MONITOR;
    public static final /* enum */ INST_CODE INST_SHLD;
    public static final /* enum */ INST_CODE INST_JZ_SHORT;
    public static final /* enum */ INST_CODE INST_CMOVNC;
    public static final /* enum */ INST_CODE INST_JA;
    public static final /* enum */ INST_CODE INST_JNC_SHORT;
    public static final /* enum */ INST_CODE INST_PMOVSXBD;
    public static final /* enum */ INST_CODE INST_SETG;
    public static final /* enum */ INST_CODE INST_BLENDPD;
    public static final /* enum */ INST_CODE INST_POPFQ;
    public static final /* enum */ INST_CODE INST_PMOVZXBQ;
    public static final /* enum */ INST_CODE INST_CVTSD2SI;
    public static final /* enum */ INST_CODE INST_FINCSTP;
    public static final /* enum */ INST_CODE INST_CVTSS2SD;
    public static final /* enum */ INST_CODE INST_PSIGND;
    public static final /* enum */ INST_CODE INST_CMOVNS;
    public static final /* enum */ INST_CODE INST_MOVBE;
    public static final /* enum */ INST_CODE INST_PSIGNB;
    public static final /* enum */ INST_CODE INST_FUCOMIP;
    public static final /* enum */ INST_CODE INST_CVTPS2DQ;
    public static final /* enum */ INST_CODE INST_PHSUBSW;
    public static final /* enum */ INST_CODE INST_CMPPS;
    public static final /* enum */ INST_CODE INST_PMADDWD;
    public static final /* enum */ INST_CODE INST_PFRSQRT;
    public static final /* enum */ INST_CODE INST_JNBE;
    public static final /* enum */ INST_CODE INST_PINSRB;
    public static final /* enum */ INST_CODE INST_FLDCW;
    public static final /* enum */ INST_CODE INST_PFNACC;
    public static final /* enum */ INST_CODE INST_RCPSS;
    public static final /* enum */ INST_CODE INST_NOP;
    public static final /* enum */ INST_CODE INST_BTS;
    public static final /* enum */ INST_CODE INST_MOVSD;
    public static final /* enum */ INST_CODE INST_PCMPISTRM;
    public static final /* enum */ INST_CODE INST_FLDZ;
    public static final /* enum */ INST_CODE INST_SETNZ;
    public static final /* enum */ INST_CODE INST_JO;
    public static final /* enum */ INST_CODE INST_FDECSTP;
    public static final /* enum */ INST_CODE INST_FDIVRP;
    public static final /* enum */ INST_CODE INST_XORPD;
    public static final /* enum */ INST_CODE INST_CVTSI2SS;
    public static final /* enum */ INST_CODE INST_HSUBPD;
    public static final /* enum */ INST_CODE INST_CMOVA;
    public static final /* enum */ INST_CODE INST_MOVLPS;
    public static final /* enum */ INST_CODE INST_PCMPESTRI;
    public static final /* enum */ INST_CODE INST_FSUBRP;
    public static final /* enum */ INST_CODE INST_JNP;
    public static final /* enum */ INST_CODE INST_PUSHFD;
    public static final /* enum */ INST_CODE INST_PAVGW;
    public static final /* enum */ INST_CODE INST_UD2;
    public static final /* enum */ INST_CODE INST_FSIN;
    public static final /* enum */ INST_CODE INST_JA_SHORT;
    public static final /* enum */ INST_CODE INST_CVTTPS2DQ;
    public static final /* enum */ INST_CODE INST_JP;
    public static final /* enum */ INST_CODE INST_CMOVS;
    public static final /* enum */ INST_CODE INST_EXTRACTPS;
    public static final /* enum */ INST_CODE INST_CVTTSD2SI;
    public static final /* enum */ INST_CODE INST_FCMOVB;
    public static final /* enum */ INST_CODE INST_PHSUBW;
    public static final /* enum */ INST_CODE INST_FABS;
    public static final /* enum */ INST_CODE INST_IDIV;
    public static final /* enum */ INST_CODE INST_CMOVNAE;
    public static final /* enum */ INST_CODE INST_PABSW;
    public static final /* enum */ INST_CODE INST_CMOVNG;
    public static final /* enum */ INST_CODE INST_DIVPD;
    public static final /* enum */ INST_CODE INST_CLD;
    public static final /* enum */ INST_CODE INST_JNE;
    public static final /* enum */ INST_CODE INST_SUBSS;
    public static final /* enum */ INST_CODE INST_MAXSD;
    public static final /* enum */ INST_CODE INST_PFCMPGT;
    public static final /* enum */ INST_CODE INST_CRC32;
    public static final /* enum */ INST_CODE INST_MOVUPS;
    public static final /* enum */ INST_CODE INST_MAXPD;
    public static final /* enum */ INST_CODE INST_PABSD;
    public static final /* enum */ INST_CODE INST_FLDENV;
    public static final /* enum */ INST_CODE INST_FXRSTOR;
    public static final /* enum */ INST_CODE INST_FBSTP;
    public static final /* enum */ INST_CODE INST_DAS;
    public static final /* enum */ INST_CODE INST_CALL;
    public static final /* enum */ INST_CODE INST_JNLE_SHORT;
    public static final /* enum */ INST_CODE INST_PACKSSWB;
    public static final /* enum */ INST_CODE INST_ROUNDPS;
    public static final /* enum */ INST_CODE INST_PADDB;
    public static final /* enum */ INST_CODE INST_PUNPCKHBW;
    public static final /* enum */ INST_CODE INST_CMOVNE;

    public static final INST_CODE valueOf(int idx) {
        return INST_CODE.values()[idx];
    }

    public static INST_CODE[] values() {
        return (INST_CODE[])$VALUES.clone();
    }

    public final boolean isShortJump() {
        return this.compareTo(INST_J_SHORT) >= 0 && this.compareTo(INST_JMP_SHORT) <= 0;
    }

    public static INST_CODE valueOf(String name) {
        return Enum.valueOf(INST_CODE.class, name);
    }

    static {
        INST_ADC = new INST_CODE();
        INST_ADD = new INST_CODE();
        INST_ADDPD = new INST_CODE();
        INST_ADDPS = new INST_CODE();
        INST_ADDSD = new INST_CODE();
        INST_ADDSS = new INST_CODE();
        INST_ADDSUBPD = new INST_CODE();
        INST_ADDSUBPS = new INST_CODE();
        INST_AMD_PREFETCH = new INST_CODE();
        INST_AMD_PREFETCHW = new INST_CODE();
        INST_AND = new INST_CODE();
        INST_ANDNPD = new INST_CODE();
        INST_ANDNPS = new INST_CODE();
        INST_ANDPD = new INST_CODE();
        INST_ANDPS = new INST_CODE();
        INST_BLENDPD = new INST_CODE();
        INST_BLENDPS = new INST_CODE();
        INST_BLENDVPD = new INST_CODE();
        INST_BLENDVPS = new INST_CODE();
        INST_BSF = new INST_CODE();
        INST_BSR = new INST_CODE();
        INST_BSWAP = new INST_CODE();
        INST_BT = new INST_CODE();
        INST_BTC = new INST_CODE();
        INST_BTR = new INST_CODE();
        INST_BTS = new INST_CODE();
        INST_CALL = new INST_CODE();
        INST_CBW = new INST_CODE();
        INST_CDQE = new INST_CODE();
        INST_CLC = new INST_CODE();
        INST_CLD = new INST_CODE();
        INST_CLFLUSH = new INST_CODE();
        INST_CMC = new INST_CODE();
        INST_CMOVA = new INST_CODE();
        INST_CMOVAE = new INST_CODE();
        INST_CMOVB = new INST_CODE();
        INST_CMOVBE = new INST_CODE();
        INST_CMOVC = new INST_CODE();
        INST_CMOVE = new INST_CODE();
        INST_CMOVG = new INST_CODE();
        INST_CMOVGE = new INST_CODE();
        INST_CMOVL = new INST_CODE();
        INST_CMOVLE = new INST_CODE();
        INST_CMOVNA = new INST_CODE();
        INST_CMOVNAE = new INST_CODE();
        INST_CMOVNB = new INST_CODE();
        INST_CMOVNBE = new INST_CODE();
        INST_CMOVNC = new INST_CODE();
        INST_CMOVNE = new INST_CODE();
        INST_CMOVNG = new INST_CODE();
        INST_CMOVNGE = new INST_CODE();
        INST_CMOVNL = new INST_CODE();
        INST_CMOVNLE = new INST_CODE();
        INST_CMOVNO = new INST_CODE();
        INST_CMOVNP = new INST_CODE();
        INST_CMOVNS = new INST_CODE();
        INST_CMOVNZ = new INST_CODE();
        INST_CMOVO = new INST_CODE();
        INST_CMOVP = new INST_CODE();
        INST_CMOVPE = new INST_CODE();
        INST_CMOVPO = new INST_CODE();
        INST_CMOVS = new INST_CODE();
        INST_CMOVZ = new INST_CODE();
        INST_CMP = new INST_CODE();
        INST_CMPPD = new INST_CODE();
        INST_CMPPS = new INST_CODE();
        INST_CMPSD = new INST_CODE();
        INST_CMPSS = new INST_CODE();
        INST_CMPXCHG = new INST_CODE();
        INST_CMPXCHG16B = new INST_CODE();
        INST_CMPXCHG8B = new INST_CODE();
        INST_COMISD = new INST_CODE();
        INST_COMISS = new INST_CODE();
        INST_CPUID = new INST_CODE();
        INST_CRC32 = new INST_CODE();
        INST_CVTDQ2PD = new INST_CODE();
        INST_CVTDQ2PS = new INST_CODE();
        INST_CVTPD2DQ = new INST_CODE();
        INST_CVTPD2PI = new INST_CODE();
        INST_CVTPD2PS = new INST_CODE();
        INST_CVTPI2PD = new INST_CODE();
        INST_CVTPI2PS = new INST_CODE();
        INST_CVTPS2DQ = new INST_CODE();
        INST_CVTPS2PD = new INST_CODE();
        INST_CVTPS2PI = new INST_CODE();
        INST_CVTSD2SI = new INST_CODE();
        INST_CVTSD2SS = new INST_CODE();
        INST_CVTSI2SD = new INST_CODE();
        INST_CVTSI2SS = new INST_CODE();
        INST_CVTSS2SD = new INST_CODE();
        INST_CVTSS2SI = new INST_CODE();
        INST_CVTTPD2DQ = new INST_CODE();
        INST_CVTTPD2PI = new INST_CODE();
        INST_CVTTPS2DQ = new INST_CODE();
        INST_CVTTPS2PI = new INST_CODE();
        INST_CVTTSD2SI = new INST_CODE();
        INST_CVTTSS2SI = new INST_CODE();
        INST_CWDE = new INST_CODE();
        INST_DAA = new INST_CODE();
        INST_DAS = new INST_CODE();
        INST_DEC = new INST_CODE();
        INST_DIV = new INST_CODE();
        INST_DIVPD = new INST_CODE();
        INST_DIVPS = new INST_CODE();
        INST_DIVSD = new INST_CODE();
        INST_DIVSS = new INST_CODE();
        INST_DPPD = new INST_CODE();
        INST_DPPS = new INST_CODE();
        INST_EMMS = new INST_CODE();
        INST_ENTER = new INST_CODE();
        INST_EXTRACTPS = new INST_CODE();
        INST_F2XM1 = new INST_CODE();
        INST_FABS = new INST_CODE();
        INST_FADD = new INST_CODE();
        INST_FADDP = new INST_CODE();
        INST_FBLD = new INST_CODE();
        INST_FBSTP = new INST_CODE();
        INST_FCHS = new INST_CODE();
        INST_FCLEX = new INST_CODE();
        INST_FCMOVB = new INST_CODE();
        INST_FCMOVBE = new INST_CODE();
        INST_FCMOVE = new INST_CODE();
        INST_FCMOVNB = new INST_CODE();
        INST_FCMOVNBE = new INST_CODE();
        INST_FCMOVNE = new INST_CODE();
        INST_FCMOVNU = new INST_CODE();
        INST_FCMOVU = new INST_CODE();
        INST_FCOM = new INST_CODE();
        INST_FCOMI = new INST_CODE();
        INST_FCOMIP = new INST_CODE();
        INST_FCOMP = new INST_CODE();
        INST_FCOMPP = new INST_CODE();
        INST_FCOS = new INST_CODE();
        INST_FDECSTP = new INST_CODE();
        INST_FDIV = new INST_CODE();
        INST_FDIVP = new INST_CODE();
        INST_FDIVR = new INST_CODE();
        INST_FDIVRP = new INST_CODE();
        INST_FEMMS = new INST_CODE();
        INST_FFREE = new INST_CODE();
        INST_FIADD = new INST_CODE();
        INST_FICOM = new INST_CODE();
        INST_FICOMP = new INST_CODE();
        INST_FIDIV = new INST_CODE();
        INST_FIDIVR = new INST_CODE();
        INST_FILD = new INST_CODE();
        INST_FIMUL = new INST_CODE();
        INST_FINCSTP = new INST_CODE();
        INST_FINIT = new INST_CODE();
        INST_FIST = new INST_CODE();
        INST_FISTP = new INST_CODE();
        INST_FISTTP = new INST_CODE();
        INST_FISUB = new INST_CODE();
        INST_FISUBR = new INST_CODE();
        INST_FLD = new INST_CODE();
        INST_FLD1 = new INST_CODE();
        INST_FLDCW = new INST_CODE();
        INST_FLDENV = new INST_CODE();
        INST_FLDL2E = new INST_CODE();
        INST_FLDL2T = new INST_CODE();
        INST_FLDLG2 = new INST_CODE();
        INST_FLDLN2 = new INST_CODE();
        INST_FLDPI = new INST_CODE();
        INST_FLDZ = new INST_CODE();
        INST_FMUL = new INST_CODE();
        INST_FMULP = new INST_CODE();
        INST_FNCLEX = new INST_CODE();
        INST_FNINIT = new INST_CODE();
        INST_FNOP = new INST_CODE();
        INST_FNSAVE = new INST_CODE();
        INST_FNSTCW = new INST_CODE();
        INST_FNSTENV = new INST_CODE();
        INST_FNSTSW = new INST_CODE();
        INST_FPATAN = new INST_CODE();
        INST_FPREM = new INST_CODE();
        INST_FPREM1 = new INST_CODE();
        INST_FPTAN = new INST_CODE();
        INST_FRNDINT = new INST_CODE();
        INST_FRSTOR = new INST_CODE();
        INST_FSAVE = new INST_CODE();
        INST_FSCALE = new INST_CODE();
        INST_FSIN = new INST_CODE();
        INST_FSINCOS = new INST_CODE();
        INST_FSQRT = new INST_CODE();
        INST_FST = new INST_CODE();
        INST_FSTCW = new INST_CODE();
        INST_FSTENV = new INST_CODE();
        INST_FSTP = new INST_CODE();
        INST_FSTSW = new INST_CODE();
        INST_FSUB = new INST_CODE();
        INST_FSUBP = new INST_CODE();
        INST_FSUBR = new INST_CODE();
        INST_FSUBRP = new INST_CODE();
        INST_FTST = new INST_CODE();
        INST_FUCOM = new INST_CODE();
        INST_FUCOMI = new INST_CODE();
        INST_FUCOMIP = new INST_CODE();
        INST_FUCOMP = new INST_CODE();
        INST_FUCOMPP = new INST_CODE();
        INST_FWAIT = new INST_CODE();
        INST_FXAM = new INST_CODE();
        INST_FXCH = new INST_CODE();
        INST_FXRSTOR = new INST_CODE();
        INST_FXSAVE = new INST_CODE();
        INST_FXTRACT = new INST_CODE();
        INST_FYL2X = new INST_CODE();
        INST_FYL2XP1 = new INST_CODE();
        INST_HADDPD = new INST_CODE();
        INST_HADDPS = new INST_CODE();
        INST_HSUBPD = new INST_CODE();
        INST_HSUBPS = new INST_CODE();
        INST_IDIV = new INST_CODE();
        INST_IMUL = new INST_CODE();
        INST_INC = new INST_CODE();
        INST_INT3 = new INST_CODE();
        INST_JA = new INST_CODE();
        INST_JAE = new INST_CODE();
        INST_JB = new INST_CODE();
        INST_JBE = new INST_CODE();
        INST_JC = new INST_CODE();
        INST_JE = new INST_CODE();
        INST_JG = new INST_CODE();
        INST_JGE = new INST_CODE();
        INST_JL = new INST_CODE();
        INST_JLE = new INST_CODE();
        INST_JNA = new INST_CODE();
        INST_JNAE = new INST_CODE();
        INST_JNB = new INST_CODE();
        INST_JNBE = new INST_CODE();
        INST_JNC = new INST_CODE();
        INST_JNE = new INST_CODE();
        INST_JNG = new INST_CODE();
        INST_JNGE = new INST_CODE();
        INST_JNL = new INST_CODE();
        INST_JNLE = new INST_CODE();
        INST_JNO = new INST_CODE();
        INST_JNP = new INST_CODE();
        INST_JNS = new INST_CODE();
        INST_JNZ = new INST_CODE();
        INST_JO = new INST_CODE();
        INST_JP = new INST_CODE();
        INST_JPE = new INST_CODE();
        INST_JPO = new INST_CODE();
        INST_JS = new INST_CODE();
        INST_JZ = new INST_CODE();
        INST_JMP = new INST_CODE();
        INST_JA_SHORT = new INST_CODE();
        INST_JAE_SHORT = new INST_CODE();
        INST_JB_SHORT = new INST_CODE();
        INST_JBE_SHORT = new INST_CODE();
        INST_JC_SHORT = new INST_CODE();
        INST_JE_SHORT = new INST_CODE();
        INST_JG_SHORT = new INST_CODE();
        INST_JGE_SHORT = new INST_CODE();
        INST_JL_SHORT = new INST_CODE();
        INST_JLE_SHORT = new INST_CODE();
        INST_JNA_SHORT = new INST_CODE();
        INST_JNAE_SHORT = new INST_CODE();
        INST_JNB_SHORT = new INST_CODE();
        INST_JNBE_SHORT = new INST_CODE();
        INST_JNC_SHORT = new INST_CODE();
        INST_JNE_SHORT = new INST_CODE();
        INST_JNG_SHORT = new INST_CODE();
        INST_JNGE_SHORT = new INST_CODE();
        INST_JNL_SHORT = new INST_CODE();
        INST_JNLE_SHORT = new INST_CODE();
        INST_JNO_SHORT = new INST_CODE();
        INST_JNP_SHORT = new INST_CODE();
        INST_JNS_SHORT = new INST_CODE();
        INST_JNZ_SHORT = new INST_CODE();
        INST_JO_SHORT = new INST_CODE();
        INST_JP_SHORT = new INST_CODE();
        INST_JPE_SHORT = new INST_CODE();
        INST_JPO_SHORT = new INST_CODE();
        INST_JS_SHORT = new INST_CODE();
        INST_JZ_SHORT = new INST_CODE();
        INST_JMP_SHORT = new INST_CODE();
        INST_LDDQU = new INST_CODE();
        INST_LDMXCSR = new INST_CODE();
        INST_LEA = new INST_CODE();
        INST_LEAVE = new INST_CODE();
        INST_LFENCE = new INST_CODE();
        INST_LOCK = new INST_CODE();
        INST_MASKMOVDQU = new INST_CODE();
        INST_MASKMOVQ = new INST_CODE();
        INST_MAXPD = new INST_CODE();
        INST_MAXPS = new INST_CODE();
        INST_MAXSD = new INST_CODE();
        INST_MAXSS = new INST_CODE();
        INST_MFENCE = new INST_CODE();
        INST_MINPD = new INST_CODE();
        INST_MINPS = new INST_CODE();
        INST_MINSD = new INST_CODE();
        INST_MINSS = new INST_CODE();
        INST_MONITOR = new INST_CODE();
        INST_MOV = new INST_CODE();
        INST_MOVAPD = new INST_CODE();
        INST_MOVAPS = new INST_CODE();
        INST_MOVBE = new INST_CODE();
        INST_MOVD = new INST_CODE();
        INST_MOVDDUP = new INST_CODE();
        INST_MOVDQ2Q = new INST_CODE();
        INST_MOVDQA = new INST_CODE();
        INST_MOVDQU = new INST_CODE();
        INST_MOVHLPS = new INST_CODE();
        INST_MOVHPD = new INST_CODE();
        INST_MOVHPS = new INST_CODE();
        INST_MOVLHPS = new INST_CODE();
        INST_MOVLPD = new INST_CODE();
        INST_MOVLPS = new INST_CODE();
        INST_MOVMSKPD = new INST_CODE();
        INST_MOVMSKPS = new INST_CODE();
        INST_MOVNTDQ = new INST_CODE();
        INST_MOVNTDQA = new INST_CODE();
        INST_MOVNTI = new INST_CODE();
        INST_MOVNTPD = new INST_CODE();
        INST_MOVNTPS = new INST_CODE();
        INST_MOVNTQ = new INST_CODE();
        INST_MOVQ = new INST_CODE();
        INST_MOVQ2DQ = new INST_CODE();
        INST_MOVSD = new INST_CODE();
        INST_MOVSHDUP = new INST_CODE();
        INST_MOVSLDUP = new INST_CODE();
        INST_MOVSS = new INST_CODE();
        INST_MOVSX = new INST_CODE();
        INST_MOVSXD = new INST_CODE();
        INST_MOVUPD = new INST_CODE();
        INST_MOVUPS = new INST_CODE();
        INST_MOVZX = new INST_CODE();
        INST_MOV_PTR = new INST_CODE();
        INST_MPSADBW = new INST_CODE();
        INST_MUL = new INST_CODE();
        INST_MULPD = new INST_CODE();
        INST_MULPS = new INST_CODE();
        INST_MULSD = new INST_CODE();
        INST_MULSS = new INST_CODE();
        INST_MWAIT = new INST_CODE();
        INST_NEG = new INST_CODE();
        INST_NOP = new INST_CODE();
        INST_NOT = new INST_CODE();
        INST_OR = new INST_CODE();
        INST_ORPD = new INST_CODE();
        INST_ORPS = new INST_CODE();
        INST_PABSB = new INST_CODE();
        INST_PABSD = new INST_CODE();
        INST_PABSW = new INST_CODE();
        INST_PACKSSDW = new INST_CODE();
        INST_PACKSSWB = new INST_CODE();
        INST_PACKUSDW = new INST_CODE();
        INST_PACKUSWB = new INST_CODE();
        INST_PADDB = new INST_CODE();
        INST_PADDD = new INST_CODE();
        INST_PADDQ = new INST_CODE();
        INST_PADDSB = new INST_CODE();
        INST_PADDSW = new INST_CODE();
        INST_PADDUSB = new INST_CODE();
        INST_PADDUSW = new INST_CODE();
        INST_PADDW = new INST_CODE();
        INST_PALIGNR = new INST_CODE();
        INST_PAND = new INST_CODE();
        INST_PANDN = new INST_CODE();
        INST_PAUSE = new INST_CODE();
        INST_PAVGB = new INST_CODE();
        INST_PAVGW = new INST_CODE();
        INST_PBLENDVB = new INST_CODE();
        INST_PBLENDW = new INST_CODE();
        INST_PCMPEQB = new INST_CODE();
        INST_PCMPEQD = new INST_CODE();
        INST_PCMPEQQ = new INST_CODE();
        INST_PCMPEQW = new INST_CODE();
        INST_PCMPESTRI = new INST_CODE();
        INST_PCMPESTRM = new INST_CODE();
        INST_PCMPGTB = new INST_CODE();
        INST_PCMPGTD = new INST_CODE();
        INST_PCMPGTQ = new INST_CODE();
        INST_PCMPGTW = new INST_CODE();
        INST_PCMPISTRI = new INST_CODE();
        INST_PCMPISTRM = new INST_CODE();
        INST_PEXTRB = new INST_CODE();
        INST_PEXTRD = new INST_CODE();
        INST_PEXTRQ = new INST_CODE();
        INST_PEXTRW = new INST_CODE();
        INST_PF2ID = new INST_CODE();
        INST_PF2IW = new INST_CODE();
        INST_PFACC = new INST_CODE();
        INST_PFADD = new INST_CODE();
        INST_PFCMPEQ = new INST_CODE();
        INST_PFCMPGE = new INST_CODE();
        INST_PFCMPGT = new INST_CODE();
        INST_PFMAX = new INST_CODE();
        INST_PFMIN = new INST_CODE();
        INST_PFMUL = new INST_CODE();
        INST_PFNACC = new INST_CODE();
        INST_PFPNACC = new INST_CODE();
        INST_PFRCP = new INST_CODE();
        INST_PFRCPIT1 = new INST_CODE();
        INST_PFRCPIT2 = new INST_CODE();
        INST_PFRSQIT1 = new INST_CODE();
        INST_PFRSQRT = new INST_CODE();
        INST_PFSUB = new INST_CODE();
        INST_PFSUBR = new INST_CODE();
        INST_PHADDD = new INST_CODE();
        INST_PHADDSW = new INST_CODE();
        INST_PHADDW = new INST_CODE();
        INST_PHMINPOSUW = new INST_CODE();
        INST_PHSUBD = new INST_CODE();
        INST_PHSUBSW = new INST_CODE();
        INST_PHSUBW = new INST_CODE();
        INST_PI2FD = new INST_CODE();
        INST_PI2FW = new INST_CODE();
        INST_PINSRB = new INST_CODE();
        INST_PINSRD = new INST_CODE();
        INST_PINSRQ = new INST_CODE();
        INST_PINSRW = new INST_CODE();
        INST_PMADDUBSW = new INST_CODE();
        INST_PMADDWD = new INST_CODE();
        INST_PMAXSB = new INST_CODE();
        INST_PMAXSD = new INST_CODE();
        INST_PMAXSW = new INST_CODE();
        INST_PMAXUB = new INST_CODE();
        INST_PMAXUD = new INST_CODE();
        INST_PMAXUW = new INST_CODE();
        INST_PMINSB = new INST_CODE();
        INST_PMINSD = new INST_CODE();
        INST_PMINSW = new INST_CODE();
        INST_PMINUB = new INST_CODE();
        INST_PMINUD = new INST_CODE();
        INST_PMINUW = new INST_CODE();
        INST_PMOVMSKB = new INST_CODE();
        INST_PMOVSXBD = new INST_CODE();
        INST_PMOVSXBQ = new INST_CODE();
        INST_PMOVSXBW = new INST_CODE();
        INST_PMOVSXDQ = new INST_CODE();
        INST_PMOVSXWD = new INST_CODE();
        INST_PMOVSXWQ = new INST_CODE();
        INST_PMOVZXBD = new INST_CODE();
        INST_PMOVZXBQ = new INST_CODE();
        INST_PMOVZXBW = new INST_CODE();
        INST_PMOVZXDQ = new INST_CODE();
        INST_PMOVZXWD = new INST_CODE();
        INST_PMOVZXWQ = new INST_CODE();
        INST_PMULDQ = new INST_CODE();
        INST_PMULHRSW = new INST_CODE();
        INST_PMULHUW = new INST_CODE();
        INST_PMULHW = new INST_CODE();
        INST_PMULLD = new INST_CODE();
        INST_PMULLW = new INST_CODE();
        INST_PMULUDQ = new INST_CODE();
        INST_POP = new INST_CODE();
        INST_POPAD = new INST_CODE();
        INST_POPCNT = new INST_CODE();
        INST_POPFD = new INST_CODE();
        INST_POPFQ = new INST_CODE();
        INST_POR = new INST_CODE();
        INST_PREFETCH = new INST_CODE();
        INST_PSADBW = new INST_CODE();
        INST_PSHUFB = new INST_CODE();
        INST_PSHUFD = new INST_CODE();
        INST_PSHUFW = new INST_CODE();
        INST_PSHUFHW = new INST_CODE();
        INST_PSHUFLW = new INST_CODE();
        INST_PSIGNB = new INST_CODE();
        INST_PSIGND = new INST_CODE();
        INST_PSIGNW = new INST_CODE();
        INST_PSLLD = new INST_CODE();
        INST_PSLLDQ = new INST_CODE();
        INST_PSLLQ = new INST_CODE();
        INST_PSLLW = new INST_CODE();
        INST_PSRAD = new INST_CODE();
        INST_PSRAW = new INST_CODE();
        INST_PSRLD = new INST_CODE();
        INST_PSRLDQ = new INST_CODE();
        INST_PSRLQ = new INST_CODE();
        INST_PSRLW = new INST_CODE();
        INST_PSUBB = new INST_CODE();
        INST_PSUBD = new INST_CODE();
        INST_PSUBQ = new INST_CODE();
        INST_PSUBSB = new INST_CODE();
        INST_PSUBSW = new INST_CODE();
        INST_PSUBUSB = new INST_CODE();
        INST_PSUBUSW = new INST_CODE();
        INST_PSUBW = new INST_CODE();
        INST_PSWAPD = new INST_CODE();
        INST_PTEST = new INST_CODE();
        INST_PUNPCKHBW = new INST_CODE();
        INST_PUNPCKHDQ = new INST_CODE();
        INST_PUNPCKHQDQ = new INST_CODE();
        INST_PUNPCKHWD = new INST_CODE();
        INST_PUNPCKLBW = new INST_CODE();
        INST_PUNPCKLDQ = new INST_CODE();
        INST_PUNPCKLQDQ = new INST_CODE();
        INST_PUNPCKLWD = new INST_CODE();
        INST_PUSH = new INST_CODE();
        INST_PUSHAD = new INST_CODE();
        INST_PUSHFD = new INST_CODE();
        INST_PUSHFQ = new INST_CODE();
        INST_PXOR = new INST_CODE();
        INST_RCL = new INST_CODE();
        INST_RCPPS = new INST_CODE();
        INST_RCPSS = new INST_CODE();
        INST_RCR = new INST_CODE();
        INST_RDTSC = new INST_CODE();
        INST_RDTSCP = new INST_CODE();
        INST_RET = new INST_CODE();
        INST_ROL = new INST_CODE();
        INST_ROR = new INST_CODE();
        INST_ROUNDPD = new INST_CODE();
        INST_ROUNDPS = new INST_CODE();
        INST_ROUNDSD = new INST_CODE();
        INST_ROUNDSS = new INST_CODE();
        INST_RSQRTPS = new INST_CODE();
        INST_RSQRTSS = new INST_CODE();
        INST_SAHF = new INST_CODE();
        INST_SAL = new INST_CODE();
        INST_SAR = new INST_CODE();
        INST_SBB = new INST_CODE();
        INST_SETA = new INST_CODE();
        INST_SETAE = new INST_CODE();
        INST_SETB = new INST_CODE();
        INST_SETBE = new INST_CODE();
        INST_SETC = new INST_CODE();
        INST_SETE = new INST_CODE();
        INST_SETG = new INST_CODE();
        INST_SETGE = new INST_CODE();
        INST_SETL = new INST_CODE();
        INST_SETLE = new INST_CODE();
        INST_SETNA = new INST_CODE();
        INST_SETNAE = new INST_CODE();
        INST_SETNB = new INST_CODE();
        INST_SETNBE = new INST_CODE();
        INST_SETNC = new INST_CODE();
        INST_SETNE = new INST_CODE();
        INST_SETNG = new INST_CODE();
        INST_SETNGE = new INST_CODE();
        INST_SETNL = new INST_CODE();
        INST_SETNLE = new INST_CODE();
        INST_SETNO = new INST_CODE();
        INST_SETNP = new INST_CODE();
        INST_SETNS = new INST_CODE();
        INST_SETNZ = new INST_CODE();
        INST_SETO = new INST_CODE();
        INST_SETP = new INST_CODE();
        INST_SETPE = new INST_CODE();
        INST_SETPO = new INST_CODE();
        INST_SETS = new INST_CODE();
        INST_SETZ = new INST_CODE();
        INST_SFENCE = new INST_CODE();
        INST_SHL = new INST_CODE();
        INST_SHLD = new INST_CODE();
        INST_SHR = new INST_CODE();
        INST_SHRD = new INST_CODE();
        INST_SHUFPS = new INST_CODE();
        INST_SQRTPD = new INST_CODE();
        INST_SQRTPS = new INST_CODE();
        INST_SQRTSD = new INST_CODE();
        INST_SQRTSS = new INST_CODE();
        INST_STC = new INST_CODE();
        INST_STD = new INST_CODE();
        INST_STMXCSR = new INST_CODE();
        INST_SUB = new INST_CODE();
        INST_SUBPD = new INST_CODE();
        INST_SUBPS = new INST_CODE();
        INST_SUBSD = new INST_CODE();
        INST_SUBSS = new INST_CODE();
        INST_TEST = new INST_CODE();
        INST_UCOMISD = new INST_CODE();
        INST_UCOMISS = new INST_CODE();
        INST_UD2 = new INST_CODE();
        INST_UNPCKHPD = new INST_CODE();
        INST_UNPCKHPS = new INST_CODE();
        INST_UNPCKLPD = new INST_CODE();
        INST_UNPCKLPS = new INST_CODE();
        INST_XADD = new INST_CODE();
        INST_XCHG = new INST_CODE();
        INST_XOR = new INST_CODE();
        INST_XORPD = new INST_CODE();
        INST_XORPS = new INST_CODE();
        INST_CODE[] iNST_CODEArray = new INST_CODE[577];
        iNST_CODEArray[0] = INST_ADC;
        iNST_CODEArray[1] = INST_ADD;
        iNST_CODEArray[2] = INST_ADDPD;
        iNST_CODEArray[3] = INST_ADDPS;
        iNST_CODEArray[4] = INST_ADDSD;
        iNST_CODEArray[5] = INST_ADDSS;
        iNST_CODEArray[6] = INST_ADDSUBPD;
        iNST_CODEArray[7] = INST_ADDSUBPS;
        iNST_CODEArray[8] = INST_AMD_PREFETCH;
        iNST_CODEArray[9] = INST_AMD_PREFETCHW;
        iNST_CODEArray[10] = INST_AND;
        iNST_CODEArray[11] = INST_ANDNPD;
        iNST_CODEArray[12] = INST_ANDNPS;
        iNST_CODEArray[13] = INST_ANDPD;
        iNST_CODEArray[14] = INST_ANDPS;
        iNST_CODEArray[15] = INST_BLENDPD;
        iNST_CODEArray[16] = INST_BLENDPS;
        iNST_CODEArray[17] = INST_BLENDVPD;
        iNST_CODEArray[18] = INST_BLENDVPS;
        iNST_CODEArray[19] = INST_BSF;
        iNST_CODEArray[20] = INST_BSR;
        iNST_CODEArray[21] = INST_BSWAP;
        iNST_CODEArray[22] = INST_BT;
        iNST_CODEArray[23] = INST_BTC;
        iNST_CODEArray[24] = INST_BTR;
        iNST_CODEArray[25] = INST_BTS;
        iNST_CODEArray[26] = INST_CALL;
        iNST_CODEArray[27] = INST_CBW;
        iNST_CODEArray[28] = INST_CDQE;
        iNST_CODEArray[29] = INST_CLC;
        iNST_CODEArray[30] = INST_CLD;
        iNST_CODEArray[31] = INST_CLFLUSH;
        iNST_CODEArray[32] = INST_CMC;
        iNST_CODEArray[33] = INST_CMOVA;
        iNST_CODEArray[34] = INST_CMOVAE;
        iNST_CODEArray[35] = INST_CMOVB;
        iNST_CODEArray[36] = INST_CMOVBE;
        iNST_CODEArray[37] = INST_CMOVC;
        iNST_CODEArray[38] = INST_CMOVE;
        iNST_CODEArray[39] = INST_CMOVG;
        iNST_CODEArray[40] = INST_CMOVGE;
        iNST_CODEArray[41] = INST_CMOVL;
        iNST_CODEArray[42] = INST_CMOVLE;
        iNST_CODEArray[43] = INST_CMOVNA;
        iNST_CODEArray[44] = INST_CMOVNAE;
        iNST_CODEArray[45] = INST_CMOVNB;
        iNST_CODEArray[46] = INST_CMOVNBE;
        iNST_CODEArray[47] = INST_CMOVNC;
        iNST_CODEArray[48] = INST_CMOVNE;
        iNST_CODEArray[49] = INST_CMOVNG;
        iNST_CODEArray[50] = INST_CMOVNGE;
        iNST_CODEArray[51] = INST_CMOVNL;
        iNST_CODEArray[52] = INST_CMOVNLE;
        iNST_CODEArray[53] = INST_CMOVNO;
        iNST_CODEArray[54] = INST_CMOVNP;
        iNST_CODEArray[55] = INST_CMOVNS;
        iNST_CODEArray[56] = INST_CMOVNZ;
        iNST_CODEArray[57] = INST_CMOVO;
        iNST_CODEArray[58] = INST_CMOVP;
        iNST_CODEArray[59] = INST_CMOVPE;
        iNST_CODEArray[60] = INST_CMOVPO;
        iNST_CODEArray[61] = INST_CMOVS;
        iNST_CODEArray[62] = INST_CMOVZ;
        iNST_CODEArray[63] = INST_CMP;
        iNST_CODEArray[64] = INST_CMPPD;
        iNST_CODEArray[65] = INST_CMPPS;
        iNST_CODEArray[66] = INST_CMPSD;
        iNST_CODEArray[67] = INST_CMPSS;
        iNST_CODEArray[68] = INST_CMPXCHG;
        iNST_CODEArray[69] = INST_CMPXCHG16B;
        iNST_CODEArray[70] = INST_CMPXCHG8B;
        iNST_CODEArray[71] = INST_COMISD;
        iNST_CODEArray[72] = INST_COMISS;
        iNST_CODEArray[73] = INST_CPUID;
        iNST_CODEArray[74] = INST_CRC32;
        iNST_CODEArray[75] = INST_CVTDQ2PD;
        iNST_CODEArray[76] = INST_CVTDQ2PS;
        iNST_CODEArray[77] = INST_CVTPD2DQ;
        iNST_CODEArray[78] = INST_CVTPD2PI;
        iNST_CODEArray[79] = INST_CVTPD2PS;
        iNST_CODEArray[80] = INST_CVTPI2PD;
        iNST_CODEArray[81] = INST_CVTPI2PS;
        iNST_CODEArray[82] = INST_CVTPS2DQ;
        iNST_CODEArray[83] = INST_CVTPS2PD;
        iNST_CODEArray[84] = INST_CVTPS2PI;
        iNST_CODEArray[85] = INST_CVTSD2SI;
        iNST_CODEArray[86] = INST_CVTSD2SS;
        iNST_CODEArray[87] = INST_CVTSI2SD;
        iNST_CODEArray[88] = INST_CVTSI2SS;
        iNST_CODEArray[89] = INST_CVTSS2SD;
        iNST_CODEArray[90] = INST_CVTSS2SI;
        iNST_CODEArray[91] = INST_CVTTPD2DQ;
        iNST_CODEArray[92] = INST_CVTTPD2PI;
        iNST_CODEArray[93] = INST_CVTTPS2DQ;
        iNST_CODEArray[94] = INST_CVTTPS2PI;
        iNST_CODEArray[95] = INST_CVTTSD2SI;
        iNST_CODEArray[96] = INST_CVTTSS2SI;
        iNST_CODEArray[97] = INST_CWDE;
        iNST_CODEArray[98] = INST_DAA;
        iNST_CODEArray[99] = INST_DAS;
        iNST_CODEArray[100] = INST_DEC;
        iNST_CODEArray[101] = INST_DIV;
        iNST_CODEArray[102] = INST_DIVPD;
        iNST_CODEArray[103] = INST_DIVPS;
        iNST_CODEArray[104] = INST_DIVSD;
        iNST_CODEArray[105] = INST_DIVSS;
        iNST_CODEArray[106] = INST_DPPD;
        iNST_CODEArray[107] = INST_DPPS;
        iNST_CODEArray[108] = INST_EMMS;
        iNST_CODEArray[109] = INST_ENTER;
        iNST_CODEArray[110] = INST_EXTRACTPS;
        iNST_CODEArray[111] = INST_F2XM1;
        iNST_CODEArray[112] = INST_FABS;
        iNST_CODEArray[113] = INST_FADD;
        iNST_CODEArray[114] = INST_FADDP;
        iNST_CODEArray[115] = INST_FBLD;
        iNST_CODEArray[116] = INST_FBSTP;
        iNST_CODEArray[117] = INST_FCHS;
        iNST_CODEArray[118] = INST_FCLEX;
        iNST_CODEArray[119] = INST_FCMOVB;
        iNST_CODEArray[120] = INST_FCMOVBE;
        iNST_CODEArray[121] = INST_FCMOVE;
        iNST_CODEArray[122] = INST_FCMOVNB;
        iNST_CODEArray[123] = INST_FCMOVNBE;
        iNST_CODEArray[124] = INST_FCMOVNE;
        iNST_CODEArray[125] = INST_FCMOVNU;
        iNST_CODEArray[126] = INST_FCMOVU;
        iNST_CODEArray[127] = INST_FCOM;
        iNST_CODEArray[128] = INST_FCOMI;
        iNST_CODEArray[129] = INST_FCOMIP;
        iNST_CODEArray[130] = INST_FCOMP;
        iNST_CODEArray[131] = INST_FCOMPP;
        iNST_CODEArray[132] = INST_FCOS;
        iNST_CODEArray[133] = INST_FDECSTP;
        iNST_CODEArray[134] = INST_FDIV;
        iNST_CODEArray[135] = INST_FDIVP;
        iNST_CODEArray[136] = INST_FDIVR;
        iNST_CODEArray[137] = INST_FDIVRP;
        iNST_CODEArray[138] = INST_FEMMS;
        iNST_CODEArray[139] = INST_FFREE;
        iNST_CODEArray[140] = INST_FIADD;
        iNST_CODEArray[141] = INST_FICOM;
        iNST_CODEArray[142] = INST_FICOMP;
        iNST_CODEArray[143] = INST_FIDIV;
        iNST_CODEArray[144] = INST_FIDIVR;
        iNST_CODEArray[145] = INST_FILD;
        iNST_CODEArray[146] = INST_FIMUL;
        iNST_CODEArray[147] = INST_FINCSTP;
        iNST_CODEArray[148] = INST_FINIT;
        iNST_CODEArray[149] = INST_FIST;
        iNST_CODEArray[150] = INST_FISTP;
        iNST_CODEArray[151] = INST_FISTTP;
        iNST_CODEArray[152] = INST_FISUB;
        iNST_CODEArray[153] = INST_FISUBR;
        iNST_CODEArray[154] = INST_FLD;
        iNST_CODEArray[155] = INST_FLD1;
        iNST_CODEArray[156] = INST_FLDCW;
        iNST_CODEArray[157] = INST_FLDENV;
        iNST_CODEArray[158] = INST_FLDL2E;
        iNST_CODEArray[159] = INST_FLDL2T;
        iNST_CODEArray[160] = INST_FLDLG2;
        iNST_CODEArray[161] = INST_FLDLN2;
        iNST_CODEArray[162] = INST_FLDPI;
        iNST_CODEArray[163] = INST_FLDZ;
        iNST_CODEArray[164] = INST_FMUL;
        iNST_CODEArray[165] = INST_FMULP;
        iNST_CODEArray[166] = INST_FNCLEX;
        iNST_CODEArray[167] = INST_FNINIT;
        iNST_CODEArray[168] = INST_FNOP;
        iNST_CODEArray[169] = INST_FNSAVE;
        iNST_CODEArray[170] = INST_FNSTCW;
        iNST_CODEArray[171] = INST_FNSTENV;
        iNST_CODEArray[172] = INST_FNSTSW;
        iNST_CODEArray[173] = INST_FPATAN;
        iNST_CODEArray[174] = INST_FPREM;
        iNST_CODEArray[175] = INST_FPREM1;
        iNST_CODEArray[176] = INST_FPTAN;
        iNST_CODEArray[177] = INST_FRNDINT;
        iNST_CODEArray[178] = INST_FRSTOR;
        iNST_CODEArray[179] = INST_FSAVE;
        iNST_CODEArray[180] = INST_FSCALE;
        iNST_CODEArray[181] = INST_FSIN;
        iNST_CODEArray[182] = INST_FSINCOS;
        iNST_CODEArray[183] = INST_FSQRT;
        iNST_CODEArray[184] = INST_FST;
        iNST_CODEArray[185] = INST_FSTCW;
        iNST_CODEArray[186] = INST_FSTENV;
        iNST_CODEArray[187] = INST_FSTP;
        iNST_CODEArray[188] = INST_FSTSW;
        iNST_CODEArray[189] = INST_FSUB;
        iNST_CODEArray[190] = INST_FSUBP;
        iNST_CODEArray[191] = INST_FSUBR;
        iNST_CODEArray[192] = INST_FSUBRP;
        iNST_CODEArray[193] = INST_FTST;
        iNST_CODEArray[194] = INST_FUCOM;
        iNST_CODEArray[195] = INST_FUCOMI;
        iNST_CODEArray[196] = INST_FUCOMIP;
        iNST_CODEArray[197] = INST_FUCOMP;
        iNST_CODEArray[198] = INST_FUCOMPP;
        iNST_CODEArray[199] = INST_FWAIT;
        iNST_CODEArray[200] = INST_FXAM;
        iNST_CODEArray[201] = INST_FXCH;
        iNST_CODEArray[202] = INST_FXRSTOR;
        iNST_CODEArray[203] = INST_FXSAVE;
        iNST_CODEArray[204] = INST_FXTRACT;
        iNST_CODEArray[205] = INST_FYL2X;
        iNST_CODEArray[206] = INST_FYL2XP1;
        iNST_CODEArray[207] = INST_HADDPD;
        iNST_CODEArray[208] = INST_HADDPS;
        iNST_CODEArray[209] = INST_HSUBPD;
        iNST_CODEArray[210] = INST_HSUBPS;
        iNST_CODEArray[211] = INST_IDIV;
        iNST_CODEArray[212] = INST_IMUL;
        iNST_CODEArray[213] = INST_INC;
        iNST_CODEArray[214] = INST_INT3;
        iNST_CODEArray[215] = INST_JA;
        iNST_CODEArray[216] = INST_JAE;
        iNST_CODEArray[217] = INST_JB;
        iNST_CODEArray[218] = INST_JBE;
        iNST_CODEArray[219] = INST_JC;
        iNST_CODEArray[220] = INST_JE;
        iNST_CODEArray[221] = INST_JG;
        iNST_CODEArray[222] = INST_JGE;
        iNST_CODEArray[223] = INST_JL;
        iNST_CODEArray[224] = INST_JLE;
        iNST_CODEArray[225] = INST_JNA;
        iNST_CODEArray[226] = INST_JNAE;
        iNST_CODEArray[227] = INST_JNB;
        iNST_CODEArray[228] = INST_JNBE;
        iNST_CODEArray[229] = INST_JNC;
        iNST_CODEArray[230] = INST_JNE;
        iNST_CODEArray[231] = INST_JNG;
        iNST_CODEArray[232] = INST_JNGE;
        iNST_CODEArray[233] = INST_JNL;
        iNST_CODEArray[234] = INST_JNLE;
        iNST_CODEArray[235] = INST_JNO;
        iNST_CODEArray[236] = INST_JNP;
        iNST_CODEArray[237] = INST_JNS;
        iNST_CODEArray[238] = INST_JNZ;
        iNST_CODEArray[239] = INST_JO;
        iNST_CODEArray[240] = INST_JP;
        iNST_CODEArray[241] = INST_JPE;
        iNST_CODEArray[242] = INST_JPO;
        iNST_CODEArray[243] = INST_JS;
        iNST_CODEArray[244] = INST_JZ;
        iNST_CODEArray[245] = INST_JMP;
        iNST_CODEArray[246] = INST_JA_SHORT;
        iNST_CODEArray[247] = INST_JAE_SHORT;
        iNST_CODEArray[248] = INST_JB_SHORT;
        iNST_CODEArray[249] = INST_JBE_SHORT;
        iNST_CODEArray[250] = INST_JC_SHORT;
        iNST_CODEArray[251] = INST_JE_SHORT;
        iNST_CODEArray[252] = INST_JG_SHORT;
        iNST_CODEArray[253] = INST_JGE_SHORT;
        iNST_CODEArray[254] = INST_JL_SHORT;
        iNST_CODEArray[255] = INST_JLE_SHORT;
        iNST_CODEArray[256] = INST_JNA_SHORT;
        iNST_CODEArray[257] = INST_JNAE_SHORT;
        iNST_CODEArray[258] = INST_JNB_SHORT;
        iNST_CODEArray[259] = INST_JNBE_SHORT;
        iNST_CODEArray[260] = INST_JNC_SHORT;
        iNST_CODEArray[261] = INST_JNE_SHORT;
        iNST_CODEArray[262] = INST_JNG_SHORT;
        iNST_CODEArray[263] = INST_JNGE_SHORT;
        iNST_CODEArray[264] = INST_JNL_SHORT;
        iNST_CODEArray[265] = INST_JNLE_SHORT;
        iNST_CODEArray[266] = INST_JNO_SHORT;
        iNST_CODEArray[267] = INST_JNP_SHORT;
        iNST_CODEArray[268] = INST_JNS_SHORT;
        iNST_CODEArray[269] = INST_JNZ_SHORT;
        iNST_CODEArray[270] = INST_JO_SHORT;
        iNST_CODEArray[271] = INST_JP_SHORT;
        iNST_CODEArray[272] = INST_JPE_SHORT;
        iNST_CODEArray[273] = INST_JPO_SHORT;
        iNST_CODEArray[274] = INST_JS_SHORT;
        iNST_CODEArray[275] = INST_JZ_SHORT;
        iNST_CODEArray[276] = INST_JMP_SHORT;
        iNST_CODEArray[277] = INST_LDDQU;
        iNST_CODEArray[278] = INST_LDMXCSR;
        iNST_CODEArray[279] = INST_LEA;
        iNST_CODEArray[280] = INST_LEAVE;
        iNST_CODEArray[281] = INST_LFENCE;
        iNST_CODEArray[282] = INST_LOCK;
        iNST_CODEArray[283] = INST_MASKMOVDQU;
        iNST_CODEArray[284] = INST_MASKMOVQ;
        iNST_CODEArray[285] = INST_MAXPD;
        iNST_CODEArray[286] = INST_MAXPS;
        iNST_CODEArray[287] = INST_MAXSD;
        iNST_CODEArray[288] = INST_MAXSS;
        iNST_CODEArray[289] = INST_MFENCE;
        iNST_CODEArray[290] = INST_MINPD;
        iNST_CODEArray[291] = INST_MINPS;
        iNST_CODEArray[292] = INST_MINSD;
        iNST_CODEArray[293] = INST_MINSS;
        iNST_CODEArray[294] = INST_MONITOR;
        iNST_CODEArray[295] = INST_MOV;
        iNST_CODEArray[296] = INST_MOVAPD;
        iNST_CODEArray[297] = INST_MOVAPS;
        iNST_CODEArray[298] = INST_MOVBE;
        iNST_CODEArray[299] = INST_MOVD;
        iNST_CODEArray[300] = INST_MOVDDUP;
        iNST_CODEArray[301] = INST_MOVDQ2Q;
        iNST_CODEArray[302] = INST_MOVDQA;
        iNST_CODEArray[303] = INST_MOVDQU;
        iNST_CODEArray[304] = INST_MOVHLPS;
        iNST_CODEArray[305] = INST_MOVHPD;
        iNST_CODEArray[306] = INST_MOVHPS;
        iNST_CODEArray[307] = INST_MOVLHPS;
        iNST_CODEArray[308] = INST_MOVLPD;
        iNST_CODEArray[309] = INST_MOVLPS;
        iNST_CODEArray[310] = INST_MOVMSKPD;
        iNST_CODEArray[311] = INST_MOVMSKPS;
        iNST_CODEArray[312] = INST_MOVNTDQ;
        iNST_CODEArray[313] = INST_MOVNTDQA;
        iNST_CODEArray[314] = INST_MOVNTI;
        iNST_CODEArray[315] = INST_MOVNTPD;
        iNST_CODEArray[316] = INST_MOVNTPS;
        iNST_CODEArray[317] = INST_MOVNTQ;
        iNST_CODEArray[318] = INST_MOVQ;
        iNST_CODEArray[319] = INST_MOVQ2DQ;
        iNST_CODEArray[320] = INST_MOVSD;
        iNST_CODEArray[321] = INST_MOVSHDUP;
        iNST_CODEArray[322] = INST_MOVSLDUP;
        iNST_CODEArray[323] = INST_MOVSS;
        iNST_CODEArray[324] = INST_MOVSX;
        iNST_CODEArray[325] = INST_MOVSXD;
        iNST_CODEArray[326] = INST_MOVUPD;
        iNST_CODEArray[327] = INST_MOVUPS;
        iNST_CODEArray[328] = INST_MOVZX;
        iNST_CODEArray[329] = INST_MOV_PTR;
        iNST_CODEArray[330] = INST_MPSADBW;
        iNST_CODEArray[331] = INST_MUL;
        iNST_CODEArray[332] = INST_MULPD;
        iNST_CODEArray[333] = INST_MULPS;
        iNST_CODEArray[334] = INST_MULSD;
        iNST_CODEArray[335] = INST_MULSS;
        iNST_CODEArray[336] = INST_MWAIT;
        iNST_CODEArray[337] = INST_NEG;
        iNST_CODEArray[338] = INST_NOP;
        iNST_CODEArray[339] = INST_NOT;
        iNST_CODEArray[340] = INST_OR;
        iNST_CODEArray[341] = INST_ORPD;
        iNST_CODEArray[342] = INST_ORPS;
        iNST_CODEArray[343] = INST_PABSB;
        iNST_CODEArray[344] = INST_PABSD;
        iNST_CODEArray[345] = INST_PABSW;
        iNST_CODEArray[346] = INST_PACKSSDW;
        iNST_CODEArray[347] = INST_PACKSSWB;
        iNST_CODEArray[348] = INST_PACKUSDW;
        iNST_CODEArray[349] = INST_PACKUSWB;
        iNST_CODEArray[350] = INST_PADDB;
        iNST_CODEArray[351] = INST_PADDD;
        iNST_CODEArray[352] = INST_PADDQ;
        iNST_CODEArray[353] = INST_PADDSB;
        iNST_CODEArray[354] = INST_PADDSW;
        iNST_CODEArray[355] = INST_PADDUSB;
        iNST_CODEArray[356] = INST_PADDUSW;
        iNST_CODEArray[357] = INST_PADDW;
        iNST_CODEArray[358] = INST_PALIGNR;
        iNST_CODEArray[359] = INST_PAND;
        iNST_CODEArray[360] = INST_PANDN;
        iNST_CODEArray[361] = INST_PAUSE;
        iNST_CODEArray[362] = INST_PAVGB;
        iNST_CODEArray[363] = INST_PAVGW;
        iNST_CODEArray[364] = INST_PBLENDVB;
        iNST_CODEArray[365] = INST_PBLENDW;
        iNST_CODEArray[366] = INST_PCMPEQB;
        iNST_CODEArray[367] = INST_PCMPEQD;
        iNST_CODEArray[368] = INST_PCMPEQQ;
        iNST_CODEArray[369] = INST_PCMPEQW;
        iNST_CODEArray[370] = INST_PCMPESTRI;
        iNST_CODEArray[371] = INST_PCMPESTRM;
        iNST_CODEArray[372] = INST_PCMPGTB;
        iNST_CODEArray[373] = INST_PCMPGTD;
        iNST_CODEArray[374] = INST_PCMPGTQ;
        iNST_CODEArray[375] = INST_PCMPGTW;
        iNST_CODEArray[376] = INST_PCMPISTRI;
        iNST_CODEArray[377] = INST_PCMPISTRM;
        iNST_CODEArray[378] = INST_PEXTRB;
        iNST_CODEArray[379] = INST_PEXTRD;
        iNST_CODEArray[380] = INST_PEXTRQ;
        iNST_CODEArray[381] = INST_PEXTRW;
        iNST_CODEArray[382] = INST_PF2ID;
        iNST_CODEArray[383] = INST_PF2IW;
        iNST_CODEArray[384] = INST_PFACC;
        iNST_CODEArray[385] = INST_PFADD;
        iNST_CODEArray[386] = INST_PFCMPEQ;
        iNST_CODEArray[387] = INST_PFCMPGE;
        iNST_CODEArray[388] = INST_PFCMPGT;
        iNST_CODEArray[389] = INST_PFMAX;
        iNST_CODEArray[390] = INST_PFMIN;
        iNST_CODEArray[391] = INST_PFMUL;
        iNST_CODEArray[392] = INST_PFNACC;
        iNST_CODEArray[393] = INST_PFPNACC;
        iNST_CODEArray[394] = INST_PFRCP;
        iNST_CODEArray[395] = INST_PFRCPIT1;
        iNST_CODEArray[396] = INST_PFRCPIT2;
        iNST_CODEArray[397] = INST_PFRSQIT1;
        iNST_CODEArray[398] = INST_PFRSQRT;
        iNST_CODEArray[399] = INST_PFSUB;
        iNST_CODEArray[400] = INST_PFSUBR;
        iNST_CODEArray[401] = INST_PHADDD;
        iNST_CODEArray[402] = INST_PHADDSW;
        iNST_CODEArray[403] = INST_PHADDW;
        iNST_CODEArray[404] = INST_PHMINPOSUW;
        iNST_CODEArray[405] = INST_PHSUBD;
        iNST_CODEArray[406] = INST_PHSUBSW;
        iNST_CODEArray[407] = INST_PHSUBW;
        iNST_CODEArray[408] = INST_PI2FD;
        iNST_CODEArray[409] = INST_PI2FW;
        iNST_CODEArray[410] = INST_PINSRB;
        iNST_CODEArray[411] = INST_PINSRD;
        iNST_CODEArray[412] = INST_PINSRQ;
        iNST_CODEArray[413] = INST_PINSRW;
        iNST_CODEArray[414] = INST_PMADDUBSW;
        iNST_CODEArray[415] = INST_PMADDWD;
        iNST_CODEArray[416] = INST_PMAXSB;
        iNST_CODEArray[417] = INST_PMAXSD;
        iNST_CODEArray[418] = INST_PMAXSW;
        iNST_CODEArray[419] = INST_PMAXUB;
        iNST_CODEArray[420] = INST_PMAXUD;
        iNST_CODEArray[421] = INST_PMAXUW;
        iNST_CODEArray[422] = INST_PMINSB;
        iNST_CODEArray[423] = INST_PMINSD;
        iNST_CODEArray[424] = INST_PMINSW;
        iNST_CODEArray[425] = INST_PMINUB;
        iNST_CODEArray[426] = INST_PMINUD;
        iNST_CODEArray[427] = INST_PMINUW;
        iNST_CODEArray[428] = INST_PMOVMSKB;
        iNST_CODEArray[429] = INST_PMOVSXBD;
        iNST_CODEArray[430] = INST_PMOVSXBQ;
        iNST_CODEArray[431] = INST_PMOVSXBW;
        iNST_CODEArray[432] = INST_PMOVSXDQ;
        iNST_CODEArray[433] = INST_PMOVSXWD;
        iNST_CODEArray[434] = INST_PMOVSXWQ;
        iNST_CODEArray[435] = INST_PMOVZXBD;
        iNST_CODEArray[436] = INST_PMOVZXBQ;
        iNST_CODEArray[437] = INST_PMOVZXBW;
        iNST_CODEArray[438] = INST_PMOVZXDQ;
        iNST_CODEArray[439] = INST_PMOVZXWD;
        iNST_CODEArray[440] = INST_PMOVZXWQ;
        iNST_CODEArray[441] = INST_PMULDQ;
        iNST_CODEArray[442] = INST_PMULHRSW;
        iNST_CODEArray[443] = INST_PMULHUW;
        iNST_CODEArray[444] = INST_PMULHW;
        iNST_CODEArray[445] = INST_PMULLD;
        iNST_CODEArray[446] = INST_PMULLW;
        iNST_CODEArray[447] = INST_PMULUDQ;
        iNST_CODEArray[448] = INST_POP;
        iNST_CODEArray[449] = INST_POPAD;
        iNST_CODEArray[450] = INST_POPCNT;
        iNST_CODEArray[451] = INST_POPFD;
        iNST_CODEArray[452] = INST_POPFQ;
        iNST_CODEArray[453] = INST_POR;
        iNST_CODEArray[454] = INST_PREFETCH;
        iNST_CODEArray[455] = INST_PSADBW;
        iNST_CODEArray[456] = INST_PSHUFB;
        iNST_CODEArray[457] = INST_PSHUFD;
        iNST_CODEArray[458] = INST_PSHUFW;
        iNST_CODEArray[459] = INST_PSHUFHW;
        iNST_CODEArray[460] = INST_PSHUFLW;
        iNST_CODEArray[461] = INST_PSIGNB;
        iNST_CODEArray[462] = INST_PSIGND;
        iNST_CODEArray[463] = INST_PSIGNW;
        iNST_CODEArray[464] = INST_PSLLD;
        iNST_CODEArray[465] = INST_PSLLDQ;
        iNST_CODEArray[466] = INST_PSLLQ;
        iNST_CODEArray[467] = INST_PSLLW;
        iNST_CODEArray[468] = INST_PSRAD;
        iNST_CODEArray[469] = INST_PSRAW;
        iNST_CODEArray[470] = INST_PSRLD;
        iNST_CODEArray[471] = INST_PSRLDQ;
        iNST_CODEArray[472] = INST_PSRLQ;
        iNST_CODEArray[473] = INST_PSRLW;
        iNST_CODEArray[474] = INST_PSUBB;
        iNST_CODEArray[475] = INST_PSUBD;
        iNST_CODEArray[476] = INST_PSUBQ;
        iNST_CODEArray[477] = INST_PSUBSB;
        iNST_CODEArray[478] = INST_PSUBSW;
        iNST_CODEArray[479] = INST_PSUBUSB;
        iNST_CODEArray[480] = INST_PSUBUSW;
        iNST_CODEArray[481] = INST_PSUBW;
        iNST_CODEArray[482] = INST_PSWAPD;
        iNST_CODEArray[483] = INST_PTEST;
        iNST_CODEArray[484] = INST_PUNPCKHBW;
        iNST_CODEArray[485] = INST_PUNPCKHDQ;
        iNST_CODEArray[486] = INST_PUNPCKHQDQ;
        iNST_CODEArray[487] = INST_PUNPCKHWD;
        iNST_CODEArray[488] = INST_PUNPCKLBW;
        iNST_CODEArray[489] = INST_PUNPCKLDQ;
        iNST_CODEArray[490] = INST_PUNPCKLQDQ;
        iNST_CODEArray[491] = INST_PUNPCKLWD;
        iNST_CODEArray[492] = INST_PUSH;
        iNST_CODEArray[493] = INST_PUSHAD;
        iNST_CODEArray[494] = INST_PUSHFD;
        iNST_CODEArray[495] = INST_PUSHFQ;
        iNST_CODEArray[496] = INST_PXOR;
        iNST_CODEArray[497] = INST_RCL;
        iNST_CODEArray[498] = INST_RCPPS;
        iNST_CODEArray[499] = INST_RCPSS;
        iNST_CODEArray[500] = INST_RCR;
        iNST_CODEArray[501] = INST_RDTSC;
        iNST_CODEArray[502] = INST_RDTSCP;
        iNST_CODEArray[503] = INST_RET;
        iNST_CODEArray[504] = INST_ROL;
        iNST_CODEArray[505] = INST_ROR;
        iNST_CODEArray[506] = INST_ROUNDPD;
        iNST_CODEArray[507] = INST_ROUNDPS;
        iNST_CODEArray[508] = INST_ROUNDSD;
        iNST_CODEArray[509] = INST_ROUNDSS;
        iNST_CODEArray[510] = INST_RSQRTPS;
        iNST_CODEArray[511] = INST_RSQRTSS;
        iNST_CODEArray[512] = INST_SAHF;
        iNST_CODEArray[513] = INST_SAL;
        iNST_CODEArray[514] = INST_SAR;
        iNST_CODEArray[515] = INST_SBB;
        iNST_CODEArray[516] = INST_SETA;
        iNST_CODEArray[517] = INST_SETAE;
        iNST_CODEArray[518] = INST_SETB;
        iNST_CODEArray[519] = INST_SETBE;
        iNST_CODEArray[520] = INST_SETC;
        iNST_CODEArray[521] = INST_SETE;
        iNST_CODEArray[522] = INST_SETG;
        iNST_CODEArray[523] = INST_SETGE;
        iNST_CODEArray[524] = INST_SETL;
        iNST_CODEArray[525] = INST_SETLE;
        iNST_CODEArray[526] = INST_SETNA;
        iNST_CODEArray[527] = INST_SETNAE;
        iNST_CODEArray[528] = INST_SETNB;
        iNST_CODEArray[529] = INST_SETNBE;
        iNST_CODEArray[530] = INST_SETNC;
        iNST_CODEArray[531] = INST_SETNE;
        iNST_CODEArray[532] = INST_SETNG;
        iNST_CODEArray[533] = INST_SETNGE;
        iNST_CODEArray[534] = INST_SETNL;
        iNST_CODEArray[535] = INST_SETNLE;
        iNST_CODEArray[536] = INST_SETNO;
        iNST_CODEArray[537] = INST_SETNP;
        iNST_CODEArray[538] = INST_SETNS;
        iNST_CODEArray[539] = INST_SETNZ;
        iNST_CODEArray[540] = INST_SETO;
        iNST_CODEArray[541] = INST_SETP;
        iNST_CODEArray[542] = INST_SETPE;
        iNST_CODEArray[543] = INST_SETPO;
        iNST_CODEArray[544] = INST_SETS;
        iNST_CODEArray[545] = INST_SETZ;
        iNST_CODEArray[546] = INST_SFENCE;
        iNST_CODEArray[547] = INST_SHL;
        iNST_CODEArray[548] = INST_SHLD;
        iNST_CODEArray[549] = INST_SHR;
        iNST_CODEArray[550] = INST_SHRD;
        iNST_CODEArray[551] = INST_SHUFPS;
        iNST_CODEArray[552] = INST_SQRTPD;
        iNST_CODEArray[553] = INST_SQRTPS;
        iNST_CODEArray[554] = INST_SQRTSD;
        iNST_CODEArray[555] = INST_SQRTSS;
        iNST_CODEArray[556] = INST_STC;
        iNST_CODEArray[557] = INST_STD;
        iNST_CODEArray[558] = INST_STMXCSR;
        iNST_CODEArray[559] = INST_SUB;
        iNST_CODEArray[560] = INST_SUBPD;
        iNST_CODEArray[561] = INST_SUBPS;
        iNST_CODEArray[562] = INST_SUBSD;
        iNST_CODEArray[563] = INST_SUBSS;
        iNST_CODEArray[564] = INST_TEST;
        iNST_CODEArray[565] = INST_UCOMISD;
        iNST_CODEArray[566] = INST_UCOMISS;
        iNST_CODEArray[567] = INST_UD2;
        iNST_CODEArray[568] = INST_UNPCKHPD;
        iNST_CODEArray[569] = INST_UNPCKHPS;
        iNST_CODEArray[570] = INST_UNPCKLPD;
        iNST_CODEArray[571] = INST_UNPCKLPS;
        iNST_CODEArray[572] = INST_XADD;
        iNST_CODEArray[573] = INST_XCHG;
        iNST_CODEArray[574] = INST_XOR;
        iNST_CODEArray[575] = INST_XORPD;
        iNST_CODEArray[576] = INST_XORPS;
        $VALUES = iNST_CODEArray;
        INST_J = INST_JA;
        INST_J_SHORT = INST_JA_SHORT;
    }
}

