org.gradle.jvmargs=-Xmx6G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3
fabric_api_version=0.141.5+1.21.11
fabric_kotlin_version=1.13.12+kotlin.2.4.0
mod_version=1.0.0-recovered
maven_group=kotakbaz.rain
archives_base_name=rain-visuals-recovered
