plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

repositories {
}

loom {
	mods {
		"wexside" {
			sourceSet sourceSets.main
		}
	}
	runs {
		client {
			if (project.hasProperty('wexQuickPlay')) {
				programArgs("--quickPlaySingleplayer", String.valueOf(project.property('wexQuickPlay')))
			}
			if (project.hasProperty('wexDebug')) {
				vmArgs("-Dwexside.debug.targetesp=true")
			}
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.layered { }
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	fileTree(dir: 'libs', include: '*.jar').each { lib ->
		implementation files(lib)
	}
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
	it.options.encoding = 'UTF-8'
	it.options.compilerArgs += ['-Xmaxerrs', '999999', '-Xmaxwarns', '999999']
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}
