/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  com.google.common.collect.ImmutableList
 *  com.mojang.datafixers.util.Pair
 */
package lightning.product;

import com.google.common.collect.ImmutableList;
import com.mojang.datafixers.util.Pair;
import java.util.List;
import java.util.function.Function;
import lightning.product.Pools;
import lightning.product.X_2241_P;
import lightning.product.ProcessorLists;
import lightning.product.g_2336_b;
import lightning.product.StructurePoolElement;

public class Q_2369_t {
    public static void n_1700_B() {
    }

    static {
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/starting_pieces"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/starting_stairs_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/starting_stairs_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/starting_stairs_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/starting_stairs_3", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/starting_stairs_4", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/mirrored_starting_pieces"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/stairs_0_mirrored", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/stairs_1_mirrored", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/stairs_2_mirrored", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/stairs_3_mirrored", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/starting_pieces/stairs_4_mirrored", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/wall_bases"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/walls/wall_base", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/walls"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/walls/side_wall_0", ProcessorLists.Q_2552_b), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/walls/side_wall_1", ProcessorLists.Q_2552_b), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/stairs"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_1_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_1_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_1_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_1_3", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_1_4", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_2_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_2_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_2_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_2_3", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_2_4", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_3_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_3_1", ProcessorLists.C_2741_M), (Object)1), (Object[])new Pair[]{Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_3_2", ProcessorLists.C_2741_M), (Object)1), Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_3_3", ProcessorLists.C_2741_M), (Object)1), Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/stairs/stairs_3_4", ProcessorLists.C_2741_M), (Object)1)}), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/small_stables/inner"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/inner_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/inner_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/inner_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/inner_3", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/small_stables/outer"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/outer_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/outer_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/outer_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/small_stables/outer_3", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/large_stables/inner"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/inner_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/inner_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/inner_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/inner_3", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/inner_4", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/large_stables/outer"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/outer_0", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/outer_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/outer_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/outer_3", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/large_stables/outer_4", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/posts"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/posts/stair_post", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/posts/end_post", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/ramparts"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/ramparts/ramparts_1", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/ramparts/ramparts_2", ProcessorLists.C_2741_M), (Object)1), (Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/ramparts/ramparts_3", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/rampart_plates"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/rampart_plates/rampart_plate_1", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
        Pools.n_1700_B(new X_2241_P(new g_2336_b("bastion/hoglin_stable/connectors"), new g_2336_b("empty"), (List<Pair<Function<X_2241_P.n_1700_B, ? extends StructurePoolElement>, Integer>>)ImmutableList.of((Object)Pair.of(StructurePoolElement.J_1907_R("bastion/hoglin_stable/connectors/end_post_connector", ProcessorLists.C_2741_M), (Object)1)), X_2241_P.n_1700_B.J_1907_R));
    }
}


